### ISSUE TITLE
Pin room to top

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#100]
Hi,
it would be nice if we can pin some rooms to top list. currently the top room will be the one has latest message. But some room (or contact) are more important like family member, it's would be nice to pin them to top even they don't have latest messages. although it's possible to do it by room action, but it would be helpful to show some UI changes such as a Pin icon etc.

**Comment by antoine92190** [comment]
That's a good idea.
I have already planned to rework the automatic rooms ordering to make it more flexible.
I can also add a `starred` property to each `room` to highlight the room.

**Comment by antoine92190** [comment]
Actually, this feature seems too specific to be implemented.
But I added an id for all rooms and messages, so you can use that to achieve what you want.
For example you can change the `background-color` of a specific room like this:

```
const elem = document.getElementById('ROOM_ID')
elem.setAttribute('style', 'background-color: #fcba03 !important');
```

You could also add a star emoji to the `roomName` of any room you want:
```
roomName: "⭐ My room"
```

**Comment by Clansty** [comment]
I use special `index` for pinned rooms. Pining rooms will set their index to `1`, and when new message comes to any room, just bring it to the front of the array

```js
this.rooms = [room, ...this.rooms.filter(item => item !== room)];
//bring the room first
```
