### ISSUE TITLE
Updating messages results in jittery scroll

### ISSUE THREAD

**Issue by j4hangir** [antoine92190/vue-advanced-chat#103]
When scrolling to top and fetching more messages, the scroll will be jittery. This only happens when there's a system message, such as the date separating the messages, and as long as that date is present the problem remains. 

I manually removed the _system message DOM_ and the problem vanished.

**Comment by j4hangir** [comment]
The stopgap I use for now:

```js
const scroller = document.getElementsByClassName('vac-container-scroll')[0];

self.messages = [...fetched, ...self.messages]

for (const element of document.getElementsByClassName('vac-card-info')) {
    scroller.scrollTop -= (element.offsetHeight * fetched.length)
}
```


It's acceptable, but not as smooth.

**Comment by antoine92190** [comment]
I cannot reproduce. On which browser are you testing?
Could you share a minimal component that reproduces the issue?

**Comment by j4hangir** [comment]
https://user-images.githubusercontent.com/7769125/103484056-154e3680-4dec-11eb-99e8-3a585d2ca9b6.mp4

On Chrome

**Comment by j4hangir** [comment]
Can see as soon as I remove the system message the scrolling goes back to normal, and also the code snippet above does make it smoother.

**Comment by antoine92190** [comment]
Should be fixed in https://github.com/antoine92190/vue-advanced-chat/commit/882352979e2c08c237ebc9a7e7ea4f5b5ba860c4
Please confirm.

**Comment by j4hangir** [comment]
It's resolved 👍🏻
