### ISSUE TITLE
Is there any Event fires when we click on room back button?

### ISSUE THREAD

**Issue by hanatharesh2712** [antoine92190/vue-advanced-chat#105]
Is there any Event fires when we click on room back button?
Or any workaround for this? How to know the user has open any room or not?

![image](https://user-images.githubusercontent.com/17156331/103504854-a372fd00-4e7e-11eb-8179-268e775bb15a.png)

**Comment by antoine92190** [comment]
No there isn't at the moment, will add it soon.
You can know if the user has opened a room using `fetch-messages` event.

**Comment by j4hangir** [comment]
> No there isn't at the moment, will add it soon.
> You can know if the user has opened a room using `fetch-messages` event.

Yes, by checking for `options?.reset`.

Also for back button I've manually bound to the button's class, but a proper event would be nice.

**Comment by hanatharesh2712** [comment]
Yes, I have done it in this way.
```

  async mounted(this: any) {
        const chatToggle: any = document.getElementsByClassName('toggle-button');
        if (chatToggle && chatToggle[0]) {
            chatToggle[0].onclick = this.closeSingleRoom;
        }
    },
     methods: {
         async closeSingleRoom(this: any) {
           // Do something
        },
    }
```

But, I totally agree that we should do it in a proper way.
Thanks!

**Comment by antoine92190** [comment]
`toggle-rooms-list` added: https://github.com/antoine92190/vue-advanced-chat/commit/2423a9c24e49cb4ee600bb1fded279c5abaf99a0
