### ISSUE TITLE
Menu actions not added

### ISSUE THREAD

**Issue by j4hangir** [antoine92190/vue-advanced-chat#106]
![image](https://user-images.githubusercontent.com/7769125/103561674-1fd70180-4eba-11eb-9f5e-d84be4164280.png)

My config:

![image](https://user-images.githubusercontent.com/7769125/103561696-29f90000-4eba-11eb-8f09-28d8d5aa87ce.png)

**Comment by j4hangir** [comment]
It was the same in previous version, and I'm using version `0.6.3` now still the same.

**Comment by j4hangir** [comment]
Menu actions are the suggested:

![image](https://user-images.githubusercontent.com/7769125/103562084-c9b68e00-4eba-11eb-9f47-ef9038f3a57c.png)

**Comment by antoine92190** [comment]
I don't see `menuActions` passed as a prop in your first screenshot: `:menu-actions="menuActions"`

**Comment by j4hangir** [comment]
Thank you, silly mistake 👍🏻
