### ISSUE TITLE
Improve audio player

### ISSUE THREAD

**Issue by j4hangir** [antoine92190/vue-advanced-chat#107]
The current use of `<audio ..>` seems too limited, even the duration isn't shown before playing the track first, and there's apparently no way in HTML to specify that.

![image](https://user-images.githubusercontent.com/7769125/103681810-3fd4f680-4f88-11eb-9fb1-59dd06f16837.png)

I think I'd be able to fix this one.

**Comment by antoine92190** [comment]
Yes, I didn't have time to polish this feature. You are more than welcome to improve it with a PR :)

**Comment by antoine92190** [comment]
@j4hangir Are you working on a PR for this feature? Otherwise I'll work on it soon

**Comment by j4hangir** [comment]
Please work on it, I researched before but surprisingly didn't find anything suitable to use...

Cheers,
Jay
________________________________

**Comment by antoine92190** [comment]
Fixed is v0.7.3: https://github.com/antoine92190/vue-advanced-chat/releases/tag/0.7.3
