### ISSUE TITLE
Tapping message emojis doesn't do anything

### ISSUE THREAD

**Issue by j4hangir** [antoine92190/vue-advanced-chat#108]
Reaction emojis show up for me, but clicking on the emojis button next to send button does nothing. Is this expected behavior?

![image](https://user-images.githubusercontent.com/7769125/103682431-2c765b00-4f89-11eb-8cb6-213a8322387c.png)

**Comment by antoine92190** [comment]
That's strange. I cannot reproduce on the demo: https://antoine92190.github.io/vue-advanced-chat/
Can you? Otherwise which browser/device are you using?

**Comment by j4hangir** [comment]
> That's strange. I cannot reproduce on the demo: https://antoine92190.github.io/vue-advanced-chat/
> Can you? Otherwise which browser/device are you using?

The demo works fine, I'm using Chrome.

**Comment by j4hangir** [comment]
I also tested with `Firefox` and `Edge`, just nothing happens when tapping on it.

**Comment by j4hangir** [comment]
Thru debugger I confirmed the function,

```js
openEmoji: function openEmoji(ev) {
      this.$emit('open-emoji', true);
      this.setEmojiPickerPosition(ev.clientY, ev.view.innerWidth, ev.view.innerHeight);
    },
```

does get called, but nothing happens.

**Comment by j4hangir** [comment]
The difference when clicking on the message emojis is that the code ends up running here:

![image](https://user-images.githubusercontent.com/7769125/103710610-b9cfa480-4fb5-11eb-81f8-24cb22b0bf11.png)

In reactions case, `roomFooterRef` is defined!

**Comment by antoine92190** [comment]
So the demo works fine on Chrome, Firefox and Edge?
If yes, then I guess the issue comes from your code.
Can you share a minimal component code snippet that reproduces your issue?

**Comment by j4hangir** [comment]
Well I'm using it as a component:

```js
<template>
    <v-ons-page>
        <chat-window
            :theme="theme"
            :current-user-id="myUserId"
            :rooms="topics"
            :single-room="false"
            :is-mobile="true"
            :messages="messages"
            :messages-loaded="messagesLoaded"
            :show-add-room="true"
            accepted-files="*"
            :message-actions="messageActions"
            :menu-actions="menuActions"
            :loading-rooms="loadingRooms"
            :rooms-loaded="topicsLoaded"
            @fetch-messages="fetchMessages"
            @send-message="sendMessage"
            @edit-message="editMessage"
            @delete-message="deleteMessage"
            @menu-action-handler="menuActionHandler"
            @message-action-handler="messageActionHandler"
            @send-message-reaction="sendMessageReaction"
            @room-info="topicInfo"
            @typing-message="hmessages.sendKeyPress"/>
    </v-ons-page>
    <!--    @open-file="openFile"-->
    <!--    @add-room="addRoom"-->
</template>
```

Looks like one strange bug/conflicting code.

**Comment by antoine92190** [comment]
I meant a full working component so I can reproduce the issue on my side. Without reproducing, it will be difficult for me to help.
Also, I see that you modified the chat code, as `is-mobile` prop doesn't exist in my code.
Have you confirmed the issue appears in the original chat component?

**Comment by antoine92190** [comment]
It looks like the emoji picker on your screenshot is very tall. Have you overridden the css to achieve that?

**Comment by j4hangir** [comment]
> It looks like the emoji picker on your screenshot is very tall. Have you overridden the css to achieve that?

I investigated further, the problem is this `top` attribute:

![image](https://user-images.githubusercontent.com/7769125/104140643-bf146100-53b2-11eb-9765-392dd53c8f00.png)


It's very strange to be added there, I looked into your CSS files there's no top defined there for `vac-emoji-picker`, and the one added to the html (visible in the image) is also weirdly commented, yet chrome still - for another strange reason - applies it.


I tested the component alone and it works fine, I guess that make it 99% something in my code, I'll investigate more and if so will close this.
