### ISSUE TITLE
Increase infinite messages scroll distance

### ISSUE THREAD

**Issue by j4hangir** [antoine92190/vue-advanced-chat#111]
I suggest the `fetch-messages` occur as soon as the user is *approaching* the end of list rather than actually _reaching_ it. At the moment the function's called only when user's actually reached the top, which in turn will always lead to a little lagging xp. 

This distance could be halved, or even be customized by a `approaching` prop, e.g. `fetch-distance=0.5`, as in the user is half-way of a full-scroll to reaching to the top, whichever better.

A default number might also be preferred and perhaps only a boolean to toggle it.

**Comment by antoine92190** [comment]
I agree the scrolling distance would be better if increased as in versions < `0.6.5`, but then the scroll behaviour is very unpredictable (especially on mobile devices).
I will try to improve that, but it will take some time as it may lead to a lot of refactoring

**Comment by j4hangir** [comment]
I actually had a feeling it was _prefetching_ on `0.6.3`, I guess that got changed in `0.6.5`?

In my imagination it's just a matter of calling `fetch-messages` earlier, I gotta read the code to find out why it might cause a lot of refactoring.

**Comment by antoine92190** [comment]
Yes it was the case in versions prior ´0.6.5´. The difficulty is not calling ´fetch-messages´ earlier, it’s making the scroll stable on all browsers and devices. For some reasons, scroll becomes jumpy when we start adding DOM elements without scrolling to the very top before.

**Comment by antoine92190** [comment]
Prop added in https://github.com/antoine92190/vue-advanced-chat/commit/9c72f2b6df5b7474fdea2fdffed673ffac9acee5
