### ISSUE TITLE
Emojis autocompletion

### ISSUE THREAD

**Issue by j4hangir** [antoine92190/vue-advanced-chat#112]
As a low-priority feature, it's quite nice to have this emojis autocompletion feature eventually implemented:

![image](https://user-images.githubusercontent.com/7769125/104140026-8757ea00-53af-11eb-87cf-d9e421525b5b.png)

This is very handy when composing texts, maybe I can also give a hand on this.

**Comment by antoine92190** [comment]
Yes I agree, feel free to send a PR for that 🙂

**Comment by antoine92190** [comment]
Feature addded in https://github.com/antoine92190/vue-advanced-chat/releases/tag/0.7.4
