### ISSUE TITLE
Add new message indicator when scrolled up

### ISSUE THREAD

**Issue by antoine92190** [antoine92190/vue-advanced-chat#115]
Current behaviour: When a user has scrolled up to load more messages and receives a new message, it will automatically scroll to the bottom.
Instead, we should show a new message indicator and prevent the automatic bottom scroll.

**Comment by j4hangir** [comment]
I was just about to post this. Please make it **automatically scroll to bottom** behave less surprisingly:

* Automatic scrolling unless user scrolled up
* When user has scrolled up, no more automatic scrolling, unless used the `new message indicator` or manually scrolled to the bottom.

**Comment by antoine92190** [comment]
Feature added in https://github.com/antoine92190/vue-advanced-chat/commit/4b8be3cfa6c40dfbd7f75c55fa3fa1ce8b68f15b
