### ISSUE TITLE
Implement basic routing

### ISSUE THREAD

**Issue by mgralikowski** [antoine92190/vue-advanced-chat#116]
What do You think about implementing basic routing to conversations/rooms and optionally to initial screen new like a Facebook messenger?

URLs could be looks like this:
https://vue-advanced-chat.herokuapp.com/chat/[id] ex. 
https://vue-advanced-chat.herokuapp.com/chat/0hdt2xFHafgw2VLy4I4Ju0SeQgF2
and optional new conversation:
https://vue-advanced-chat.herokuapp.com/chat/new

It would be very useful to linking to conversations, improve navigation, and useability.

Without using any routing library:

In RoomList:

```this.$emit('openRoom', this.room)```

Handling click:
```
// open room, fetch messages etc..
window.history.pushState(room, null, baseUrl+ chat/[id]);
```

And sth like this in creating/init component:
```
    this.openRoom(id); // id from props (server can pass id from URL and pass to component) or directly from url

    window.onpopstate = (event) => {
      if (event.state) {
        if (event.state.id) {
          this.openRoom(event.state.id);
        } else {
          this.initNewConversation(); 
        }
      }
    }
```
Thanks to this we handle navigation buttons (forward / next).

**Comment by antoine92190** [comment]
I like the idea, as long as there is a prop to activate/deactivate this feature. Will you send a PR for that?

**Comment by antoine92190** [comment]
Actually, can you not implement this feature outside the component scope? You could implement routing when `fetch-messages` event is triggered, would that work?
Even if I like the idea, any implementation that can be done outside the component is encouraged in order to keep the component light and simple, and not enforcing specific behaviour.
