### ISSUE TITLE
Unread message indicator

### ISSUE THREAD

**Issue by sam26880** [antoine92190/vue-advanced-chat#118]
## Is your feature request related to a problem? Please describe
No

## Describe the solution you'd like
When there are new messages for me, it should have an indicator showing exactly how many messages are new in a specific chat room that I haven't checked yet.

**Comment by antoine92190** [comment]
You can add `unreadCount` for each room in `rooms` prop: https://github.com/antoine92190/vue-advanced-chat#rooms-prop

**Comment by sam26880** [comment]
> You can use `unreadCount` for each room in `rooms` prop: https://github.com/antoine92190/vue-advanced-chat#rooms-prop

I was looking at your demo source at [https://github.com/antoine92190/vue-advanced-chat/blob/master/demo/src/ChatContainer.vue](https://github.com/antoine92190/vue-advanced-chat/blob/master/demo/src/ChatContainer.vue)

and I don't see that "unreadCount" property is being set.

**Comment by antoine92190** [comment]
I don’t showcase every feature and option in the demo, for that you should refer to the readme
