### ISSUE TITLE
 v 5.0.8 & v 5.09 failure using quasar

### ISSUE THREAD

**Issue by lapinzon** [antoine92190/vue-advanced-chat#120]
using quasar the versions > 5.0.7 :
- when open a room, doesnt receive @fetchMessage, then still showing the image loading
- the back button (toggle-rooms-list) doesnt respond to click.

That works fine with v 5.0.6 & v 5.0.7

**Comment by antoine92190** [comment]
You mean chat version or quasar version?
The lastest chat version is 0.6.9 and the latest quasar version seems to be 1.15.1.
Am I missing something?

**Comment by lapinzon** [comment]
Sorry by the swapping. My test with chat 0.5.6 & 0.5.7 works fine, chat 0.5.9 & 0.5.9 with the fail.
I will test with 0.6.9

**Comment by lapinzon** [comment]
Sorry by the swapping. My test with chat 0.5.6 & 0.5.7 works fine, chat 0.5.9 & 0.5.9 with the fail.
I will test with 0.6.9

**Comment by lapinzon** [comment]
Now, testing chat 0.6.9 the issue is similar with 0.5.9  in chat,  $emit('fetch-messages',...) doesnt fire the event declared in  <chat-window @fetchMessages=" ...>

**Comment by antoine92190** [comment]
It's because the events syntax has been changed: https://github.com/antoine92190/vue-advanced-chat/releases/tag/0.5.8

**Comment by lapinzon** [comment]
Thanks antoine, nice work
