### ISSUE TITLE
No image preview with WebP format

### ISSUE THREAD

**Issue by Clansty** [antoine92190/vue-advanced-chat#122]
Image preview doesn't show up when sending or receiving picture with WebP format (`image/webp`) unless I change `message.file.type` to `image/jpeg` or some other image types

I hope it can recognize `image/webp` as pictures

**Comment by antoine92190** [comment]
WebP format added: https://github.com/antoine92190/vue-advanced-chat/commit/7ce0b4c551a36c95adbc52843bf7d40e1171562f
