### ISSUE TITLE
Text formatting

### ISSUE THREAD

**Issue by mgralikowski** [antoine92190/vue-advanced-chat#124]
Small bug in formatting. Let's assume:

`**I want bold text**`

Expected:

**I want bold text** or * **I want bold text** *

Result:

I want bold text (no bold, no asterisks).

And general question. Why custom standard instead of so common markdown standard? Many people, mostly developers, are used to using markdown :) and it is easier to use some ready to use parser like https://www.npmjs.com/package/vue-simple-markdown

**Comment by antoine92190** [comment]
Indeed that's a bug. I'll check that.
I don't really like using external packages, especially if it's not actively maintained.
Plus, `vue-simple-markdown` is a very heavy package: minified bundle is 268kb while the chat is only 76kb.

**Comment by mgralikowski** [comment]
It is more about using standard (markdown) instead custom one. I do not recommend any library to a Vue, maybe is easier to just adjust existing code to markdown standard. Markdown is universal across languages, for example I use it to message templating in PHP.

**Comment by antoine92190** [comment]
What do you mean by standard markdown?
The one I use is a mix between the one used by slack and github.

**Comment by mgralikowski** [comment]
Slack has custom standard, it is only similar to markdown. However Github follows markdown standard. 

https://www.markdownguide.org/basic-syntax/

First difference between both is bold/italic formatting.

**Comment by antoine92190** [comment]
Right, I think real users (not developers) are more used to slack custom standard.
I prefer to use that, but indeed I will fix this issue:
`*bold*` will be **bold**
`**bold**` will be **bold**
`***bold***` will be **bold**
Same for italic

**Comment by antoine92190** [comment]
I started working on this but it will be difficult to achieve.
I am open to ideas or help to implement a light and solid markdown implementation, as the current one has some flaws.

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/4212b386917fec1c26d55e9e67cb61a59017dcb1

**Comment by antoine92190** [comment]
Final behaviour is:
*bold* will be **bold**
**bold** will be ***bold***
***bold*** will be ****bold****
