### ISSUE TITLE
Files in storage are not removable [demo] [security]

### ISSUE THREAD

**Issue by mgralikowski** [antoine92190/vue-advanced-chat#126]
For now there is no dedicated button to remove file in post, and I think it is ok, but removing whole post remove only post record and file will stay accessible. This is problematic because costs, hard to track files without parent record (trash files) and it is a security risk  (for example I uploaded sth confidential in demo chat and some people can have still active to link do this file).

**Comment by antoine92190** [comment]
Fixed in d46e966 and c753f6c
