### ISSUE TITLE
Single room utilization

### ISSUE THREAD

**Issue by blurdylan** [antoine92190/vue-advanced-chat#128]
## Describe the bug
My use case needs the chat to work with multiple users under a single-room (like a single group chat instance). As far as the docs says, we need to add the attribute `single-room` and then add my array of `messages`. This looks great. However I do not have an input field and the room header is blank.

## Steps to reproduce

```
<chat-window
      single-room
      :rooms="[{}]"
      :current-user-id="currentUserId"
      :messages="chatData"
    >
```

## Expected behavior
Expected a room to be created with users and messages but without showing the side and header bar

## Screenshots
![image](https://user-images.githubusercontent.com/26802924/107522163-b1b9e480-6bb3-11eb-96d2-b9fc5f8f74b3.png)

## Device (please complete the following information)

- OS: OSX
- Browser: Chrome Canary, Mozilla
- Package version: 0.7.0

## Additional context

Ideally, if it was possible to make it act like a room with users inside but hide completely the room list and header, it would be good for me

**Comment by mgralikowski** [comment]
Hack just for a while:

```css
#chat-app .vac-room-header {
  display: none;
}
```

also, you can try to override some elements by slots (in my case I totally replaced the room header in some cases).

**Comment by blurdylan** [comment]
@mgralikowski  thanks, I'll add that to hide the header,

However, I was able to make it work using `room-id` attribute, whenever I am using single-room,

This should be mentioned as required in the docs when working with single rooms.

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/21536b55e2668e61f52a6cbbc42865ff7bd464d5

**Comment by antoine92190** [comment]
You are not required to use `room-id` anymore with `single-room`
