### ISSUE TITLE
(BUG) roomId type inconsistent

### ISSUE THREAD

**Issue by mryellow** [antoine92190/vue-advanced-chat#13]
`ChatWindow` has `roomId` as either `Number` or `String`:

https://github.com/antoine92190/vue-advanced-chat/blob/ef876a70b869cc0025841e30420b6de9a6e9b065/src/ChatWindow/ChatWindow.vue#L83

Where `Room` has it as `String` only:

https://github.com/antoine92190/vue-advanced-chat/blob/ef876a70b869cc0025841e30420b6de9a6e9b065/src/ChatWindow/Room.vue#L260

**Comment by antoine92190** [comment]
Fixed: https://github.com/antoine92190/vue-advanced-chat/commit/b44eae1b91a711e495d94ea2ec18fea4b8c972a8
