### ISSUE TITLE
Broken long rooms names

### ISSUE THREAD

**Issue by mgralikowski** [antoine92190/vue-advanced-chat#130]
Nothing important but long room names require some changes in CSS ;) ellipsis doesn't work.

![image](https://user-images.githubusercontent.com/17027876/107793829-0a75b280-6d57-11eb-8ca1-00ce2f8c50cc.png)

**Comment by antoine92190** [comment]
Yes it is fixed in https://github.com/antoine92190/vue-advanced-chat/commit/6abefb3e5214cadc002f66cb99244ee1ee5dffa9
Will release an update this weekend
