### ISSUE TITLE
Regression on 0.7.2

### ISSUE THREAD

**Issue by blurdylan** [antoine92190/vue-advanced-chat#131]
## Describe the bug
I tried implementing the single room from #128 , but it didn't work as expected. I have message errors (not being the right format) and the same issues when I remove the room-id when using it with a single room. Moreover, my messages sent were at the left (where recieved messages are supposed to stand)

## Steps to reproduce
Create a chat window component without room-id

## Expected behavior
Work as shown in the example but with a single room.

Right now I downgrade to 0.7.0 and I am using it with room-id

## Device (please complete the following information)

OS: OSX
Browser: Chrome Canary, Mozilla
Package version: 0.7.2

## Additional context
This is a great Vue package right here, however, I strongly recommend the author to add a minimal number of solid tests, this will strongly help the component scale and avoid such regressions

**Comment by antoine92190** [comment]
Please check https://github.com/antoine92190/vue-advanced-chat/releases/tag/0.7.1 for breaking changes

**Comment by antoine92190** [comment]
I agree about adding tests, but I will not be able to do it soon. If you want to give a hand you are more than welcome!
