### ISSUE TITLE
Is it supported by internet explorer version 10 ?

### ISSUE THREAD

**Issue by deepweller** [antoine92190/vue-advanced-chat#134]
Hi ! I have a question.
Is it supported by internet explorer version 10 ?
In version 11, after adding a few polyfills, it works.
However, it does not work in version 10.
Thank you.

**Comment by antoine92190** [comment]
I haven't added internet explore support.
If you want, you can send a pull request to improve IE support, otherwise I don't think I will work on that.

**Comment by deepweller** [comment]
Thanks for the quick reply.
