### ISSUE TITLE
lastMessage not updated.

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#135]
hi,
I am using 0.7.3 version. i set lastMessage when send new Message. 
`
   this.$set(this.rooms[i], 'lastMessage', this.formatLastMessage(event.message))

my lastMessage like: 
lastMessage:{
content: "hi"
date: "2021-02-18 12:46"
datetime: "2021-02-18T10:46:20.199Z"
new: false
seen: true
senderId: "1"
timestamp: "Today, 12:46"
_id: "602e457c04d1867a5b5e61d6"
}

I didn't set the saved, distributed field and username field, like the document:
lastMessage: {
      content: 'Last message received',
      senderId: 1234,
      username: 'John Doe',
      timestamp: '10:20',
      saved: true,
      distributed: false,
      seen: false,
      new: true
    },
`
do you know what's the reason causes the lastMessage not updated, i have to refresh the page to show the lastMessage.

**Comment by antoine92190** [comment]
This is wrong
```this.$set(this.rooms[i], 'lastMessage', this.formatLastMessage(event.message))```

It should be:
```
const roomIndex = this.rooms.find(room => room.id === roomId)

this.$set(this.rooms, roomIndex, {...this.rooms[i], lastMessage: this.formatLastMessage(event.message))
```

Or:
```
const roomIndex = this.rooms.find(room => room.id === roomId)

this.rooms[roomIndex] = {...room, this.formatLastMessage(event.message}
this.rooms = [...this.rooms]
```

**Comment by tingan** [comment]
hi, thx, it works, but your code has one typo, should be
 this.$set(this.rooms, i, {...this.rooms[i], lastMessage: this.formatLastMessage(event.message)})`
`
missing the }.
