### ISSUE TITLE
Lame Js dependency error

### ISSUE THREAD

**Issue by AlandEr2612** [antoine92190/vue-advanced-chat#136]
## Describe the bug

There is a problem with the new voice recorder feature, when i start the voice recorder a error in my console is present, i've already installed lamejs dependence but this error still appear.

I put the libraries in my index.html file in the following order:

```
 <!-- VueChatComponent -->
  <script src="/wap/geh/telemedicina/node_modules/lamejs/lame.all.js"></script>
  <script src="/wap/geh/telemedicina/node_modules/vue-advanced-chat/dist/vue-advanced-chat.umd.js"></script>
```

## Screenshots

![image](https://user-images.githubusercontent.com/9408682/108368819-e2f46f00-71c8-11eb-8d2d-e486eff1073a.png)

## Device (please complete the following information)

- OS: [Windows 10]
- Browser: [Microsoft Edge]
- Package version: [0.7.3]

**Comment by antoine92190** [comment]
Why do you need to import lamejs and vue-advanced-chat in `index.html` if you installed those using npm?

**Comment by antoine92190** [comment]
Can you try to import `vue-advanced-chat` in your component using the chat like this:
```
import ChatWindow from 'vue-advanced-chat'
import 'vue-advanced-chat/dist/vue-advanced-chat.css'
```

**Comment by AlandEr2612** [comment]
What happens is that my application is not made with Vue CLI, I dont have vue files create only js files, and the way I import the library to my project is through "cdn" so to speak. and the component I am importing like this:

![image](https://user-images.githubusercontent.com/9408682/108372996-6912b480-71cd-11eb-82b3-80dc878db1cf.png)

**Comment by AlandEr2612** [comment]
> Can you try to import `vue-advanced-chat` in your component using the chat like this:
> 
> ```
> import ChatWindow from 'vue-advanced-chat'
> import 'vue-advanced-chat/dist/vue-advanced-chat.css'
> ```

![image](https://user-images.githubusercontent.com/9408682/108374236-be9b9100-71ce-11eb-86e9-d3b04b5d7c5c.png)

**Comment by antoine92190** [comment]
Indeed I could reproduce the issue with lamejs import. Will fix it ASAP

**Comment by antoine92190** [comment]
Should be fixed in: https://github.com/antoine92190/vue-advanced-chat/commit/a2caf5ec490da38fd4e2e640fe855303acf69f78

**Comment by AlandEr2612** [comment]
Hi, now is working well, but there is a little issue when the voice recorder ends.

![image](https://user-images.githubusercontent.com/9408682/108511376-d38b2980-728d-11eb-97a4-ed5920c4e66a.png)

I've put a console.log() to see what value is sent in the method when the audio file is generated.

![image](https://user-images.githubusercontent.com/9408682/108511462-f0276180-728d-11eb-8532-fd457415230a.png)

**Comment by antoine92190** [comment]
Mmm it seems like a browser issue. Does the error appear systematically?
Is there anyway I could have access to your repo or a minimal example so I can reproduce on my side?

**Comment by AlandEr2612** [comment]
I'll close this ticket for now because the initial issue was fixed, but, i'll re open it to share with you a source code with a little example of my implementation, i'm short of time rigth now for make the example.

**Comment by antoine92190** [comment]
Ok thanks. Please open another issue when you have more info
