### ISSUE TITLE
New message divider behaviour

### ISSUE THREAD

**Issue by yantsz826** [antoine92190/vue-advanced-chat#137]
I found that in Room.vue the newMessages array will never got remove, is there any reason? 
Since if the newMessages array didn't got remove, the new message divider will keep on the screen. 
I added below code in the watcher of messages to remove the newMessages after message been seen, but not sure does it against your original purpose.
```javascript
messages(newVal, oldVal) {
  newVal.forEach(message => {
    this.newMessages = this.newMessages.filter(n => n._id = message._id && !n.seen)
      if (!messagesValid(message)) {
        throw new Error(
          'Messages object is not valid! Must contain _id[String, Number], content[String, Number] and senderId[String, Number]'
	)
    }
  })
  ...
} 
```

**Comment by antoine92190** [comment]
This is the expected behaviour.
The new message divider is displayed above the oldest unseen message, and it will be removed the next time you open this same room.
But I guess we could remove the new message divider once the use scrolled away from it.
Have you checked what is the behaviour of WhatsApp, Telegram, Messenger or Slack?

**Comment by antoine92190** [comment]
I checked, I think the expected behaviour should be to remove the new message divider after sending or receiving a new message. Will implement that shortly.

**Comment by yantsz826** [comment]
> I checked, I think the expected behaviour should be to remove the new message divider after sending or receiving a new message. Will implement that shortly.

Nice to hear that, thank you very much.

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/2a26e7e0a9f89700d5d22f8317018d7d5b2ec7f0
