### ISSUE TITLE
Vue 3 migration

### ISSUE THREAD

**Issue by pnutmath** [antoine92190/vue-advanced-chat#138]
are you planning to support vue 3? @antoine92190

**Comment by antoine92190** [comment]
Yes it’s planned. Not sure how difficult the migration is, so I cannot give any estimate at this point

**Comment by pnutmath** [comment]
I am in for Vue 3 migration @antoine92190

**Comment by antoine92190** [comment]
It is now possible to use this library with vue 3: https://github.com/antoine92190/vue-advanced-chat#use-in-a-vue-3-project
The usage is not perfect, but the library relies on other projects that are not migrated to vue 3 yet.
This should be soon available though: https://github.com/PeachScript/vue-infinite-loading/pull/312
Until then, you can use this workaround.

**Comment by antoine92190** [comment]
@rrolla Thanks! Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/f51fe724fdf09f61481b3d75086407a580b892df

**Comment by yaphuiyi** [comment]
@rrolla do you have the code in vue 3 syntax? I am trying to migrate the project to vue 3 but without success :( would appreciate if there is a version in vue 3

**Comment by rrolla** [comment]
> @rrolla do you have the code in vue 3 syntax? I am trying to migrate the project to vue 3 but without success :( would appreciate if there is a version in vue 3

Hey, I was able to run it on vue3 after my fix, what's above ^

**Comment by antoine92190** [comment]
> It is now possible to use this library with vue 3: https://github.com/antoine92190/vue-advanced-chat#use-in-a-vue-3-project The usage is not perfect, but the library relies on other projects that are not migrated to vue 3 yet. This should be soon available though: [PeachScript/vue-infinite-loading#312](https://github.com/PeachScript/vue-infinite-loading/pull/312) Until then, you can use this workaround.

The workaround above is not needed anymore, the `next` branch is now fully compatible with vue 3 🥳

**Comment by Sublime1** [comment]
Hi Antoine

just a quick question about the Vue 3 branch. I notice that you have been making a lot of changes to the Vue 2 branch but have not yet added these to the Vue 3 branch.

What are your plans regarding the Vue 3 branch? Do you plan to keep both Vue 2 and 3 versions up to date with new features? I presume that Vue 3 will become more important than Vue 2 in the long term.

Would love to hear your thoughts and thanks for an amazing library!

**Comment by antoine92190** [comment]
@Sublime1 Yes you are right, I didn't have the time to keep the vue 3 branch up to date.
I will try to keep it updated more often.

In the long term, I'm not yet 100% sure how I will manage the vue 2 and vue 3 branches, but I was thinking of making the vue 3 branch as default (master) and create a vue 2 branch. The vue 2 branch would then become a legacy one, and not be updated anymore.

If anyone has other ideas, I'm happy to hear it :)

**Comment by Sublime1** [comment]
Thanks Antoine. Yes, it's a tricky question, but I'm sure other projects are solving this issue too!

Maybe it's worth looking at the way that Vue themselves have done it: 2 separate repositories, each with its own releases.

Vue 2.x https://github.com/vuejs/vue
Vue 3.x https://github.com/vuejs/vue-next

thanks

**Comment by rrolla** [comment]
> @Sublime1 Yes you are right, I didn't have the time to keep the vue 3 branch up to date. I will try to keep it updated more often.
> 
> In the long term, I'm not yet 100% sure how I will manage the vue 2 and vue 3 branches, but I was thinking of making the vue 3 branch as default (master) and create a vue 2 branch. The vue 2 branch would then become a legacy one, and not be updated anymore.
> 
> If anyone has other ideas, I'm happy to hear it :)

Good idea about vue 3 as master branch

**Comment by antoine92190** [comment]
@Sublime1 The issue with creating 2 repo is that the new Vue 3 repo would loose all it's visibility and stars, which would be a huge SEO step back. This project doesn't have the hype of VueJS (yet 😄), so I'm not sure it's a good idea...

**Comment by Sublime1** [comment]
Yes, that's an important point. 

For me personally, at the moment I have forked your 2.x branch but want to switch to the 3.x version as soon as possible. If you will do what you are suggesting (switch the current "next" Vue 3 branch to become the default (master)), then I think probably the best approach for me is to merge your current "next" branch into my fork. 

Please let us know once you have clarity on exactly what you plan to do. Thanks again!

**Comment by antoine92190** [comment]
@Sublime1 Just update the next branch with latest updates
