### ISSUE TITLE
Polling Chat data without refresh page

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#140]
Hi,
Originally i used vue-advanced-chat for login users. So the data is push and pull by websockets. but now i added the chat for anonymous user by generating a uuid for anonymous user,  anonymous user cannot use Websocket authentication.I used a Polling technology
`
 pollData() {
                this.polling = setInterval(() => {
                    this.fetchRooms(false)
                }, 3000)
            },

async fetchRooms(reset=true) {
                if (reset) {
                    this.resetRooms()
                }
                await axios({
                    method: 'get',
                    url: url,
                }).then(response => {
                    if (response.status === 200) {
                        this.rooms = response.data
                        //this.rooms = [...response.data]
                        this.roomsLoaded = true
                    }
                }).catch(error => {
                    console.log(error)
                })
  resetRooms() {
                this.loadingRooms = true
                this.rooms = []
                this.resetMessages()
            },
`
If i resetRooms , the page will refresh and flash every 3 seconds, although the data is pulled or updated. if I don't resetRooms, the page will not refresh, but the messages is not updated in chat UI, (although the rooms variables did get the new updated messages).

any suggestion? thanks! It seems i need to call 
 fetchMessages({room, options = {}}) {}`
`
if i set  this.messagesLoaded = false before fetchRooms, the fetchMessages will be called once, but not in a repeated way. I need the fetchMessages function to be called regularly e.g. every 3 seconds.

**Comment by antoine92190** [comment]
Your implementation is not part of the chat component scope.

To update messages, you just need to update the messages prop like:
```
this.messages = [...this.messages]
```

You could put this code in a timeout to update this value every 3 seconds.
Please not that `rooms` prop and `messages` props are independent from each other, if you update one it will not impact/update the other, and vice versa.
