### ISSUE TITLE
Support for Hash links, targets other than _blank

### ISSUE THREAD

**Issue by bapaynter** [antoine92190/vue-advanced-chat#141]
I'm using this in a hash-based app, and I'd like the chat to support hash-based links using the linkify hashtag plugin. It would also be nice to have the option to choose the target for links, I want the links from chat to be opened in the same tab.

**Comment by antoine92190** [comment]
Will release the target option feature soon: https://github.com/antoine92190/vue-advanced-chat/commit/54a19bf44a7e9d2817ddb0d2a6b3fd62a0b684f7

Regarding hash links, I will think about it more, will keep in touch.

**Comment by antoine92190** [comment]
Target option feature released in https://github.com/antoine92190/vue-advanced-chat/releases/tag/0.7.9

**Comment by bapaynter** [comment]
Thank you! This also seems to work well with my app, doesn't cause a page reload when clicking links. With this behavior, hash-based links should be unnecessary.
