### ISSUE TITLE
setting room-info and textarea-action-handler event listeners does not cause intended behavior change

### ISSUE THREAD

**Issue by bapaynter** [antoine92190/vue-advanced-chat#142]
## Describe the bug

When @textarea-action-handler is set, custom-action-icon should be displayed but is not.
When @room-info is set, room header should be clickable but is not.

## Steps to reproduce

Add a @textarea-action-handler to chat-window component, expected icon does not appear in text area.

## Additional context

Code used is demo code modified for purpose, with relevant additions:

```
<chat-window
   ...
  @textarea-action-handler="sendLink"
>
  <template v-slot:custom-action-icon>
    <i  class="far fa-link" />
  </template>
</chat-window>

...

sendLink({ roomId }) {
  const message = {
    content: document.location.href,
    roomId: roomId
  }
  this.sendMessage(message)
}
```

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/c44f70c6aac819beb97f0f174e5dc1e12010e105
