### ISSUE TITLE
Add an event that was triggered when the user viewed a new message

### ISSUE THREAD

**Issue by ldar** [antoine92190/vue-advanced-chat#146]
Thanks for the great the Chat

## Is your feature request related to a problem? Please describe

I can not change the status that a user viewed the message

**Comment by antoine92190** [comment]
You just need to set `seen: true` in the `messages` prop: https://github.com/antoine92190/vue-advanced-chat#messages-prop

**Comment by ldar** [comment]
How do i know what the user has see?

**Comment by antoine92190** [comment]
If the message is loaded inside `messages` prop, then it's displayed on the screen and we can consider the user has seen it. This is how it's working for every messaging app
