### ISSUE TITLE
Typing message event fired after room loaded.

### ISSUE THREAD

**Issue by martynishin** [antoine92190/vue-advanced-chat#150]
## Describe the bug

typing-message fired immediately after room loaded. This behaviour triggers false event to 3-rd party like Pusher.

## Expected behavior

Trigger the typing-message event on typing and send message / press Enter.

**Comment by antoine92190** [comment]
Indeed, will fix that

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/5bd0dd9f576778d8dadcb8340b38632ecd8916db
New version will be released shortly
