### ISSUE TITLE
Show which user in room

### ISSUE THREAD

**Issue by vanthao03596** [antoine92190/vue-advanced-chat#151]
## Is your feature request related to a problem? Please describe

Recently user can't know who in room, who is online. Would be great if we have some ui to show list user in room.

## Describe the solution you'd like

Maybe a popup ?

**Comment by antoine92190** [comment]
I will not add this feature, as it's something you can implement on your side.
Plus, I don't want the chat component to become an app.
You can see a UI implementation here: https://vue-advanced-chat.herokuapp.com/
