### ISSUE TITLE
New Message divider (Blue line) is not showing

### ISSUE THREAD

**Issue by harryct229** [antoine92190/vue-advanced-chat#152]
Hi. As indicated, the new message divider will be shown after last seen message. But it does not work on my end.

Here is my integration:
<img width="1186" alt="Screen Shot 2021-03-17 at 2 10 43 PM" src="https://user-images.githubusercontent.com/1321049/111429186-38ba2980-872b-11eb-8b50-0bab2fa0cde9.png">

Can you help me with this? Thanks.

**Comment by antoine92190** [comment]
Indeed there is a bug. Will fix that soon

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/453bacc01409afb3bb463cfa78eb95827bb3696f

**Comment by harryct229** [comment]
@antoine92190 It works. Thank you.
