### ISSUE TITLE
Typing view slow performance

### ISSUE THREAD

**Issue by oasis345** [antoine92190/vue-advanced-chat#153]
first 
thank you for letting me use a nice App!.

anyway I found a problem.

A lot of messages make typing slow. ( eventlistener, v-model ...) 

So I fixed it temporarily. 

Feedback thank u

[room (2).zip](https://github.com/antoine92190/vue-advanced-chat/files/6209904/room.2.zip)

.diff

**Comment by antoine92190** [comment]
Can you create a pull request with your changes?

**Comment by yleclanche** [comment]
You can reproduce it on the demo page. You juste have to add a tons of message, and the typing is getting slower.
Instead of using a debounce, I think you could use `v-model.lazy`.
Or extract the textarea in another component to avoid rerenders.

**Comment by natsumework** [comment]
@antoine92190 
#185 improved the typing performance, but the typing speed is still slow on mobile devices.
After loading about 30 messages on my phone, I start to feel the typing speed slows down. After loading about 100 messages, the typing speed becomes unacceptable.

It can be observed in debug mode that the components under room.vue will be rerendered every time typing in textarea.
I think we really need to extract the textarea to another component to avoid rerenders.

https://user-images.githubusercontent.com/23622184/133209598-d121e2f2-072c-4e9c-b999-c7a5bf548a57.mp4

**Comment by antoine92190** [comment]
Actually, I found out that this code is causing many re-renders
```
<template v-for="(idx, name) in $scopedSlots" #[name]="data">
  <slot :name="name" v-bind="data" />
</template>
```
It's used everywhere in the app to pass slots across components, not sure yet how to solve it yet.

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/839359228416e1d9e51ce3d7e27c5904be5f1918
