### ISSUE TITLE
Upgrade to sass-loader 10

### ISSUE THREAD

**Issue by vanthao03596** [antoine92190/vue-advanced-chat#154]
## Is your feature request related to a problem? Please describe

I tried to install vue-advanced-chat with vuetify, but vuetify require sass-loader 10

## Describe the solution you'd like

Can we upgrade to sass-loader 10 ?

**Comment by antoine92190** [comment]
I'll check that soon and see if it's not breaking anything

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/0c9b8c3445af909d21f3232f66d3ee40c3f1213f

**Comment by vanthao03596** [comment]
Thanks you @antoine92190

**Comment by vanthao03596** [comment]
@antoine92190 in some latest commit i see sass-loader downgrade to version 8. Is it working good on version 10 ?

**Comment by antoine92190** [comment]
Indeed, I forgot that. I downgraded because it was breaking something, but I will upgrade it again and try to fix the issues

**Comment by antoine92190** [comment]
Fixed again in https://github.com/antoine92190/vue-advanced-chat/commit/6f9c497537dc772347ebe832e7c07420b6ffae1e
