### ISSUE TITLE
Room- / Message- menus does not close once clicked outside of menu-area

### ISSUE THREAD

**Issue by Nojahhh** [antoine92190/vue-advanced-chat#158]
When either room- or message-menu has been clicked and opened and the user clicks outside of that menu-area, that menu should automatically close. I don't really wanna call this a bug but I also didn't wanna call it a feature since it's pretty minor behvaiour-thing. Let me know if you think I should move this post.

##Steps to re-produce:
Click the three-dotted menu in the room-area or click the arrow down in the room-list-area and then click outside of that menu-area.

##Expected behaviour:
Menu should automatically close.

Love this utility btw, great work!!

Thank you,
Johan

**Comment by antoine92190** [comment]
I cannot reproduce. Can you reproduce on the demo? https://antoine92190.github.io/vue-advanced-chat/
If yes, which OS and which browser are you using?

**Comment by Nojahhh** [comment]
The issue is clearly on my side. I cannot reproduce it using the demo. I used your demo as a base for my project. Don't know how I can have disabled that feature though, have only done minor changes so far but I'm closing this as it's obvisouly isn't any bug. Thanks for such a quick response!

**Comment by antoine92190** [comment]
Ok, feel free to share your findings here if you can figure it out, it may be useful in case others are facing the same issue

**Comment by Nojahhh** [comment]
Think I might have figured it out. The problem seems to be that I'm running this as a own component in modal-panel which breaks the "v-click-outside" lib built-in. By running this in a modal the "v-click-outside" lib renders the whole modal as the same area as the menu and will only register as "clicked-outside" once clicked outside of the modal. Don't really know how to solve this yet since I'm using your lib from npm and your vac-logic is a bit too much for me to put my teeths in today... But ought i should share my findings :)
