### ISSUE TITLE
How to update and mantain chats from previous versions

### ISSUE THREAD

**Issue by climentjoan** [antoine92190/vue-advanced-chat#159]
Hi there!

I'm using an old version of your chat and I want to update it. I have everything working, but I can't load previous chats as they don't have the lastUpdated property.

Is there a way to update the previous conversations to be used in the new version?

Thank you so much

**Comment by antoine92190** [comment]
Are you using firebase? If yes you can a small script like below to set `lastUpdated` manually to current date:
```
roomsRef.get().then(rooms => {
  rooms.forEach(room => {
    if (!room.data().lastUpdated) {
      roomsRef.doc(room.id).update({ lastUpdated: new Date() });
  })
})
```

**Comment by climentjoan** [comment]
Thank you! Now I have everything working.
