### ISSUE TITLE
No caption in video 

### ISSUE THREAD

**Issue by hasanbasri1993** [antoine92190/vue-advanced-chat#160]
## Describe the bug

The caption in video is not showing 

## Steps to reproduce

I try to upload / send a video with caption

## Expected behavior

no caption in video 

## Screenshots

![image](https://user-images.githubusercontent.com/6375150/114692953-50dd9280-9d43-11eb-8c87-1b540f209748.png)
In ui

![image](https://user-images.githubusercontent.com/6375150/114693012-5f2bae80-9d43-11eb-8654-533275b3de3d.png)
in firebase there a content text

## Device (please complete the following information)

- OS: macOS bigsure
- Browser: Chrome 89
- Package version: 0.8.4

Thanks u

**Comment by antoine92190** [comment]
Indeed, will fix this ASAP

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/9e011ef48044afa9eef38dd1124c2ee9f80586f4
