### ISSUE TITLE
Auto Complete Template Text

### ISSUE THREAD

**Issue by hasanbasri1993** [antoine92190/vue-advanced-chat#161]
## Is your feature request related to a problem? Please describe

Now just inspired by other 

## Describe the solution you'd like

Auto complete template text is useful for over and over at same answer 
When type **/** will fetch data from database 

## Additional context

Example like this
![image](https://user-images.githubusercontent.com/6375150/114753414-a173e080-9d81-11eb-8d8e-2e2440919885.png)

**Comment by antoine92190** [comment]
Thanks for the suggestion, will work on it in the future

**Comment by ycarooliveira** [comment]
@antoine92190 any progress with this? if not I'll see what I can I do

**Comment by antoine92190** [comment]
No progress on it. Feel free to send a PR, you can use the same UI implementation as user tags

**Comment by ycarooliveira** [comment]
@antoine92190 I already did the script but there are more small changes of mine, should I send separated PRs or doesnt matter?

**Comment by antoine92190** [comment]
If all your changes are related to this issue, please make it a single PR.

Otherwise, please create another PR explaining your changes.
