### ISSUE TITLE
Swipe back when a room is open to get back to the room list

### ISSUE THREAD

**Issue by infobiac** [antoine92190/vue-advanced-chat#163]
## Is your feature request related to a problem? Please describe

The mobile interface looks great! I think a useful UX feature would be to allow a user to swipe back from a single room to the rooms list.

## Describe the solution you'd like

I'm happy to try implementing. It would be pretty simple - I think you could measure the drag motion using something like [this](https://stackoverflow.com/questions/2264072/detect-a-finger-swipe-through-javascript-on-the-iphone-and-android), have a threshold for how many pixels count as a "swipe", and then when a swipe is over that threshold, change the view..

## Describe alternatives you've considered

No real alternatives right now.

**Comment by antoine92190** [comment]
Sure, sounds like a good feature. Feel free to send a PR for that :)

**Comment by antoine92190** [comment]
Feature added in https://github.com/antoine92190/vue-advanced-chat/commits/master
