### ISSUE TITLE
Grouping rooms

### ISSUE THREAD

**Issue by ferretwithaberet** [antoine92190/vue-advanced-chat#167]
## Is your feature request related to a problem? Please describe

The ability to group rooms under the same category.

## Describe the solution you'd like

It should look something like
- Category 1
  - Room 1
  - Room 2
- Category 2
  - Room 1
  - Room 2
  
by default, with a slot to let the developer customize how the categories look.

## Describe alternatives you've considered

None.

## Additional context

A great example of this is Discord's folder system.
![Discord Folders](https://support.discord.com/hc/article_attachments/360033993751/6.gif)

**Comment by antoine92190** [comment]
I like the idea, will work on that in the future

**Comment by antoine92190** [comment]
This feature is a bit too specific for this library, I will close it for now.
Plus, this can probably be implemented on developer side using currents slots and playing with css.

**Comment by ferretwithaberet** [comment]
> This feature is a bit too specific for this library, I will close it for now.
> Plus, this can probably be implemented on developer side using currents slots and playing with css.

Not really, I tried to implement it using current slots and CSS workarounds, it is a mess.

**Comment by antoine92190** [comment]
Oh I see. Anyway it's a significant change that doesn't seem to be required by many people.
If you or anyone would like this feature added, you can send a PR and I will reopen the issue.
