### ISSUE TITLE
get file object

### ISSUE THREAD

**Issue by nicoaudy** [antoine92190/vue-advanced-chat#168]
Hi, first thing first i want to thank for creating this great package. I want to ask, how do i get the attachment file object? cause when i click upload attachment i just have some not valid blob object from payload. Thanks

**Comment by antoine92190** [comment]
Can you share some code?
To get attachment file object when sending a message, you should listen to the `send-message` event:

```
// template
<vue-advanced-chat
    ...
    (send-message)="sendMessage"
</vue-advanced-chat>

// method
async sendMessage({ content, roomId, file, replyMessage }) {
   console.log(file) // This is the file object
}
```

**Comment by nicoaudy** [comment]
Ah! got it. thanks man @antoine92190 🔥
