### ISSUE TITLE
Channel selected event

### ISSUE THREAD

**Issue by jcosta33** [antoine92190/vue-advanced-chat#169]
When the user select a channel an event should be triggered so the developer can implement a callback for that action.

**Comment by infobiac** [comment]
I believe you already can by using the fetch-messages event - when a room is first opened this fires with reset: true set in the options parameter.

**Comment by antoine92190** [comment]
@infobiac Yes you are right

**Comment by jcosta33** [comment]
Yes, worked perfectly, thanks!
