### ISSUE TITLE
A way to hide/change search bar completely

### ISSUE THREAD

**Issue by ferretwithaberet** [antoine92190/vue-advanced-chat#170]
## Is your feature request related to a problem? Please describe

I am trying to categorize my rooms using a hacky implementation, the problem is that the search bar completely borks my implementation, so I would love the ability to hide the search bar.

## Describe the solution you'd like

Adding a prop like `hide-search` so developers can hide the search bar if they want to.

## Describe alternatives you've considered

Adding a slot for the search bar.

## Additional context

Related to #167, but this can be implemented faster.

**Comment by ferretwithaberet** [comment]
Nevermind, I can just `display: none;`. But a slot/prop to hide/change it would still be nice rather than this fix.

**Comment by antoine92190** [comment]
Indeed, I will add a search bar slot.

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/deef2be41f092b748885b82478552f6d6ae22037
