### ISSUE TITLE
How can i use like index.html ?

### ISSUE THREAD

**Issue by diogo-palma** [antoine92190/vue-advanced-chat#171]
Sorry about this, but how can i use this vue advanced chat like a index.html? i see this lib have web component,

**Comment by antoine92190** [comment]
Indeed, I doesn't seem to work well when using it with index.html
I will try to find the reason why and fix it

**Comment by antoine92190** [comment]
You can use it with:
`<script src="https://cdn.jsdelivr.net/npm/vue-advanced-chat@0.8.7/dist/vue-advanced-chat.min.js"></script>`

However, you would need to pass props like this:
```
// HTML
<vue-advanced-chat :rooms="rooms">
</vue-advanced-chat>

// JS
document.querySelector('vue-advanced-chat').rooms = this.rooms
```
