### ISSUE TITLE
System message formatting

### ISSUE THREAD

**Issue by yleclanche** [antoine92190/vue-advanced-chat#172]
## Is your feature request related to a problem? Please describe

System messages are not formatted. For exemple, I want to send a message to all my channels with a link inside but the link is not wrapped in a `a` tag.

## Describe the solution you'd like

System messages should be formatted like any other messages.
An other approach would be to allow html in the system message with the `v-html` directive. These kind of messages are handled by the server side, so it should not be a security issue.

Thanks

**Comment by antoine92190** [comment]
Indeed I agree, I would go with the "System messages should be formatted like any other messages" approach.
Feel free to open a PR if you want this fixed quickly

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/fbb54326dd8d0010366162fc54c82b0098a67132
