### ISSUE TITLE
Get current room from component

### ISSUE THREAD

**Issue by ferretwithaberet** [antoine92190/vue-advanced-chat#174]
## Is your feature request related to a problem? Please describe
I am receiving a message from web sockets, the problem is that I do not know if the message belongs to the current room. So I want to do `message.roomId === currentRoom.id` to check that.

## Describe the solution you'd like
Emit an event when the current room changes.

## Describe alternatives you've considered
`v-model` would model on the `room` prop.

## Additional context
None

**Comment by antoine92190** [comment]
The `fetch-messages` event is triggered every time a room is loaded.
You can then get the `room` data from this event to know which room is currently selected.

**Comment by ferretwithaberet** [comment]
> The `fetch-messages` event is triggered every time a room is loaded.
> You can then get the `room` data from this event to know which room is currently selected.

Ah, true, I did not think about this. Thank you!
