### ISSUE TITLE
How to make it work on Nuxt SSR

### ISSUE THREAD

**Issue by kavin404** [antoine92190/vue-advanced-chat#175]
I have tried to use it as a plugin (https://github.com/antoine92190/vue-advanced-chat/issues/129) but still, I am unable to make it work. I am getting the following error.

```
vue.common.dev.js?4650:630 [Vue warn]: Unknown custom element: <chat-window> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Inbox> at components/messages/Inbox.vue
       <BTab>
         <BTabs>
           <Pages/loads/LoadId/index.vue> at pages/loads/_loadId/index.vue
             <Nuxt>
               <Layouts/default.vue> at layouts/default.vue
                 <Root>
```

**Comment by antoine92190** [comment]
Do you have the error when testing locally, or is it when your app is deployed?

**Comment by kavin404** [comment]
I tested only locally.

**Comment by kavin404** [comment]
The error occurs only when we refresh the page.  I guess it has something to do with SSR

**Comment by antoine92190** [comment]
There may be some additional config needed on Nuxt level to make it work.
I will try to create a new Nuxt project and reproduce.
In the meantime, if you find any useful information please let me know.

**Comment by TheMangoTrain** [comment]
SSR is the first thing I'd look at. An element being unavailable in early lifecycle, on server-side.

Look into explicitly setting the chat resources as being for client-only, that way they're ignored on server-side.

It could be as simple as naming the plugin file with ".client.js" and specifying it in nuxt.config.js:
```
export default {
  plugins: [
    '~/plugins/myChatPlugin.client.js', // only in client side
    '~/plugins/foo.server.js', // only in server side
    '~/plugins/foo.js' // both client & server
  ]
}
```

**Comment by kavin404** [comment]
@TheMangoTrain  Yes when registering the plugin I have set it to client only

**Comment by wobsoriano** [comment]
> @TheMangoTrain Yes when registering the plugin I have set it to client only

any update? Did you make it work?

**Comment by wobsoriano** [comment]
To actually make it work with SSR, you have to register it globally by adding it in `plugins` property and set [`mode` to `client`](https://nuxtjs.org/docs/2.x/directory-structure/plugins#object-syntax)  and also wrap the component with [client-only](https://nuxtjs.org/docs/2.x/features/nuxt-components#the-client-only-component) component from Nuxt

**Comment by odranoelBR** [comment]
Hi community! 
I'm using nuxt v2.15.7 and works locally import client only.
I hope it help \o/
``` 
<client-only>
     <chat-window
      :current-user-id="currentUserId"
      :show-add-room="false"
      :show-audio="false"
      :messages-loaded="true"
      :rooms-loaded="true"
      :rooms="rooms"
      :messages="messages"
    />
  </client-only>
```
```
<script>
  import 'vue-advanced-chat/dist/vue-advanced-chat.css'

  export default {
    layout: 'patient',
    components: {
      ChatWindow: () => import('vue-advanced-chat')
    },
```

**Comment by antoine92190** [comment]
It seems this issues has been solved. Is anyone still having issues with that?
Is there anything that can be done on plugin side to improve SSR compatibility?

**Comment by csumarcolee** [comment]
It doesnt work in NUXT. Unuseful plugin
