### ISSUE TITLE
How to use 'delete-message EVENT-API'?

### ISSUE THREAD

**Issue by abbb1399** [antoine92190/vue-advanced-chat#176]
Hi.
I'm wondering how to use 'delete-message' as below,
![image](https://user-images.githubusercontent.com/65113179/123913878-b4c63d80-d9b9-11eb-941a-8c4443ac2052.png)

By using delete-message, the only thing i can get is {roomId, message}. There's no element selector and i don't know where '.vac-message-deleted' comes from. 
 
I'm not using 'send-message-reaction' either. Your exlplnation is highly appreciated.

**Comment by antoine92190** [comment]
I’m not sure what you mean, but to show a message as deleted, you need the specific message data to have ‘deleted: true’

**Comment by abbb1399** [comment]
Thanks for your prompt reply :). it worked.
I read a documentation in npmjs.com. [https://www.npmjs.com/package/vue-advanced-chat#props-api](url)
There's no deleted props. It should be updated.  Thanks!!!!
