### ISSUE TITLE
Your demo site seems to have stopped showing the other side of the chats

### ISSUE THREAD

**Issue by Sublime1** [antoine92190/vue-advanced-chat#177]
Hi!
I'm a big admirer of this project, and I thought you should know an issue I noticed today on your demo site https://antoine92190.github.io/vue-advanced-chat/ This was working a few weeks ago I remember, so maybe you changed something?

## Steps to reproduce

Open 2 different browsers and go to https://antoine92190.github.io/vue-advanced-chat/ Login as Luke in one, and Leia in the other. Make sure that both Luke and Leia are in the same chat. You'll notice that neither can see the other's chats. 

## Expected behavior

This used work last time I looked a few weeks ago (as it's a fundamental feature of the library!)

**Comment by antoine92190** [comment]
It seems to work fine on my side...

<img width="1680" alt="Screenshot 2021-07-06 at 08 51 45" src="https://user-images.githubusercontent.com/16256207/124555518-77d5cd00-de37-11eb-998d-e29c25ec48e5.png">

**Comment by Sublime1** [comment]
Thanks! It seems to be working fine now. I feel a bit stupid. I appreciate you taking the time.
