### ISSUE TITLE
Is there a way to set the font size?

### ISSUE THREAD

**Issue by kavin404** [antoine92190/vue-advanced-chat#180]
I am looking for a way to increase the font size. I couldn't find anything related to this in the docs. Is there a way to do it?

**Comment by antoine92190** [comment]
Yes, you should be able to use CSS to customize the chat.
For example I changed the font in the demo project:
https://github.com/antoine92190/vue-advanced-chat/blob/master/demo/src/App.vue#L173-L176

**Comment by antoine92190** [comment]
You can change the font-size for all the text using the method above, otherwise you can point so a specific CSS class by inspecting the component and apply you font-size for each block/element

**Comment by kavin404** [comment]
Cool thanks a lot
