### ISSUE TITLE
No message icon-check re-render after setting distributed = true

### ISSUE THREAD

**Issue by prokhn** [antoine92190/vue-advanced-chat#183]
## Describe the bug

Messages that are already exist in chat-window messages array don't update their state correctly. After setting `distributed = true` for such messages nothing happen, and only typing something to input or waiting for 4-5+ seconds cause re-render.

## Steps to reproduce

1. Add message to `messages` array (`<chat-window ... :messages="messages" />`)
2. Wait for api response or something 
2. Mark message as distributed like `this.messages[messageIndex].distributed = true`
3. Nothing changes
4. Type anything to input or just wait for ~4-5 seconds
5. Message re-renders it's state

## Expected behavior

Message should be marked distributed much faster. 

## Screenshots

![](https://media.giphy.com/media/pEXH6vk8P1Xb9MCdv3/giphy.gif)

**Comment by antoine92190** [comment]
Does this work?
```
this.messages[messageIndex] = {...this.messages[messageIndex], distributed: true}
```

**Comment by antoine92190** [comment]
Closing this as the comment above should solve your issue.
Please reopen if it's not working.
