### ISSUE TITLE
Leveraging third-party platforms like Twilio or TalkJS;

### ISSUE THREAD

**Issue by TheMangoTrain** [antoine92190/vue-advanced-chat#184]
Hey, I'm building communication features into my app, and open to different ideas.

I just want to hear about someone leveraging this Vue plugin with third-party platforms like [Twilio](https://www.twilio.com/) or [TalkJS](https://talkjs.com). **Is this regularly done?**  What were the issues, etc. Some of these major services provide Vue chat plugins as well, but I'm undecided as to which front-end chat plugin is best or if I should create one from scratch (for basic needs).

Ultimately I'd have a proxy server between the front-end and back-end service. In this proxy server I'd pass the payloads back and forth according to the needs of this plugin and the needs of the third-party back-end service.

Am I on the right track?

**Comment by wobsoriano** [comment]
> Hey, I'm building communication features into my app, and open to different ideas.
> 
> I just want to hear about someone leveraging this Vue plugin with third-party platforms like [Twilio](https://www.twilio.com/) or [TalkJS](https://talkjs.com). **Is this regularly done?** What were the issues, etc. Some of these major services provide Vue chat plugins as well, but I'm undecided as to which front-end chat plugin is best or if I should create one from scratch (for basic needs).
> 
> Ultimately I'd have a proxy server between the front-end and back-end service. In this proxy server I'd pass the payloads back and forth according to the needs of this plugin and the needs of the third-party back-end service.
> 
> Am I on the right track?

Sounds good to me

**Comment by antoine92190** [comment]
This plugin is very flexible, so you should be able to use it with many third party platforms and any server.
