### ISSUE TITLE
Question: Use existing components in custom message

### ISSUE THREAD

**Issue by NielXu** [antoine92190/vue-advanced-chat#187]
Is it possible that we can use the existing components like emoji picker and dropdown when overriding the message slot?
```javascript
<template v-slot:message="{ message }">
  // <emoji-picker/> or something
</template>
```

**Comment by antoine92190** [comment]
It's not possible at the moment.
Closing this as it's a duplicate of https://github.com/antoine92190/vue-advanced-chat/issues/166
