### ISSUE TITLE
Question: Emit toggle-rooms-list in custom room-header

### ISSUE THREAD

**Issue by NielXu** [antoine92190/vue-advanced-chat#188]
How should we emit `toggle-rooms-list` when using the custom room-header, i.e. how should we go back to the rooms list from a room if we want to use the custom room-header slot?

**Comment by antoine92190** [comment]
Indeed, I'm not sure it's currently possible.
I will add the prop `toggle-rooms-list` shortly

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/6288f66addf00d4628402956eefcebcd7c37c6f0
You can use `rooms-list-opened` prop to hide or show rooms list.
