### ISSUE TITLE
Username not show up for reply message

### ISSUE THREAD

**Issue by NielXu** [antoine92190/vue-advanced-chat#189]
## Describe the bug

Username does not show up in the reply message.

## Steps to reproduce

Checkout the demo page
1. Go to the demo page
2. Reply a message
3. A message reply is sent with only the content without the username

## Expected behavior

The username should show up for the original message

## Screenshots

![Screen Shot 2021-07-26 at 2 58 38 PM](https://user-images.githubusercontent.com/21092425/127043683-26f2f4f2-d40d-4cdf-b037-d238264aec24.png)

## Device (please complete the following information)

- OS: MacOS
- Browser: Chrome Version 92.0.4515.107 (Official Build) (arm64)
- Package version: 0.8.6

**Comment by antoine92190** [comment]
There is no need to show username if the room has only two users. Username will appears if number of users are 3 or more.

**Comment by antoine92190** [comment]
Actually, just saw that whatsapp and telegram display username even if room only has 2 users.
Will think about adding this.

**Comment by ferretwithaberet** [comment]
> Actually, just saw that whatsapp and telegram display username even if room only has 2 users.
> Will think about adding this.

In my opinion it should be a prop like `showUsernames`, with options like `always`, `never` or `overtwo`(Yes, I could not come up with a better name, I am a dev I struggle with naming my variable ;-;) with `overtwo` being the default.

**Comment by odranoelBR** [comment]
Yea, same need here.
My cenario have an impersonate feature, meaning I need to show "Admin user impersonating LALALA" for example.

**Comment by antoine92190** [comment]
Actually, that was a bug in the demo.
To make it work, you need to pass `replyMessage.senderId`. `senderId` being the id of the user who sent the initial message.
