### ISSUE TITLE
Run with demo firebase

### ISSUE THREAD

**Issue by hcnhatnam** [antoine92190/vue-advanced-chat#19]
I can't run because I don't have a firebase.
Can you create an account demo firebase or **provider template to create a firebase database** to run the demo of you?
The other solution is don't use firebase to easy to run the demo.

**Comment by antoine92190** [comment]
I already added the steps to make the chat work with firestore: https://github.com/antoine92190/vue-advanced-chat#using-with-firestore

Creating a firestore database is easy and takes only 2 minutes, you can find many tutorials to help you achieve that.

-  Basically you need to create a firebase project here: https://firebase.google.com/?gclid=CjwKCAjwtNf6BRAwEiwAkt6UQt4udQTzgPYWcIJx6bMRF5hRztmCwsyaKLSLHUkLknG0rI0SHVVjBhoCpMUQAvD_BwE
- Then go to Firestore tab and follow the steps to setup the database.
- Then you can find your firebase config in the settings and follow my readme setup: https://github.com/antoine92190/vue-advanced-chat#using-with-firestore
