### ISSUE TITLE
is it possible to replace firbase with MySQL DB

### ISSUE THREAD

**Issue by HaniOurEdu** [antoine92190/vue-advanced-chat#191]
is it possible to replace firbase with MySQL DB #191

**Comment by antoine92190** [comment]
Yes. You can use whatever backend you want, this library is just a UI component.
The demo is build with firebase, but you don't need to use that.

**Comment by mbuk** [comment]
@HaniOurEdu Yeah we've done it here - you'll have to write the appropriate schema, and supply the data in the correct format but it does work.

**Comment by dsultanr** [comment]
@mbuk could you please share some of your code?

**Comment by vesper8** [comment]
@mbuk any chance you can provide a data sample for the correct format? Having a lot of trouble deciphering the expected format
