### ISSUE TITLE
How to properly use unreadCount, new (lastMessage) and seen (lastMessage)?

### ISSUE THREAD

**Issue by kavin404** [antoine92190/vue-advanced-chat#192]
Hi all, I am trying to put the unread count for each chat room. 
I have exactly two users per chatRoom. 

If I set the unreadCount(within the chatroom object) in the database it will show it to all the users including the user who sent the messages.

Since I am getting a list of all the chat rooms initially without the messages in it. I don't have a proper way to show the unread count without calling get messages for all the chat rooms one by one.

If I set the new flag to true in the database it will also highlight the message to both sender and user. 

Did I miss something or am I doing something wrong here? 
Is there a way to handle this within the package? A way to show the user that he/she has new messages per chat room (at least without the count)

**Comment by antoine92190** [comment]
You can either use `unreadCount` or `lastMessage`.
It seems like your issue is a limitation in your own code implementation or backend.
Which backend are you using?

**Comment by kavin404** [comment]
I am using aws appsync

**Comment by antoine92190** [comment]
No, if you set `new`, the last message will be displayed as `new` whatever user is receiving it.
You need to set `new` logic on your own, check which user you want to show this and implement the conditional param accordingly.

**Comment by antoine92190** [comment]
For example, the demo code is:
```
new: message.sender_id !== this.currentUserId && (!message.seen || !message.seen[this.currentUserId])
```

**Comment by kavin404** [comment]
Thanks. That makes sense.
