### ISSUE TITLE
room-list avatar slot

### ISSUE THREAD

**Issue by Alexx23** [antoine92190/vue-advanced-chat#194]
## Is your feature request related to a problem? Please describe

It would be helpful to have a template-slot precisely to change the avatar image of the room-list-item.

## Describe the solution you'd like

The solution that I have come up with is the creation of a template-slot precisely for the avatar, it sure does not take much time to implement it.

## Additional context

http://prntscr.com/1qhdquc
That's what I mean

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/ec08bdea746bfdda6b9d782c35e208d7cb01665e
