### ISSUE TITLE
Cannot compile latest build

### ISSUE THREAD

**Issue by silverbullet1** [antoine92190/vue-advanced-chat#195]
## Describe the bug
I am trying to use this module in my project but getting the following error :
Module parse failed: /Users/xx/Documents/CoPilot/node_modules/vue-advanced-chat/dist/vue-advanced-chat.common.js Unexpected token (15883:3)
You may need an appropriate loader to handle this file type.
| 			emoji,
| 			skinTone: currentSkinTone,
| 			...skinTonedUnicode && { unicode: skinTonedUnicode },
| 			...emojiSummary.name && { name: emojiSummary.name }
| 		});

## Steps to reproduce
The older versions(0.8.3) work fine however latest build breaks for me when I run the project.

**Comment by antoine92190** [comment]
Could you provide your package.json, node & npm version as well?

**Comment by silverbullet1** [comment]
Excuse the long set of dependencies(I am learning this)
npm -v = 6.14.14
node -v = 14.17.4

`{
  "name": "Test",
  "version": "0.5.0",
  "scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",
    "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
    "e2e": "node test/e2e/runner.js",
    "test": "npm run unit && npm run e2e",
    "deploy": "netlify deploy dist",
    "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs",
  },
  "dependencies": {
    "axios": "^0.15.3",
    "babel-preset-es2015": "^6.24.1",
    "babel-runtime": "^5.8.0",
    "chart.js": "2.3.0",
    "datatables.net": "^1.10.19",
    "datatables.net-bs": "^1.10.19",
    "faker": "^3.1.0",
    "firebase": "^8.10.0",
    "hideseek": "^0.7.0",
    "http-server": "^0.9.0",
    "jquery": "^2.2.2",
    "moment": "^2.12.0",
    "vue": "^2.6.14",
    "vue-advanced-chat": "^0.8.3",
    "vue-date-picker": "^1.0.2",
    "vue-loader": "^15.9.2",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.2.0",
    "vuex": "^2.0.0",
    "vuex-router-sync": "^4.1.2"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^10.0.2",
    "babel-loader": "^7.1.1",
    "babel-plugin-istanbul": "^3.1.2",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.2.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chai": "^3.5.0",
    "chalk": "^1.1.3",
    "chromedriver": "^2.27.2",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^3.1.4",
    "cross-spawn": "^5.0.1",
    "css-loader": "^0.26.1",
    "es6-promise": "^4.1.0",
    "eslint": "^3.14.1",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "eslint-plugin-vue": "^7.16.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.10.0",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "function-bind": "^1.1.0",
    "geckodriver": "^1.8.0",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "inject-loader": "^2.0.1",
    "json-loader": "^0.5.4",
    "karma": "^1.4.1",
    "karma-coverage": "^1.1.1",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sinon-chai": "1.2.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.26",
    "karma-webpack": "^2.0.2",
    "lolex": "^1.5.2",
    "mocha": "^3.2.0",
    "nightwatch": "^0.9.12",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.1.0",
    "phantomjs-prebuilt": "^2.1.14",
    "rimraf": "^2.6.0",
    "selenium-server": "^3.0.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.4",
    "sinon": "^1.17.7",
    "sinon-chai": "^2.8.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "vue-cli-plugin-vuetify": "^0.6.1",
    "vue-template-compiler": "^2.6.11",
    "url-loader": "^0.5.7",
    "vue-loader": "^15.9.8",
    "vue-style-loader": "^2.0.4",
    "webpack": "^2.2.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1",
    "@mdi/font": "^3.8.95",
    "@vue/cli-plugin-babel": "^3.9.2",
    "@vue/cli-plugin-eslint": "^3.9.2",
    "@vue/cli-plugin-unit-mocha": "^3.9.0",
    "@vue/cli-service": "^3.9.3",
    "@vue/eslint-config-prettier": "^5.0.0",
    "@vue/test-utils": "^1.0.0-beta.29",
    "node-sass": "^4.14.1",
    "sass-loader": "^7.3.1"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
`

**Comment by antoine92190** [comment]
Your environment is very specific, and the issue seems to come from this plugin: https://github.com/nolanlawson/emoji-picker-element
You should probably try to create a vue project from scratch with the emoji-picker-element plugin, and check which one of your dependency is breaking the build, then open an issue in the repo above.
I don't think there is much more I can do here.
