### ISSUE TITLE
Swiping left-to-right in single-room breaks the chat.

### ISSUE THREAD

**Issue by MackoHacko** [antoine92190/vue-advanced-chat#196]
## Describe the bug

When using single-room mode on mobile and swiping left-to-right (which would normally display the rooms list), the header and footer disappears.

## Steps to reproduce

1. Enter a chat in single-room mode on mobile (Chrome dev tools also works).
2. Swipe left-to-right
3. Header and footer are now gone.

## Expected behavior

Nothing should happen when swiping on mobile for single room mode.

## Screenshots

**Before swiping**

![before_swipe](https://user-images.githubusercontent.com/32510775/130931861-77abe505-6c78-4d82-ab38-52c7ece20f0d.png)

**After swiping**

![after_swipe](https://user-images.githubusercontent.com/32510775/130931915-1ca1075a-015a-43c8-b764-60c5f32b34af.png)

## Device

- OS: Tested in Chrome dev-tools and on ios / android
- Package version: 1.1.0

**Comment by antoine92190** [comment]
Indeed, will fix that soon

**Comment by antoine92190** [comment]
Fixed https://github.com/antoine92190/vue-advanced-chat/commit/c5a381a923a8ee87c7506729a83a9de1f7ea07ed
