### ISSUE TITLE
need a clue on how to inject this app into existing Java project

### ISSUE THREAD

**Issue by dsultanr** [antoine92190/vue-advanced-chat#199]
Very inspiring project! Thank you!

I'm trying to inject this Vue app into my existing JSP based project. I did already successfully build that Vue app. I just done npm build the demo folder and copied js/css to my Java project. It works fine as a standalone app. But my goal is to render the Vue app after click of the button on my existing page.

now the main.js contains this:
```

import Vue from 'vue'
import App from './App.vue'

Vue.config.productionTip = false

new Vue({
	render: h => h(App)
}).$mount('#chat_app')

```

my html is:

```
...
<div id="app"></div>
<input type="button" value="Chat"/>
<script src="assets/js/app.beb67329.js"></script>
<script src="assets/js/chunk-vendors.29eba92b.js"></script>

```
now the chat initializes automatically on the page load, how to make it render on a button click?

**Comment by antoine92190** [comment]
Is that not working? https://github.com/antoine92190/vue-advanced-chat#you-can-import-it-as-a-custom-component
You can then use `v-if` to show or hide `<chat-window/>` component

**Comment by dsultanr** [comment]
I hadn't a Vue at all in my old project. Perhaps I shouldn't start from a demo folder. Will give it a try. Thank you
