### ISSUE TITLE
Messages sent by user not appearing on the correct side

### ISSUE THREAD

**Issue by Steuls** [antoine92190/vue-advanced-chat#2]
Messages sent by the current user do not appear on the right or with the correct class styling. I am sending the currentUserId prop and well as having sender_id on the messages. 

Looking at the src code it looks like currentUserId is always a string whereas in the docs you write sender_id as a number so this comparison will fail? is sender_id supposed to also be a string or am I possibly missing something.

**Comment by Steuls** [comment]
After a quick test sender_id does need to be a string. Might want to update the docs to reflect this for any future users.

**Comment by antoine92190** [comment]
@Steuls You are right, thanks! Just updated the code, `currentUserId` can now be either a string or a number

**Comment by 0xMostafa** [comment]
Hi, @antoine92190,

I'm having this problem and I converted senderId to interger!

any ideas?
