### ISSUE TITLE
(BUG) New Messages blue line popping up even after seen flag is set

### ISSUE THREAD

**Issue by echrs** [antoine92190/vue-advanced-chat#20]
![image](https://user-images.githubusercontent.com/6318495/93015097-ee5ac300-f5b6-11ea-83fd-be66e6d43ac6.png)
This seems to occur even when the seen flag is set.
![image](https://user-images.githubusercontent.com/6318495/93015120-219d5200-f5b7-11ea-82e0-f20b523feb39.png)

In the repo I see that my message then should not be treated as new but it still is: 
https://github.com/antoine92190/vue-advanced-chat/blob/df56ddfc1e8908ce06c44f86b0da3755dfe4ae2b/src/ChatWindow/Message.vue#L300-L306

I am not sure if this.start or this.end has any role in this (I am not using those since I don't need them), but for now I've solved my problem with css 😄

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/6847c48fc4886a4824cb855ba113a75331c3a7aa

To hide the blue line, you can now use the prop: `showNewMessagesDivider: false`
