### ISSUE TITLE
edit-message event not emit if we clear all file

### ISSUE THREAD

**Issue by vanthao03596** [antoine92190/vue-advanced-chat#200]
## Describe the bug

edit-message event not emit if we clear all file

## Steps to reproduce

 1. Create message with one file
 2. Click edit message
 3. keep content and remove file
 4. edit-message not being emit

## Expected behavior

If we change file or remove file, i think it should emit event two

## Device (please complete the following information)

- OS: Ubuntu
- Browser: Chrome
- Package version: latest

## Additional context

i think we need to check editedMessage's old file with files instead
https://github.com/antoine92190/vue-advanced-chat/blob/219fe6bf2c89a69c368d0825d11dc9bbc5aa688f/src/lib/Room/Room.vue#L816

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/4876b8a46630941d8c545c8da7064369a16892fe
