### ISSUE TITLE
User tags not loading when edit message

### ISSUE THREAD

**Issue by shahil1607** [antoine92190/vue-advanced-chat#203]
Hi,

This happens when we try to edit the old message where we have already tagged any user to the text.

## Steps to reproduce

1. Add the message by tagging any member of the chat room.
2. Now select the option to edit the message from the dropdown action of the message.
3. Message will get load in the edit section but the user tag is showing like <usertag>user id</usertag> instead of name.

## Expected behavior

Tagged user name must be loaded instead of id.

Thanks

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/cb55106b951d72552bce7067494b69ddcf882341

**Comment by shahil1607** [comment]
Hi @antoine92190 

Thank you for the quick fix
