### ISSUE TITLE
vue advanced chat with PHP(laravel)

### ISSUE THREAD

**Issue by soumsena** [antoine92190/vue-advanced-chat#205]
Hi everyone. i have tried using vue advanced chat with php (laravel), but i cannot display the messages. Can I have an example of use with PHP. thanks in advance

**Comment by antoine92190** [comment]
There is no specific example with PHP, but implementation is the same as any other backend. Have you followed the correct usage and data structure in the readme?

**Comment by soumsena** [comment]
Hey how are you??? Thank you for your answer.  followed the correct usage and data structure in the readme and I even do it. but I wanted an example of use with PHP backend.
![Capture d’écran de 2021-09-08 01-02-25](https://user-images.githubusercontent.com/40273435/132429063-0183c365-166e-4208-bac4-72f251e4c5aa.png)

**Comment by antoine92190** [comment]
There is no example with PHP.
You can check another simplified repo to help you understand better how the chat should be implemented: https://github.com/antoine92190/vue-advanced-chat-sandbox

**Comment by TasneemWahdan** [comment]
@soumsena have you found any solution for this issue? I have the same in my Laravel project. 
Spinner is there and messages are not loaded
