### ISSUE TITLE
Clicking on image message should trigger preview action

### ISSUE THREAD

**Issue by abrari** [antoine92190/vue-advanced-chat#212]
Currently, clicking on file message will trigger the download action. But for image message, clicking on the image itself does nothing. To preview, the user have to hover the image and click the preview icon (small clickable area). For mobile users, it requires two taps: first to display the icons and second to trigger the action.

I think it is a better UX if clicking the image trigger the preview action, just like some popular messaging app (WhatsApp, Telegram for example). More friendly for mobile user as well.

**Comment by antoine92190** [comment]
I agree, added in https://github.com/antoine92190/vue-advanced-chat/commit/4c7a5f915981b769d9af353970e74be89441c40b
