### ISSUE TITLE
Text with more than two formatting on Nested formatting

### ISSUE THREAD

**Issue by ycarooliveira** [antoine92190/vue-advanced-chat#213]
## Is your feature request related to a problem? Please describe

As the title says, more than two formatting on the text 

## Steps to reproduce

Just type something like this:

`°*This text is _extremely_ important*°`

## Describe the solution you'd like

I tried myself to solve but it didn't work as I intended 

## Describe alternatives you've considered

This is my version of [format-string.js](https://pastebin.com/e2ZK7Eu1) file. Can someone help out why it didin't work?

**Comment by antoine92190** [comment]
@ycarooliveira I tried your code and it seems to work fine. What didn't work on your side?

**Comment by ycarooliveira** [comment]
It doesn't work when I try to nest a lot of 4 or 5 formatting at once. Should I send a PR?

**Comment by antoine92190** [comment]
Yes you can send a PR so we can all work on top of it to fix it.

**Comment by antoine92190** [comment]
@ycarooliveira I managed to fix it with a more scalable approach.
Could you test it locally and confirm it's working as expected?
https://github.com/antoine92190/vue-advanced-chat/commit/72041ac610119dfdc9559134f55128c5968291da
