### ISSUE TITLE
Images preview mechanic is not flexible

### ISSUE THREAD

**Issue by dsultanr** [antoine92190/vue-advanced-chat#214]
I ended up with my attachments are stored in a CouchDB. 

I have a JWT authentication in front of CouchDB and realised that vac-message-image preview mechanics [is not so flex](https://github.com/antoine92190/vue-advanced-chat/blob/18aff0262a80b5f14e7cceecc65250e7281c2c84/src/components/FormatMessage/FormatMessage.vue#L36
)

Requests to a background-images couldn't be customized nor manipulated

I need the `Authorization: Bearer <token>` header to be added to those requests

**Comment by antoine92190** [comment]
I could add a method like:

```
async getServerImage(url) {
	const token = 'TOKEN'
	const imageBlob = await fetch(url, {
		headers: {
			Authorization: `Bearer ${token}`
		}
	})
	const reader = new FileReader()
	return new Promise((resolve, reject) => {
		reader.onloadend = () => resolve(reader.result)
		reader.readAsDataURL(imageBlob)
	})
},
```

However, I have no easy way of testing this.
Could you test on you side by cloning the repo locally?
Otherwise, could you give me access to your repo?

**Comment by dsultanr** [comment]
I'm not sure if this could be useful for every usecase

How about adding an event listener for the image downloader where everyone could implement their own logic?

**Comment by antoine92190** [comment]
Sounds like a good idea, but I'm not 100% sure about the implementation you have in mind.
Could you send a PR so we could have something more concrete to base our discussions?

**Comment by dsultanr** [comment]
I'm not a Vue/JavaScript ninja as you unfortunatelly... I just realised that your solution is good enough. Let's try to implement it. I will test it locally and give you a feedback

**Comment by dsultanr** [comment]
Could you please show - how will code below will look like after changing to getServerImage method?

```
<div class="vac-image-link-container">
	<div
		class="vac-image-link"
		:style="{
			'background-image': `url('${message.value}')`,
			height: message.height
		}"
	/>
</div>
```

**Comment by antoine92190** [comment]
```
'background-image': getServerImage(message.value)
```

I'm not a fan of this method as it's not optimal and flexible.
Also, we would need to pass the bearer token as a prop, considering it's the same token for all images.

Another way could be:
```
getElementsByClassName('vac-image-link').style.backgroundImage = YOUR_LOGIC
```
If that works, we don't have anything to change on the component side.

**Comment by dsultanr** [comment]
`getElementsByClassName('vac-image-link').style.backgroundImage = YOUR_LOGIC`

If I will call this code after chat-window is loaded then very first requests for the image backround will anyway executed with the error?

following is the example on how I do the flex requests for the chat message attachments

```

    const axiosInstance = axios.create();

    axiosInstance.interceptors.response.use((response) => {
        return response
    },  function (error) {
            const originalRequest = error.config;
            if (error.response)
            {
                if (error.response.status === 401 && originalRequest.url.indexOf('ajax_get_jwt') !== -1 ) {
                    router.push('/login');
                    return Promise.reject(error);
                }

                if (error.response.status === 401 && !originalRequest._retry) {
                    originalRequest._retry = true;
                    return axiosInstance.get('ajax_get_jwt')
                        .then(res => {
                            if (res.status === 200) {
                                axiosInstance.defaults.headers.common['Authorization'] = 'Bearer ' + res.data.token;
                                return axiosInstance(originalRequest);
                            }
                        })
                }
            } else {
                console.log("axiosInstance error", error);
            }
            return Promise.reject(error);
    });


```

can we do something like this for the image previews also?

**Comment by antoine92190** [comment]
Closing this for now as the issue is stale. Please reopen when you can provide a reproducible example.

**Comment by sky-ermesombarros** [comment]
Hello guys, regarding this issue, I've found a solution that helped me https://stackoverflow.com/a/54026378.
Basically you can save your token as a cookie and then use it on your backend when you want it.

I've tested it and it worked, so we can continue to protect our files and use the architecture that this lib provide us.
