### ISSUE TITLE
Search Chat Message

### ISSUE THREAD

**Issue by julianodev** [antoine92190/vue-advanced-chat#215]
## Is your feature request related to a problem? Please describe

Hello friend, would you like to know if it is possible to search for a message within the chat?

It would be a very interesting feature, congratulations for the project.

**Comment by antoine92190** [comment]
I will probably not implement this feature, but you can use `menu-actions` prop to add a menu entry in the room header, like "Search Messages" and implement your own UI through a sliding panel for example.
