### ISSUE TITLE
audio bitrate variable

### ISSUE THREAD

**Issue by Alexx23** [antoine92190/vue-advanced-chat#217]
## Is your feature request related to a problem? Please describe

It would be helpful to have a variable that allows you to define the audio quality (bitrate).
I've seen the code and the current bitrate is 128kbps, this should be able to change to the programmer's taste, because with that bitrate, the audio can weigh too much.

## Describe the solution you'd like

The solution I had thought of is to add the variable 'bitrate-audio' inside <chat-container>.

**Comment by antoine92190** [comment]
Feel free to send a PR if you are in a rush.
I would rather name the prop `audio-bitrate` as a number.

**Comment by Alexx23** [comment]
Many thanks.
Yes, I think it's fine to be a number.

**Comment by antoine92190** [comment]
`audio-bit-rate` and `audio-sample-rate` props added in https://github.com/antoine92190/vue-advanced-chat/commit/6d8a0138cdf6ec8db0b086f165a13822573e9765
