### ISSUE TITLE
Open room by roomId message open ON mobile

### ISSUE THREAD

**Issue by NamioL** [antoine92190/vue-advanced-chat#219]
## Describe the bug
When I'm trying to open a room by roomId it works only in a case if in the chat exist more than 1 room
Actually, I am not 100 percent sure that it's a bug, maybe I am doing something wrong :( Anyway it would be grateful if we could discuss that

**Comment by NamioL** [comment]
`<template>
    <div class="window-container">
        <chat-window
                :auth-user="authUser"
                :current-user-id="this.currentUserId"
                :roomId="this.getRoom ? this.getRoom : this.dummyOrNothing"
                :rooms="this.rooms"
                :rooms-loaded="this.roomsLoaded"
                :loading-rooms="this.loadingRooms"
                :messages-loaded="this.messagesLoaded"
                :messages="this.messages"
                :show-audio="false"
                :show-files="false"
                :show-add-room="false"
                :vehicle="vehicle"
                @send-message="sendMessage"
                @fetch-more-rooms="fetchRooms"
                @fetch-messages="fetchMessages"
                @room-info="roomInfo"
        />
    </div>
</template>`

`<script>
    import ChatWindow from 'vue-advanced-chat'
    import 'vue-advanced-chat/dist/vue-advanced-chat.css'
    import axios from 'axios'

    export default {
        components: {
            ChatWindow
        },

        props:['height', 'authUser', 'vehicle'],

        data(){
            return {
                loadingRooms: true,
                roomsLoaded: false,
                messagesLoaded: false,
                messages: [],
                rooms: [],
                currentUserId: '',
                savedMessage: [],
                dummyRoomId: 'dummy'
            }
        },
        created(){
            this.currentUserId = this.authUser.id;
            this.messagesLoaded = false;
            if (!_.isEmpty(this.vehicle)) {
                this.createNewRoom();
            }
            this.fetchRooms();
        },

        mounted() {
            console.log(this.roomInfo())
        },
        computed: {
            getRoom(){
                if(typeof(this.vehicle)==='number') {
                    
                    // changing the index to show first in the list
                    this.rooms.forEach( elem => {
                        if( elem.roomId === this.vehicle ) {
                            elem.index = (new Date()).getTime();
                        }
                    });

                    return this.vehicle;
                }
                return null;
            },

            dummyOrNothing() {
                let result = null
                this.rooms.forEach( room => {
                    room.roomId == this.dummyRoomId 
                                    ? result = this.dummyRoomId 
                                    : '';
                })
                return result
            }
        },

        methods: {
            sendMessage(message) {
              this.saveMessage(message)
            },

            fetchMessages({ room, options }) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
            this.messagesLoaded = false
            this.messages = []
            if(room.roomId) {
                axios.get('/api/profile/messages/' + room.roomId)
                        .then(({data}) => {
                            this.messages = data;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                            this.messagesLoaded = true;
                        })
                        .catch(errors => {
                            this.messagesLoaded = false;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                console.error(errors)
                            })
            }
        },

            // fetchMessages(param){
            //     this.messagesLoaded = false;
            //     this.messages = [];
            //     param.room.unreadCount = 0;

            //     if(param.room.roomId){
            //         axios.get('/api/profile/messages/' + param.room.roomId)
            //             .then(({data}) => {
            //                 this.messages = data;
            //             })
            //             .catch(errors => {
            //                 this.messagesLoaded = false;
            //                 console.error(errors)
            //                 })
                    
            //         this.messagesLoaded = true;
            //     }
            // },


            fetchRooms(){
                this.roomsLoaded = false

                axios.get('/api/profile/conversations/' + this.authUser.id)
                    .then(({data}) => {
                        let rooms = [];
                        // search for dummy room and append it to the rest
                        for (let r in this.rooms) {
                            if (this.rooms[r].roomId == "dummy") {
                                rooms.push(this.rooms[r])
                                break;
                            }
                        }
                        // add the rest from the response data
                        for (let d in data) {
                            rooms.push(data[d]);
                        }
                        // update component rooms
                        this.rooms = rooms;
                        this.roomsLoaded = true;
                        this.loadingRooms = false;
                    })
                    .catch(errors => console.error(errors))
            },

             saveMessage(message){
                if (message.roomId == 'dummy') {
                    message.roomId = this.dummyRoomId;
                }
                axios.post('/api/profile/messages', {
                    message: message,
                    user_id: this.vehicle ? this.vehicle.customer_id : '',
                    vehicle_id: this.vehicle ? this.vehicle.id : ''
                }).then(({data}) => {
                    let is_filtered = data.is_filtered?data.is_filtered:false;
                    let msg = {
                        _id: this.messages.length ? this.messages[this.messages.length - 1]._id + 1 : 0,
                        content: data.content,
                        senderId: this.authUser.id,
                        username: this.authUser.name,
                        avatar: this.authUser.photo_url,
                        date: moment().format('MMMM D'),
                        timestamp: moment().format('H:m'),
                        system: false,
                        saved: true,
                        distributed: true,
                        seen: false,
                        disableActions: true,
                        disableReactions: true,
                    };

                    let systemMsg = {
                        _id: this.messages.length ? this.messages[this.messages.length - 1]._id + 1 : 0,
                        content: 'For safety reasons, never transfer money or communicate outside of the Vinty website',
                        senderId: this.authUser.id,
                        username: this.authUser.name,
                        avatar: this.authUser.photo_url,
                        date: moment().format('MMMM D'),
                        timestamp: moment().format('H:m'),
                        system: true,
                        saved: true,
                        distributed: true,
                        seen: true,
                        disableActions: true,
                        disableReactions: true,
                    };

                    if(is_filtered || data.content.length == 0)
                        this.messages.push(systemMsg);

                    if (data.content.length > 0) {
                        this.messages.push(msg);
                    }

                    if (message.roomId == 'dummy') {
                        this.dummyRoomId = data.room_id;
                    }

                }).catch((errors) => {
                    console.error(errors)
                });
            },

            roomInfo(room){
                window.open(room.vehicle_link, '_blank');
            },

            createNewRoom(){
                let rooms = [];
                let room = {
                    roomId: this.rooms.length ? this.rooms[this.rooms.length - 1].roomId : 'dummy',
                    roomName: !this.vehicle.customer_name?this.vehicle.title:this.vehicle.customer_name,
                    avatar: this.vehicle.image,
                    unreadCount: 0,
                    vehicle_id: this.vehicle ? this.vehicle.id : '',
                    index: (new Date()).getTime(),
                    /*lastMessage: {
                        content: 'dsa',
                        senderId: 1,
                        username: 'dsadas',
                        timestamp: moment().format('H:m'),
                        saved: true,
                        distributed: false,
                        seen: true,
                        new: true
                    },*/
                    users: [
                        {
                            _id: this.authUser.id,
                            username: this.authUser.name,
                            avatar: this.authUser.photo_url,
                        },
                        {
                            _id: this.vehicle.owner_id,
                            username: this.vehicle.owner_name,
                            avatar: this.vehicle.owner_image,
                        }
                    ],
                    vehicle_link: this.vehicle.link
                };
                rooms.push(room);
                this.rooms = rooms;
            }
        }
    }
</script>`

`<style scoped>
    .vac-card-window {
        height: calc(100vh - 216px) !important;
        max-height: 700px !important;
        min-height: 300px !important;
    }
</style>`

**Comment by antoine92190** [comment]
What is happening exactly when you try to use `roomId` with only one room? A gif or video might be helpful to understand your issue

**Comment by antoine92190** [comment]
Due to lack of activity, I'm closing this issue. Please reopen if you have more information to share about the issue.
