### ISSUE TITLE
Channel keeps loading when it has no messages

### ISSUE THREAD

**Issue by jcosta33** [antoine92190/vue-advanced-chat#220]
When the user opens the channel sometimes there are no messages in which case, to try to show the "no messages" label to the user, I have tried to pass in an empty array or a null value to the messages property. Unfortunately this only works sometimes but most of the time the loading doesn't disappear. 

## Steps to reproduce

Set up a few channels and upon the user selecting the channel get the messages from an API and map them to the chat component's "messages" property. If you have messages, it works normally. If none exist you can try passing null or an empty array but the loading will persist most of the time.

## Expected behavior

Loading should disappear and the label "no messages" should appear

**Comment by NamioL** [comment]
Can you drop your component code?

**Comment by jcosta33** [comment]
`
<template>
  <ChatWindow
    height="calc(100vh - 15rem)"
    :theme="config.theme ? config.theme : theme"
    :current-user-id="config.userId"
    :room-id="config.selectedRoom"
    :rooms="loadedRooms"
    :loading-rooms="loadingRooms"
    :messages="messages"
    :messages-loaded="messagesLoaded"
    :rooms-loaded="roomsLoaded"
    :menu-actions="menuActions"
    :room-message="roomMessage"
    @fetch-more-rooms="fetchMoreRooms"
    @fetch-messages="fetchMessages"
    @send-message="sendMessage"
    @edit-message="editMessage"
    @delete-message="deleteMessage"
    @open-file="openFile"
    @add-room="addRoom"
    @menu-action-handler="menuActionHandler"
    @message-action-handler="messageActionHandler"
    @send-message-reaction="sendMessageReaction"
    @typing-message="typingMessage"
    class="vue-advanced-chat"
  />
</template>
<script>
import ChatWindow from 'vue-advanced-chat';
import 'vue-advanced-chat/dist/vue-advanced-chat.css';
import { parseTimestamp, isSameDay } from '@/utils/dates';
import store from '@/store';

export default {
  name: 'Chat',
  components: {
    ChatWindow,
  },
  props: ['config'],
  computed: {
    loadedRooms() {
      return this.config.rooms && this.config.rooms.slice(0, this.roomsLoadedCount);
    },
    messages() {
      return this.config.messages && this.config.messages.length > 0
        ? this.config.messages
        : undefined;
    },
    currentUser() {
      return store.getters.currentUser;
    },
    messagesLoaded() {
      return !!this.config.messages;
    },
  },
  data() {
    return {
      drag: false,
      theme: 'light',
      roomsListeners: [() => false],
      listeners: [() => false],
      roomsPerPage: 15,
      startRooms: null,
      endRooms: null,
      roomsLoaded: true,
      loadingRooms: false,
      allUsers: [],
      loadingLastMessageByRoom: 0,
      roomsLoadedCount: this.config.roomsLoadedCount,
      selectedRoom: null,
      messagesPerPage: 20,
      roomMessage: '',
      startMessages: null,
      endMessages: null,
      typingMessageCache: '',
      disableForm: false,
      addNewRoom: null,
      addRoomUsername: '',
      inviteRoomId: null,
      invitedUsername: '',
      removeRoomId: null,
      removeUserId: '',
      removeUsers: [],
      menuActions: [],
    };
  },
  methods: {
    fetchMoreRooms() {
      console.log();
    },

    fetchMessages(prop) {
      const rid = prop.room.roomId;
      this.$emit('selectChannel', rid);
    },

    sendMessage(message) {
      this.$emit('sendMessage', message);
    },

    editMessage(message) {
      this.$emit('editMessage', message);
    },

    deleteMessage() {
      console.log();
    },

    openFile() {
      console.log();
    },

    addRoom() {
      console.log();
    },

    menuActionHandler() {
      console.log();
    },

    messageActionHandler() {
      console.log();
    },

    sendMessageReaction() {
      console.log();
    },

    typingMessage() {
      console.log();
    },
    resetRooms() {
      this.loadingRooms = true;
      this.loadingLastMessageByRoom = 0;
      this.roomsLoadedCount = 0;
      this.rooms = [];
      this.roomsLoaded = false;
      this.startRooms = null;
      this.endRooms = null;
      this.roomsListeners.forEach((listener) => listener());
      this.roomsListeners = [];
      this.resetMessages();
    },

    resetMessages() {
      this.messages = [];
      this.messagesLoaded = false;
      this.startMessages = null;
      this.endMessages = null;
      this.listeners.forEach((listener) => listener());
      this.listeners = [];
    },

    fetchRooms() {
      this.resetRooms();
    },

    formatLastMessage(message) {
      if (!message.timestamp) return false;
      const date = new Date(message.timestamp.seconds * 1000);
      const timestampFormat = isSameDay(date, new Date()) ? 'HH:mm' : 'DD/MM/YY';
      let timestamp = parseTimestamp(message.timestamp, timestampFormat);
      if (timestampFormat === 'HH:mm') timestamp = `Today, ${timestamp}`;
      let { content } = message;

      if (message.file) {
        content = `${message.file.name}.${message.file.extension || message.file.type}`;
      }

      return {
        ...message,
        ...{
          content,
          timestamp,
          date: message.timestamp.seconds,
          seen: message.sender_id === this.currentUser.id ? message.seen : null,
          new:
            this.currentUser.id &&
            message.sender_id !== this.currentUser.id &&
            (!message.seen || !message.seen[this.currentUser.id]),
        },
      };
    },
  },
};
</script>
`

It's a bit messy, I left a bunch of empty functions so I wouldn't have to go see the docs if I needed them. The messages and channels come from whichever component uses this and get passed via the "config" prop.

**Comment by NamioL** [comment]
sorry, your code to messy and unfortunately I don`t know how can I format it faster. and I don`t have time to format it myself. 

fetchMessages({ room, options }) {
  this.messagesLoaded = false

  // use timeout to imitate async server fetched data
  setTimeout(() => {
    this.messages = []
    this.messagesLoaded = true
  })
} 

this code is written down in documentation and if you follow the rules right it would work normal, without any issues, for it works perfectly fine

**Comment by antoine92190** [comment]
Which chat and vue version are you using?

**Comment by antoine92190** [comment]
I couldn't read your code as the formatting is terrible, but it seems like you're not correctly passing `:messages-loaded="true"` when messages are empty.

**Comment by jcosta33** [comment]
messagesLoaded, which is declared on the class as a computed variable, is assigned to ":messages-loaded". Changing this to a normal reactive variable has fixed the issue. My guess is computed variables don't work with that prop.

**Comment by seyfer** [comment]
@jcosta33  I had the same issue, just providing messages to the chat component did not help.

What I did is that I do set messages in the fetch-messages event.
`@fetch-messages="fetchMessages($event.detail[0])"`

there inside I also set messages-loaded to true
`:messages-loaded="messagesLoaded"`

in this way I simulate messages being loaded from somewhere, not just set, and it works well.
