### ISSUE TITLE
Message from self no longer appears with different color on the right of the chat

### ISSUE THREAD

**Issue by jcosta33** [antoine92190/vue-advanced-chat#221]
I updated to versio 1.2.0 from version 0.6.X (don't recall the specific version) and the messages from the user himself no longer appear highlighted. I have confirmed that I'm passing the correct user ID and that they match perfectly when the message is added.

Reverting to version 0.6.9 fixed the issue.

**Comment by antoine92190** [comment]
Which vue version are you using? You probably need to upgrade your vue version: https://github.com/antoine92190/vue-advanced-chat/releases/tag/0.8.9

**Comment by jcosta33** [comment]
I'm on 2.6.12. Thanks for the info!
