### ISSUE TITLE
MessageFile refs not working

### ISSUE THREAD

**Issue by pnhuyduy** [antoine92190/vue-advanced-chat#223]
## Describe the bug
My message has an image, but I cannot click on it. When I inspect the component, the `MessageFile` for that message didn't have class tag (see screenshot below)

## Expected behavior
Can be clicked and show cursor when hovering.

## Screenshots
![image](https://user-images.githubusercontent.com/46210597/135716888-b5693d77-ae2d-43d3-973c-c0543e65a8c8.png)

Should be like this from demo sandbox:
![image](https://user-images.githubusercontent.com/46210597/135717038-c644ffc4-66dc-45f4-857e-e1cbeba966ec.png)

## Device (please complete the following information)

- OS: Windows 10
- Browser: Brave Version 1.30.87 Chromium: 94.0.4606.71
- Package version: 1.2.0
- VueJS version: 2.6.11

**Comment by antoine92190** [comment]
Can you share the image you're having the issue with here?
It seems like the image format is not recognised.

**Comment by pnhuyduy** [comment]
The message data:
```js
{
  "_id": "61495c03f7fdb5581d708044",
  "senderId": "613b3e9fef2bea1dd942f772",
  "content": "eeee",
  "readBy": [],
  "replyMessage": null,
  "reactions": {},
  "createdAt": "2021-09-21T04:13:55.386Z",
  "timestamp": "11:13 AM",
  "username": "HD",
  "files": [
    {
      "type": "image/png",
      "url": "https://firebasestorage.googleapis.com/v0/b/vuexfire-a9c43.appspot.com/o/files%2F6R0MijpK6M4AIrwaaCY2%2F5RM2yf2TBCVmAUpaHbCD%2Fimage.png?alt=media&token=141dc7d8-1665-438b-871e-6e8566fabd2c",
      "extension": "png",
      "name": "proof",
      "size": 196763
    }
  ],
  "date": "21-9-2021"
}
```

I tried hard code message data in demo sandbox, it works fine.

**Comment by antoine92190** [comment]
So is it working for you in https://codesandbox.io/s/dreamy-mccarthy-f4x67?file=/src/App.vue?
It's working on my side.

**Comment by antoine92190** [comment]
Also, to be able to click on it, you need to add `@open-file="openFile"` event.
To be able to click on the entire image, you need to update chat version to 1.2.1

**Comment by pnhuyduy** [comment]
Thanks, turn out I need upgrade to version 1.2.1 and yeah it's working now 😄
