### ISSUE TITLE
File sending and uploading progress bar

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#231]
The user cannot know the upload progress of the current file. When sending the file, you can add a slot or parameter to display the upload progress

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/9286b97180d78ca5c42dd75a510fa8db4e8e785f

![ezgif-7-75f90f9dcc30](https://user-images.githubusercontent.com/16256207/139586653-53bcfcb4-2062-42b6-b944-84fa17b2f914.gif)

**Comment by antoine92190** [comment]
To use it, you need to pass `progress` property to the message file in `messages` prop.
See https://github.com/antoine92190/vue-advanced-chat/commit/422ca5ab973b74e71f74e6006cb72251cf31c756
