### ISSUE TITLE
Error when sending empty files array

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#235]
![image](https://user-images.githubusercontent.com/29892659/140615647-80483b05-942d-4047-8222-b7366cc0f4a6.png)
![image](https://user-images.githubusercontent.com/29892659/140615667-3fe4ce65-4a8b-466b-a187-fed265a29c17.png)

**Comment by antoine92190** [comment]
Should be fixed with https://github.com/antoine92190/vue-advanced-chat/commit/771c9cf0718cd08af530db53e9c9ade819b75d4e

**Comment by antoine92190** [comment]
@Alisonispig Please check version `1.3.1` and let me know if the issue is fixed

**Comment by Alisonispig** [comment]
is ok
