### ISSUE TITLE
Emoji panel scrollbar

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#239]
![image](https://user-images.githubusercontent.com/29892659/140950871-d036ed8c-2dd5-4a9e-b2b2-d7ebd47367e8.png)

About this panel, I wonder if you can make its x-axis and y-axis scroll bars disappear? The current state is really not very beautiful, and if the panel can be a little larger, you can make the scroll bar under the category disappear, which will be better

**Comment by antoine92190** [comment]
Indeed, will fix that

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/8d316f117d45a5da298ccef84f751f92bac3ed72
