### ISSUE TITLE
Error font and color of emoji

### ISSUE THREAD

**Issue by hcnhatnam** [antoine92190/vue-advanced-chat#24]
## Describe the bug

 Error font and color of emoji

![image](https://user-images.githubusercontent.com/37246426/94379093-651bc280-0158-11eb-9036-d5b417ef5a59.png)

**Comment by antoine92190** [comment]
Which operating system are you using? And which browser?

**Comment by hcnhatnam** [comment]
> Which operating system are you using? And which browser?

Ubuntu 20.04.1 LTS and Chrome.

**Comment by antoine92190** [comment]
Thanks, it seems like an issue with the vue-emoji-picker package.
Can you test their demo and let me know if you can reproduce the issue: https://codepen.io/DCzajkowski/pen/jzLzWp

**Comment by hcnhatnam** [comment]
> Thanks, it seems like an issue with the vue-emoji-picker package.
> Can you test their demo and let me know if you can reproduce the issue: https://codepen.io/DCzajkowski/pen/jzLzWp

it works fine

**Comment by antoine92190** [comment]
@hcnhatnam I could reproduce the issue on an Ubuntu online emulator. It will be difficult to debug on my side so I will not be able to fix this issue immediately. But feel free to send a pull request if you have the time

**Comment by hcnhatnam** [comment]
> @hcnhatnam I could reproduce the issue on an Ubuntu online emulator. It will be difficult to debug on my side so I will not be able to fix this issue immediately. But feel free to send a pull request if you have the time

Currently, I don't see any errors. It's difficult to explain
![image](https://user-images.githubusercontent.com/37246426/94710701-578d5500-0371-11eb-8ea9-998c07ffd42e.png)

**Comment by antoine92190** [comment]
I'm closing this for now, please let me know if you are still facing this issue.

**Comment by citrumsoft** [comment]
There's a very strange bug, I've installed a clean Vue 2 chat and the emoji call next to the message input field isn't working for me! Although, if I try to react to a message, the emoji window appears but only on the left side. I noticed that the demo generates a block without a TOP indicator but in my case it appears. Here is an example from the console: <div class="vac-emoji-picker" style="height: 315px; top: 315px; right: 622px; display: initial;"><emoji-picker></emoji-picker></div>

**Comment by citrumsoft** [comment]
> There's a very strange bug, I've installed a clean Vue 2 chat and the emoji call next to the message input field isn't working for me! Although, if I try to react to a message, the emoji window appears but only on the left side. I noticed that the demo generates a block without a TOP indicator but in my case it appears. Here is an example from the console:

and I find this in example `<template v-if="emojiOpened">
			<transition name="vac-slide-up" appear>
				<div
					class="vac-emoji-picker"
					:class="{ 'vac-picker-reaction': emojiReaction }"
					:style="{
						height: `${emojiPickerHeight}px`,
						top: positionTop ? emojiPickerHeight : `${emojiPickerTop}px`,
						right: emojiPickerRight,
						display: emojiPickerTop || !emojiReaction ? 'initial' : 'none'
					}"
				>
					<emoji-picker
						v-if="emojiOpened"
						ref="emojiPicker"
						:data-source="emojiDataSource"
					/>
				</div>
			</transition>
		</template>` why in demo don't have top param?
