### ISSUE TITLE
Room and Message is fixed on loading [NUXTJS]

### ISSUE THREAD

**Issue by dahromy** [antoine92190/vue-advanced-chat#240]
![image](https://user-images.githubusercontent.com/50836890/141140547-4fe17c58-bfb2-4f15-b470-5f0a0aee0fef.png)

I'm using NUXTJS

**Comment by antoine92190** [comment]
Could you share your component?

**Comment by antoine92190** [comment]
Are you correctly setting ` loading-rooms`, `rooms-loaded` and `messages-loaded` to `false`?

**Comment by AlirezaAriyanpour** [comment]
yes I have the same problem to using Nuxtjs

**Comment by antoine92190** [comment]
Have you checked closed nuxt issues in this project? https://github.com/antoine92190/vue-advanced-chat/issues?q=is%3Aissue+nuxt

**Comment by AlirezaAriyanpour** [comment]
i fixed it
thank you very much
