### ISSUE TITLE
vue-advanced-chat.herokuapp.com/chat is not loading

### ISSUE THREAD

**Issue by jonmalave** [antoine92190/vue-advanced-chat#241]
When logging into vue-advanced-chat.herokuapp.com on Mobile, or Desktop via Browser or PWA App we remain stuck on a loading screen. Chat interface never loads.

**Comment by antoine92190** [comment]
Could you share a video?
I have no problem on iOS device (tested on Chrome, Safari, PWA).

**Comment by jonmalave** [comment]
@antoine92190 see screenshot attached and console error. I'm getting a blank page on both iOS Safari, Chrome, and even on my laptop Chrome Browser.

![image](https://user-images.githubusercontent.com/3487527/141361997-7152bb0d-7b50-45c1-8bc7-29c87a2f4c4c.png)

**Comment by jonmalave** [comment]
@antoine92190 everything seems to be working now... not sure what fixed it. Did you do anything new on your end to address this?

**Comment by antoine92190** [comment]
No I didn't. The error comes from firestore, maybe that was an issue on their end.
