### ISSUE TITLE
Markdown characters prop

### ISSUE THREAD

**Issue by cartenzelra** [antoine92190/vue-advanced-chat#247]
## Describe the bug

There is an inappropriate format when using italic format such as this_is_variable, which will change to this<i>is</i>variable.
How to update the regex to check if there are no characters at the beginning of the text and at the end of the text?

## Expected behavior

Text example:
[✓] "const most_viewed_posts = 'Covid Life Updates'" 
[X] "const most<i>viewed</i>posts = 'Covid Life Updates'"

**Comment by antoine92190** [comment]
This is the expected behaviour, that's how markdown works.
- You can disable markdown entirely using `text-formatting` prop.
- I can add a prop `"markdown-characters": "{italic: '_', ...}"` to allow more flexibility

**Comment by antoine92190** [comment]
`text-formatting` prop was reworked: https://github.com/antoine92190/vue-advanced-chat/commit/e1acf799cbea34c0d29417dd445e26073f8082ef

**Comment by Mickaz89** [comment]
which prop need to use now instead text-formatting ?

**Comment by antoine92190** [comment]
@Mickaz89 I don't understand, `text-formatting` still exists and work as explained in the readme
