### ISSUE TITLE
Message failure indicator

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#248]
Can you put an icon in front of the message? And I can customize it, because if the message is not sent in case of network error, I want to more clearly identify the message sending failure, and I can click the icon to try again

**Comment by antoine92190** [comment]
Yes, will do

**Comment by antoine92190** [comment]
Feature added in https://github.com/antoine92190/vue-advanced-chat/commit/c81638e8db4f88cec23b80c712dc6639e383a574

**Comment by antoine92190** [comment]
You need to pass `failure: true` to `messages` prop, and can listen to icon click using `open-failure-message` event
