### ISSUE TITLE
Chat rooms with only two people can @

### ISSUE THREAD

**Issue by hakumen** [antoine92190/vue-advanced-chat#249]
When I wanted to @ other members, I found that there were only two people in the chat room and could not @.
I need to trigger a message alert via @, even if there are only two people in the room.
So whether can open two people can also @, thx

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/edbe8f21735a90ffb3ed30c58fdf174a2da19ccf
