### ISSUE TITLE
How to notify a user of new messages

### ISSUE THREAD

**Issue by georgeroamtech** [antoine92190/vue-advanced-chat#25]
@antoine92190 Thanks so much for this application, i was wondering how i would go about notifying a user they have a new message? am using firebase

**Comment by antoine92190** [comment]
You mean a push notification? On mobile or browser?

**Comment by georgeroamtech** [comment]
on web, i have a message icon and would like to display unread messages

**Comment by antoine92190** [comment]
Ok so this indicator would be detached from the chat component right?

**Comment by georgeroamtech** [comment]
Yes the chat is in a different page and the indicator is on the menu component, i want the user to see there is new messages so that they can navigate to the chat page

**Comment by antoine92190** [comment]
There would be 2 ways of doing that:

First is to keep a separate counter of unread messages for each user. Then increment the counter manually each time this user receives a new message, and reset the counter every time the user open the messages window.

Another solution, would be to fetch all the rooms of a user, and for each room see if the last message was seen or not.
If at least one message is unseen, then you show a dot to indicate unread messages. Something like this:

```
const rooms = await fb.collection('chatRooms')
	.where(`users.${currentUserId}`, '==', true)
	.get();

rooms.forEach(room => {
	fb.collection('chatRooms')
		.doc(room.id)
		.collection('messages')
		.orderBy('timestamp', 'desc')
		.limit(1)
		.onSnapshot(messages => {
			messages.forEach(message => {
                           if (message.sender_id !== currentUserId && !message.seen) {
                               // there is at least one unseen message
                           }
			});
		});
});
```

The first solution is more optimal, but you need to manually increment/reset the messages counter.

The second solution is less optimal, especially if a user has many rooms, but you don't have any counter implementation to manage.

**Comment by georgeroamtech** [comment]
Thank you, i think am more familiar with the second solution let me try that, thanks again

**Comment by hanatharesh2712** [comment]
@antoine92190 Is there any plan to provide unread message counter for each room? like as below: 
![image](https://user-images.githubusercontent.com/17156331/95297288-d0237280-0897-11eb-8d68-c4834a414b44.png)

**Comment by antoine92190** [comment]
@hanatharesh2712 Please open a new issue for that.

**Comment by aldoprogra** [comment]
Has anybody did such feature?I am interested a lot!

**Comment by hanatharesh2712** [comment]
@aldoprogra Pass the `unreadCount` property for rooms object. it will show the badge with unread message counter:

`unreadCount: 4,`

See data ref:
```
rooms="[
  {
    roomId: '1',
    roomName: 'Room 1',
    avatar: 'assets/imgs/people.png',
    unreadCount: 4,
    index: 3,
    lastMessage: {
      _id: 'xyz',
      content: 'Last message received',
      senderId: '1234',
      username: 'John Doe',
      timestamp: '10:20',
      saved: true,
      distributed: false,
      seen: false,
      new: true
    },
    users: [
      {
        _id: '1234',
        username: 'John Doe',
        avatar: 'assets/imgs/doe.png',
        status: {
          state: 'online',
          lastChanged: 'today, 14:30'
        }
      },
      {
        _id: '4321',
        username: 'John Snow',
        avatar: 'assets/imgs/snow.png',
        status: {
          state: 'offline',
          lastChanged: '14 July, 20:00'
        }
      }
    ],
    typingUsers: [ 4321 ]
  }
]"
```

**Comment by aldoprogra** [comment]
Thanks a lot for the message, how to make it red? 			
theme: {
				color: 'light',  // Define the theme mode (light/dark)
				backgroundCounterBadge: 'red',  // Customize the background color for the badge
				}, 
I do not know how to do it in the theme prop could you provide an example?
