### ISSUE TITLE
About system messages

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#250]
When sending system messages in a group, can the default sender name be removed? Because it's a little strange that system messages are sent by users

**Comment by antoine92190** [comment]
I don't see the send name on my side. Can you share a screenshot, and also share the system message data you are passing?

**Comment by Alisonispig** [comment]
Just like this, because my own actions generate system messages, the sender is myself, but both other users in the room and myself get a user name - the content of the system message. I mean, if it is a system message, this user name will not be spliced

![image](https://user-images.githubusercontent.com/29892659/144089442-d4aaf16a-060d-4218-8204-cdafb1251091.png)

**Comment by antoine92190** [comment]
You're talking about room lastMessage on the left panel?
In that case, why don't you add a condition, like:
```
 lastMessage: {
  content: 'Last message received',
  senderId: 1234,
  username: message.system ? '' : 'John Doe',
},
```

**Comment by Alisonispig** [comment]
Oh my god, It is a good idea

**Comment by antoine92190** [comment]
Closing this issue as the solution above seems to work, and it can be useful to keep the flexibility to add username for system messages in case it's needed for any use case.
