### ISSUE TITLE
Jumpy scroll with few messages

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#251]
When there are 16 or 17 messages on the screen, the scroll bar will jump to the top when switching sessions and coming back,like this

![动画](https://user-images.githubusercontent.com/29892659/143055947-a8b07fa2-9fd3-4d28-95cf-c8bf49933578.gif)

**Comment by antoine92190** [comment]
I cannot reproduce, which browser and OS are you using?

**Comment by Alisonispig** [comment]
im use edge 96. in windows

**Comment by antoine92190** [comment]
Did you update the `scroll-distance` prop?

**Comment by Alisonispig** [comment]
No, I not use this prop.  you can't emerge ?

**Comment by antoine92190** [comment]
I couldn't reproduce on Edge using Windows.
Could you check if you have the same issue with other browsers, like Google Chrome?

**Comment by Alisonispig** [comment]
OK, if you don't repeat it I don't think it's a very important issue I'll close it. By the way, I use windows
