### ISSUE TITLE
Console error saving code

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#252]
There is a strange error that does not affect the operation, but it is very uncomfortable. It appears after updating the latest version, not every time. If you don't repeat it at the first time, please pay attention

![屏幕截图 2021-11-24 230329](https://user-images.githubusercontent.com/29892659/143263469-a5f97f57-4054-4c51-84bb-a0f2f7ffb998.png)

**Comment by Alisonispig** [comment]
![image](https://user-images.githubusercontent.com/29892659/143263947-2c01ce2f-f22c-41f7-ac1b-fbae9fb77f58.png)

**Comment by antoine92190** [comment]
I can add a security check, but how do you reproduce this error exactly? On which browser?

**Comment by antoine92190** [comment]
Security check added in https://github.com/antoine92190/vue-advanced-chat/commit/46b50ff321357cc7f2f7f6d21f7d4ace831a6431
