### ISSUE TITLE
About upload progress

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#254]
I mentioned the problem of file upload progress before, and you also carried out relevant content.  #231  I tried it today. It's great, but I think it's not enough to only have the image file upload progress, because most scenes are uploading large non image files. Can you migrate the upload progress to all files? I think this should be great

**Comment by antoine92190** [comment]
Yes indeed, I will add this for other files.

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/68e3319030abbf5de8ae61e1da0e7d536672fe67
