### ISSUE TITLE
Large file upload is slow

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#255]
When I select a relatively large file, because you need to convert it into a file stream that can be displayed, the waiting time is always infinitely longer with the increase of file size. In this process, the user does not know what happened. So can you change the display order of the file area to be sent so that it can be displayed immediately after the user selects the file, Read the file stream after the presentation. If you are worried about the sending action of incomplete file reading, you can increase the reading prompt or disable the send button

like this
![动画2](https://user-images.githubusercontent.com/29892659/144092192-6d89c7a9-0d38-4e6e-a6aa-dd4a28789ed8.gif)

**Comment by antoine92190** [comment]
Indeed, I can probably improve this behaviour

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/593f04304878a4fc7b88b3c38900b194cde7f882
