### ISSUE TITLE
Type definition typo

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#257]
![image](https://user-images.githubusercontent.com/29892659/144242786-c60dc6eb-998e-4568-b3d7-1444d15f25e9.png)

**Comment by antoine92190** [comment]
Right, thanks! Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/a1313a5042eb4d88e4e93e1a691260c8a5d7867f
