### ISSUE TITLE
Add virtual scroll

### ISSUE THREAD

**Issue by antoine92190** [antoine92190/vue-advanced-chat#261]
Adding virtual scroll could fix messages performance issue https://github.com/antoine92190/vue-advanced-chat/issues/153

**Comment by antoine92190** [comment]
Closing this as https://github.com/antoine92190/vue-advanced-chat/issues/153 should be fixed, and adding virtual scroll would break many things. Will reconsider this when fully migrating to vue 3.

**Comment by catthecreator** [comment]
Is it possible to add a message slot override completely in order to implement message output via a third-party virtual scroll component?

**Comment by catthecreator** [comment]
Thanks. Are there at least approximate deadlines for the implementation of this functionality?

**Comment by antoine92190** [comment]
I cannot promise anything as it's a difficult implementation, but I'll try to do it by the end of the year

**Comment by catthecreator** [comment]
Thank you very much, I will be waiting. 
I also want to share my opinion that working without friezes provides a better ux than effects animations. imho)

**Comment by catthecreator** [comment]
Hi! Is there an approximate deadline for this functionality? :)

**Comment by catthecreator** [comment]
I'm still hoping for the release of this feature 0:)

**Comment by DMzmwh** [comment]
Hello, I noticed that this function has not yet been implemented. Are you still interested in adding this feature? Please reply, thank you!

**Comment by DMzmwh** [comment]
Hello, I noticed that this function has not yet been implemented. Are you still interested in adding this feature? Please reply, thank you!

**Comment by aerovulpe** [comment]
@DMzmwh hi, I think this might be very useful for performance in certain use-cases. Adding it to the backlog.
