### ISSUE TITLE
Redundant avatar and username messages in group chat

### ISSUE THREAD

**Issue by pnhuyduy** [antoine92190/vue-advanced-chat#262]
## Is your feature request related to a problem? Please describe
Avatar and Username are duplicated in group chat.
![image](https://user-images.githubusercontent.com/46210597/145031376-477ca9b7-aae9-4db8-9443-79a3be7285ce.png)

## Describe the solution you'd like
Only display avatar and username on first message
![image](https://user-images.githubusercontent.com/46210597/145032037-65bc894c-e35e-4f3a-a6a1-f9e816b95dd2.png)

## Describe alternatives you've considered
My solution is grouping messsages have same `senderId` into one container as a "block message".

## Additional context
Another suggestion, places avatar on top of message container
![image](https://user-images.githubusercontent.com/46210597/145032753-5dd29a8f-a0a8-4d37-a4ff-b26991f4bd7e.png)

**Comment by antoine92190** [comment]
You can do that by sending messages data with or without username. This is a specific UX behaviour that not everybody wants to have by default, hence we should keep the flexibility.

**Comment by pnhuyduy** [comment]
If I remove avatars, the messages are not align.
![image](https://user-images.githubusercontent.com/46210597/145544764-d7f461c5-3e9f-455c-9c68-3acd864d038f.png)

**Comment by antoine92190** [comment]
Mmm indeed, I can fix that

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/ad42fac909410890317574e5a3a1fb1f12b26aa6
