### ISSUE TITLE
Need ability to prevent the scrolling of new entries

### ISSUE THREAD

**Issue by psantora-amazon** [antoine92190/vue-advanced-chat#264]
Currently new entries that show up within the chat window auto-scrolls to the bottom of the message list. 

ASK 1: I need the ability scroll old messages without new entries causing the page to auto-scroll to the bottom of the message list
ASK 2: I need the auto-scrolling to re-enabled if I scroll back down to the bottom of the entry list

**Comment by antoine92190** [comment]
I can add a prop to have more control over the scrolling behaviour. Currently, it works as below:
- When sending/receiving a message => scroll down
- When scrolling up and sending a message => scroll down
- When scrolling up and receiving a message => show new message indicator (no scroll)

The new default prop could be:
```
autoScroll: {
  send: {
    new: true,
    newAfterScrollUp: true
  }
  receive: {
    new: true,
    newAfterScrollUp: false
  }
}
```

**Comment by antoine92190** [comment]
Prop added in https://github.com/antoine92190/vue-advanced-chat/commit/61b91f10396f9dfd64748611991e196912cac025
