### ISSUE TITLE
wow, about edit message

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#268]
if i use the edit message function. i can send this message . I've reproduced it in your demo

**Comment by antoine92190** [comment]
I don't understand this issue. Which message?

**Comment by Alisonispig** [comment]
My God, I seem to have misunderstood what you mean. Has the current editing message directly modified the original message? In that case, how can I follow your train of thought I think the message sent should have a certain effect. Whether the random modification is in line with the rigor of chat tools Or if I don't use this function, can I provide the same function as before Otherwise I can't upgrade the new version

**Comment by Alisonispig** [comment]
![Images_1640507382557](https://user-images.githubusercontent.com/29892659/147403336-e2b86e42-4d03-4143-ba3b-eb19f185681f.GIF)

**Comment by Alisonispig** [comment]
And I found that using this function can not trigger the message sending time

**Comment by antoine92190** [comment]
I still don't understand the issue.
If you send a message, then edit the message, the original message will be replaced by the new message and the pencil icon will be shown. It has always been working like that. Is it not what's happening there?
On your video, everything seems to work fine.

**Comment by Alisonispig** [comment]
OK, as you said, there are no events in the current edited message. What should I do if I change my data

**Comment by antoine92190** [comment]
Change which data? Please explain what you are trying to achieve with step by step explanation.

**Comment by Alisonispig** [comment]
https://youtu.be/C2pXOqFWWR8

like this video, Editing the message does not trigger the sending of the message. I don't know how to proceed

**Comment by antoine92190** [comment]
You need to use `@edit-message` event

**Comment by antoine92190** [comment]
Is your issue solved?

**Comment by Alisonispig** [comment]
yes . cloes it
