### ISSUE TITLE
 About group positioning messages

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#269]
Is there a way to scroll the scroll bar to the message location and blink when I'm searching for a message?

**Comment by antoine92190** [comment]
Each message has a specific ID, you can use `scrollToPosition()`. If you want to add specific style to a message (the selected one for example), you can also use it's ID to apply styles to it.

**Comment by Alisonispig** [comment]
I have understood and implemented what you said, but I still have some questions to discuss with you. I mainly want to implement a record search and jump function, but some messages that are not loaded will be retrieved in the search results, so I can't jump to this position In view of this situation, I think of several ways

1. I load some messages near this message. When I scroll up or down, I continue to load the unloaded messages Until it connects with the message known to be loaded

2. I give up the loaded messages directly Load from the clicked position


Personally, I prefer the second one, but either one needs your help Or do you have any better suggestions? Can we talk together

**Comment by antoine92190** [comment]
The solution 1 seems more scalable, you would need to couple this with a server query to check the indexed position of the message you are trying to search, and load the right number of paginated message to be able to see the searched message.
