### ISSUE TITLE
(FEATURE REQUEST) Internationalization of dates and message actions

### ISSUE THREAD

**Issue by ByteFight** [antoine92190/vue-advanced-chat#27]
Hello!

First of all I love your project, it makes developing a chat in Vue amazingly easy, especially your firebase example!

But since I'm developing an app in german, I need to translate some parts of the chat component. Is there currently any way to customize the date output and the message actions to fit for other languages? This feature would be awesome!

Kind regards,
Jonas

**Comment by antoine92190** [comment]
Yes, you can use the textMessages props: https://github.com/antoine92190/vue-advanced-chat#props-api
Let me know if that solves your problem

**Comment by antoine92190** [comment]
Actually, can you explain more about date output? Maybe some screenshots or examples.
Regarding message actions, you can use the messageActions prop to use your own text.

**Comment by ByteFight** [comment]
Thanks, I missed the option for messageActions, working fine now!

Regarding the dates: I mean the ones that intersect messages of different days and also the date output at the beginning of the chat (see the screenshot).

![Bildschirmfoto 2020-10-02 um 19 22 59](https://user-images.githubusercontent.com/20315976/94951571-d22ab180-04e4-11eb-8d4c-57317b30b671.png)

**Comment by ByteFight** [comment]
If you're using the JavaScript Date object you could provide an option for a language code or something like that. Maybe the output could be generated by [Date.toISOString()](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) which accepts language codes, timezones and other params for modifying the displayed output.

**Comment by antoine92190** [comment]
I'm not using any date library on purpose so you keep maximum control.
Dates are actually plain strings, which you assign using the messages prop: https://github.com/antoine92190/vue-advanced-chat#messages-prop
You can assign the `date` property, which is a string.

**Comment by ByteFight** [comment]
Ok, got it working like you described it! Thanks for your effort!
