### ISSUE TITLE
 Select message

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#270]
Sometimes I need to perform multiple message selection to realize the forwarding function But I have no way to implement it at present. Is there any plan to add this function

**Comment by antoine92190** [comment]
That would be a nice addition yes, will work on that in the future.

**Comment by antoine92190** [comment]
Feature added in https://github.com/antoine92190/vue-advanced-chat/commit/13589e6022c86dfbf58d030cd179a28dce3140b1

**Comment by mreguly** [comment]
@antoine92190 I am able to select and delete messages that are not mine (messages that I received from someone). I think that in the function messageSelectionActionHandler case deleteMessages needs to be check if message that I am deleting belongs to me? We don't use firebase so I don't know if firebase handles this logic you your case.
