### ISSUE TITLE
Always show usernames

### ISSUE THREAD

**Issue by dsultanr** [antoine92190/vue-advanced-chat#271]
Is it possible to detach the constant `2` at this line to a config variable? 

https://github.com/antoine92190/vue-advanced-chat/blob/c7d18a594237a80c1ad4c7d14faa4e4faad75c66/src/lib/Message/Message.vue#L57

I need to always show the usernames. Even if the users count in the room is less than 3

this is the example of how it looks like in the Slack

![image](https://user-images.githubusercontent.com/1683476/147497651-2a710011-8a36-4302-869a-4440c282be9a.png)

**Comment by antoine92190** [comment]
Indeed, will add that soon.

**Comment by antoine92190** [comment]
Prop added in https://github.com/antoine92190/vue-advanced-chat/commit/0bd2e30f9be77bb8f0119fa418ff2d516ea9ad4d
