### ISSUE TITLE
TypeError in vue-advanced-chat.common.js

### ISSUE THREAD

**Issue by AntipovIvan** [antoine92190/vue-advanced-chat#273]
## Describe the bug

Getting a "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')" in vue-advanced-chat.common.js in Vue 3 CLI project when importing as a custom component

## Screenshots

![what](https://user-images.githubusercontent.com/85480386/148862146-c57eb85e-7676-464d-bb74-dfbc5a1c088b.jpg)

## Device (please complete the following information)

- OS: Windows 10 (WSL2)
- Browser: Chrome

Please.
Will appreciate any help.

**Comment by antoine92190** [comment]
Is your projet using vue 3, if yes are you using the next branch?

**Comment by AntipovIvan** [comment]
oh my god, sorry, it seems I've used non-Vue 3 version.
reinstalled it and it seems it works, but it looks empty by default. Can't create rooms or anything. No error's though. I am not so much experienced, so I guess I need to make some adjustments in order to make it move.
![hm2](https://user-images.githubusercontent.com/85480386/149047923-664007ec-5b6f-48e6-89af-fb9c3634a514.jpg)

**Comment by antoine92190** [comment]
You need to read the doc to understand how the component works, how to add rooms, users, messages, etc.
