### ISSUE TITLE
Vue 3 - npm peer dependency problem

### ISSUE THREAD

**Issue by ggjulio** [antoine92190/vue-advanced-chat#276]
## Describe the bug

Can't install anymore this package in vue 3 app.
It was working fine from a couple of weeks.

## Steps to reproduce

```bash 
npm install --save https://github.com/antoine92190/vue-advanced-chat/tarball/next
```

**OR** if already installed:
1 - Delete `node_modules/` + `package-lock.json`
2 -  Do `npm install`

## Logs

```bash
☁  /app  npm install --save https://github.com/antoine92190/vue-advanced-chat/tarball/next
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: vue@3.2.28
npm ERR! node_modules/vue
npm ERR!   vue@"^3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.6.14" from vue-advanced-chat@1.4.5
npm ERR! node_modules/vue-advanced-chat
npm ERR!   vue-advanced-chat@"https://github.com/antoine92190/vue-advanced-chat/tarball/next" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/node/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-01-22T15_23_00_580Z-debug.log
```

## Device (please complete the following information)

- OS: ubuntu and macos (containerized app)
- Browser: firefox and chrome
- Package version: `1.4.5`

**Comment by antoine92190** [comment]
Which version of npm are you using?
You probably have npm 7 or npm 8.
I will try to fix that but in the meantime you can run `npm i --legacy-peer-deps`

**Comment by antoine92190** [comment]
I just tried `rm -rf node_modules && rm -rf package-lock.json && npm i` with `npm v8.1.2` and everything works fine.

**Comment by ggjulio** [comment]
We use npm `8.1.2`

As a workaround, we forked your repo to update the [package.json](https://github.com/antoine92190/vue-advanced-chat/blame/44ac7224782daabd29119fbca81f41280fad3165/package.json#L76) deps.

https://github.com/Working-From-Home/vue-advanced-chat/commit/420d10384890bfe2c24c6f2007448dcc2074af42

It seem to work fine for us.

**Comment by antoine92190** [comment]
Just fixed the issue https://github.com/antoine92190/vue-advanced-chat/commit/7d3eb42b7f0d42de43967851b0c051ae6292ed8e
Can you try and see if it works?

**Comment by ggjulio** [comment]
It seem to work fine
