### ISSUE TITLE
Open user tag is not working with image message

### ISSUE THREAD

**Issue by cartenzelra** [antoine92190/vue-advanced-chat#280]
## Describe the bug

If you click @ tag at the image message, `this.$emit('open-user-tag', user)` is not emitted. If you click at the text message, it's working.

## Steps to reproduce

 1. Send image with tag caption
 2. Click on tagged user
 3. Open user tag is not emitted

## Expected behavior

Open user tag is emitted.

## Screenshots
[Screenshot](https://i.ibb.co/qd8PjzH/Screen-Shot-2022-01-31-at-11-52-59.png)

**Comment by cartenzelra** [comment]
I fixed it by adding open-user-tag event on message files component at RoomMessage.vue.

```
<message-files
  v-else-if="!isAudio || message.files.length > 1"
  :current-user-id="currentUserId"
  :message="message"
  :room-users="roomUsers"
  :text-formatting="textFormatting"
  :link-options="linkOptions"
  :message-selection-enabled="messageSelectionEnabled"
  @open-file="openFile"
  @open-user-tag="openUserTag"
>
```

**Comment by antoine92190** [comment]
Thanks, will fix that shortly

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/3804047ed9c15284bde20bfb1c98ee847e8d40ce
