### ISSUE TITLE
Initial render fails

### ISSUE THREAD

**Issue by mzhurincnb** [antoine92190/vue-advanced-chat#281]
## Describe the bug

The initial render is not done, immediately after installation.

I'm attaching a screenshot, what could it be?

## Screenshots
![image](https://user-images.githubusercontent.com/99278343/153035340-9275654f-c37f-4e66-8545-2e4e46f44f1a.png)

## Device (please complete the following information)

- OS: [Windows 10]
- Browser: [e.g. Chrome last]

## Additional context

my dependencies:
"dependencies": {
    "axios": "^0.24.0",
    "core-js": "3.6.5",
    "flipbook-vue": "^0.10.4",
    "img-vuer": "^0.19.3",
    "lodash": "^4.17.21",
    "moment": "2.27.0",
    "swiper": "^5.4.2",
    "v-calendar": "^2.3.4",
    "v-img-swipe": "^0.2.2",
    "v-smooth-scroll": "^2.0.0-beta.1",
    "vee-validate": "^3.4.14",
    "vue": "2.6.11",
    "vue-advanced-chat": "^1.5.2",
    "vue-appear": "^0.1.3",
    "vue-awesome-swiper": "^4.1.1",
    "vue-fragment": "^1.5.2",
    "vue-meta": "^2.4.0",
    "vue-phone-mask-input": "^1.1.11",
    "vue-router": "3.3.4",
    "vue-the-mask": "^0.11.1",
    "vue-toastification": "^1.7.14",
    "vuetify": "^2.4.0",
    "vuex": "3.5.1",
    "vuex-persistedstate": "^4.1.0"
  },
  "devDependencies": {
    "@types/swiper": "^5.4.3",
    "@typescript-eslint/eslint-plugin": "2.34.0",
    "@typescript-eslint/parser": "2.34.0",
    "@vue/cli-plugin-babel": "4.4.6",
    "@vue/cli-plugin-eslint": "4.4.6",
    "@vue/cli-plugin-pwa": "4.4.6",
    "@vue/cli-plugin-router": "4.4.6",
    "@vue/cli-plugin-typescript": "4.4.6",
    "@vue/cli-plugin-vuex": "4.4.6",
    "@vue/cli-service": "4.4.6",
    "@vue/eslint-config-prettier": "6.0.0",
    "@vue/eslint-config-typescript": "5.0.2",
    "@vue/preload-webpack-plugin": "1.1.1",
    "eslint": "6.8.0",
    "eslint-plugin-prettier": "3.1.4",
    "eslint-plugin-vue": "6.2.2",
    "moment-locales-webpack-plugin": "1.2.0",
    "node-sass": "4.14.1",
    "prettier": "2.0.5",
    "sass": "~1.32.0",
    "sass-loader": "^10.0.0",
    "typescript": "3.9.6",
    "vue-class-component": "7.2.3",
    "vue-cli-plugin-vuetify": "~2.4.5",
    "vue-property-decorator": "8.5.0",
    "vue-template-compiler": "2.6.11",
    "vuetify-loader": "^1.7.0"
  }

**Comment by mzhurincnb** [comment]
ok, but in an empty project with "vue": "^2.6.11", everything works correctly, I checked.
Now I updated the main project and everything worked.

Any idea why in the empty project with "vue": "^2.6.11" everything worked fine, but not in the main project?

this is a question out of curiosity.

Chat is great! Thanks guys!

empty project dependencies:
"dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-advanced-chat": "^1.5.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  },

**Comment by antoine92190** [comment]
`"vue": "2.6.11"` !== `"vue": "^2.6.11"`
You have `^` in your main project, which install the latest minor version silently, which is `2.6.14`

**Comment by mzhurincnb** [comment]
ok, thanks for the help!
