### ISSUE TITLE
Emojis not displayed on Windows 7

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#282]
When I use this message panel on win7, many boxes appear, which may not be supported by the system So I was wondering if you could be [emoji]( http://onesignal.github.io/emoji-picker/demo/) This address uses the same unified expression content and no longer depends on the system capability

**Comment by antoine92190** [comment]
Could you send a screenshot of the issue? Which browser are you using?

**Comment by Alisonispig** [comment]
![image](https://user-images.githubusercontent.com/29892659/154611703-e96d76fa-edee-4815-a9fc-36eb03a00c4f.png)

use edge for win7 

and use issues demo 

![image](https://user-images.githubusercontent.com/29892659/154611800-4dfaa59e-237e-424f-ac67-73197cc43e43.png)

**Comment by antoine92190** [comment]
Can you confirm you have the same issue directly with the plugin I use? https://nolanlawson.github.io/emoji-picker-element/

**Comment by Alisonispig** [comment]
![image](https://user-images.githubusercontent.com/29892659/154843980-46da9e99-f9ea-4269-b0e7-b90a8d446bc7.png)

Yes, that's the effect


![image](https://user-images.githubusercontent.com/29892659/154844060-e1005c3e-d714-4b4e-843d-98f59c563479.png)


http://onesignal.github.io/emoji-picker/demo/

This is the one I recommend, but I don't know how much to transform

**Comment by antoine92190** [comment]
I see. Could you open an issue on https://github.com/nolanlawson/emoji-picker-element and link it to this issue?
It looks like it could be managed on the emoji plugin, and I would rather not change the emoji plugin unless absolutely necessary.

**Comment by Alisonispig** [comment]
Hello, the author answered this question. Do you have a new plan

**Comment by antoine92190** [comment]
Why do you need to support Windows 7 if it was officially shut off?
I don't see a good reason to make this plugin compatible with any unmaintained browser.

**Comment by Alisonispig** [comment]
Sorry, this is true from the perspective of technology development. I don't want to do this, but my boss needs to realize this function Thank you for your support. I will look for other solutions

**Comment by antoine92190** [comment]
I could add a slot so you can replace the emoji picker with the one you want. Would that help?

**Comment by Alisonispig** [comment]
This is a very good idea, and I look forward to you doing so so that I can re implement this part

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/8b076386e9c777a71adcc5ee62b19eab5efcbbde
