### ISSUE TITLE
Scrolling an image in full screen

### ISSUE THREAD

**Issue by mzhurincnb** [antoine92190/vue-advanced-chat#283]
when the image is opened in full view, it can be scrolled if the content of the page is larger than the height of the screen
![state1](https://user-images.githubusercontent.com/99278343/153856818-4a1a4cd4-81cc-4bf5-adc2-fa42e5883fc0.PNG)
![after scroll](https://user-images.githubusercontent.com/99278343/153856826-6026c65a-1375-4312-8562-d1b0c5f6f80f.PNG)

perhaps better to use? What do you think?
.vac-media-preview {
    position: fixed; //insted absolute
}

**Comment by antoine92190** [comment]
Indeed, thanks for pointing it out. Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/24ec3b0c34d52437723b87b430de467b8de916fd
