### ISSUE TITLE
Nuxt - overriding emoji, add file and send message icons doesnt work when building the code to production.

### ISSUE THREAD

**Issue by StefanGhiban** [antoine92190/vue-advanced-chat#284]
## Describe the bug

I have used the provided slots in order to override the send icon, emoji-picker-icon and paperclip-icon. In local development this works, but when deploying to firebase, the icons go back to their defaults.

## Expected behavior

I have expected the icons to work correctly even in production. Are there any more tweaks that are needed in your opinion?

## Additional context

I am using nuxt and I am just importing the component and the related css into a page in nuxt.

**Comment by antoine92190** [comment]
Are you using the correct syntax when using slots? For example
```
<template #room-header="{ room }">
  {{ room.roomName }}
</template>
```

**Comment by StefanGhiban** [comment]
![image](https://user-images.githubusercontent.com/47953165/154856278-b7a8fdc5-f287-4ae0-9ce5-6a53276dee9a.png)
Yes, I have followed the structure in the docs like in the image above.

**Comment by antoine92190** [comment]
There is an issue with footer slots which was introduced in the latest version of this plugin. Maybe locally you have not installed the latest version, but Firebase is using the latest version. I will release the fix and you can try again
https://github.com/antoine92190/vue-advanced-chat/issues/288

**Comment by antoine92190** [comment]
Version `1.5.3` is released. Could you try again and let me know if it works?

**Comment by StefanGhiban** [comment]
It worked after bumping the version to 1.5.3. Thank you!
