### ISSUE TITLE
@ usertag displays @unknown if user removed from room

### ISSUE THREAD

**Issue by Sublime1** [antoine92190/vue-advanced-chat#286]
## Describe the bug
I'm not sure if this is a bug because I'm not sure what the right behaviour would be. If a user is removed from a room, any messages where they were usertagged now say "@unknown"

## Steps to reproduce

1. add a user "Jim" to a chat
2. send that user a message using usertag @Jim - all looks good
3. remove Jim from the chat - the previous message now say "@unknown"

## Expected behavior

Ideally the message would still say @Jim 

## Screenshots

![image](https://user-images.githubusercontent.com/10615800/154713939-df85643c-5e88-4cdc-ac28-edccfd328670.png)

## Device (please complete the following information)

- OS:  Windows 10
- Browser: Firefox 97
- Package version:  reproduced here https://antoine92190.github.io/vue-advanced-chat/

**Comment by antoine92190** [comment]
The demo doesn't perfectly handle users and rooms creation/edition, so that's just how it works.
But you can definitely improve that logic on your side.
