### ISSUE TITLE
After I import it with vue, the page shows undefined

### ISSUE THREAD

**Issue by PercyT** [antoine92190/vue-advanced-chat#287]
After I import it with vue, the page shows undefined
[https://postimg.cc/FdDkzY85](url:https://postimg.cc/FdDkzY85)

**Comment by antoine92190** [comment]
You need to use vue `2.6.14` or above.
https://github.com/antoine92190/vue-advanced-chat#installation

**Comment by PercyT** [comment]
> You need to use vue `2.6.14` or above. https://github.com/antoine92190/vue-advanced-chat#installation
The vue version used in my package.json file is ^2.6.14

**Comment by clementmas** [comment]
I have the same issue with vue 2.6.14 on a fresh install as well as vue 3 with the next branch

**Comment by antoine92190** [comment]
This might be related to this issue: https://github.com/antoine92190/vue-advanced-chat/issues/204

**Comment by clementmas** [comment]
Yes, that's the same "error" message.

I managed to fix it on my end but I tweaked so many things I'm not sure what the solution is.
I downgraded Laravel Mix to v4 (so using a different webpack and babel version), used npm install of yarn, and re-installed Laravel Nova's assets which might have been interfering.
Very strange issue.

**Comment by antoine92190** [comment]
@PercyT Did you manage to solve the issue on your side?

**Comment by bokamix** [comment]
I have that same issue. Screen:
<img width="323" alt="Zrzut ekranu 2022-03-24 o 08 21 10" src="https://user-images.githubusercontent.com/29372724/159863407-34cf0f4c-7e8e-4ac3-b793-16f3ef738211.png">

**Comment by bokamix** [comment]
This fix my issue https://github.com/antoine92190/vue-advanced-chat/issues/204#issuecomment-917671849

**Comment by antoine92190** [comment]
Seems like everyone managed to fix the issue, closing this for now.
