### ISSUE TITLE
send-icon slot dont work

### ISSUE THREAD

**Issue by mzhurincnb** [antoine92190/vue-advanced-chat#288]
<ChatWindow>
<template #send-icon>
   <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
         ......
  </svg>
</template>
</ChatWindow>

it works:

<template #room-header="{ room, userStatus }">
  {{ room.roomName }} - {{ userStatus }}
</template>

what could be wrong?

**Comment by antoine92190** [comment]
What do you mean? `room-header` slot works but `send-icon` slot doesn't work?
Are you using Nuxt?

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/d1860b2237f69e615d6555997a4863f5eb58df6e

**Comment by mzhurincnb** [comment]
> 

yes, but i am not using Nuxt
