### ISSUE TITLE
"The $scopedSlots is deprecated" Error

### ISSUE THREAD

**Issue by schosdas** [antoine92190/vue-advanced-chat#295]
Hello.
I would like to copy and use the demo code for this project to my project (Vue 3).
However, v-for of all components will produce the same error.

RoomsList.vue (The same goes for other components.)
`					<template v-for="(i, name) in $scopedSlots" #[name]="data">
						<slot :name="name" v-bind="data" />
					</template>
`
"The $scopedSlots is deprecated" Error.

![스크린샷 2022-03-28 오후 1 01 13](https://user-images.githubusercontent.com/63434070/160324526-6eeae608-ffa5-4b4c-8d80-d1c0f9112fb8.png)

May I know the cause of this problem?
Thank you.

**Comment by antoine92190** [comment]
For vue 3, you need to use the `next` branch.

**Comment by antoine92190** [comment]
Did using next branch solved your issue?
