### ISSUE TITLE
Vue 3 - RoomMessageReply crashing session recordings

### ISSUE THREAD

**Issue by bapaynter** [antoine92190/vue-advanced-chat#296]
## Describe the bug

We're experiencing an issue where an uncaught error in vue-advanced-chat is crashing our session recording software.

## Steps to reproduce

Using the LogRocket SDK, initialize a session recording and navigate between different routes of a Vue app. In the console, you will see an error:
```
index.7949988e.js:22 LogRocket TypeError: Cannot read properties of null (reading 'files')
    at Proxy.firstFile (index.7949988e.js:14:409508)
    at V.run (index.7949988e.js:1:2271)
    at Ge.get value [as value] (index.7949988e.js:1:10410)
    at Object.get [as firstFile] (index.7949988e.js:1:31915)
    at Object.get (index.7949988e.js:1:58990)
    at e (logger-1.min.js:8:569079)
    at logger-1.min.js:8:569265
    at l (logger-1.min.js:8:571731)
    at Generator._invoke (logger-1.min.js:8:571519)
    at Generator.next (logger-1.min.js:8:572156)
```
LogRocket SDK Version: 2.2.1

## Expected behavior

This error should be prevented, or caught in vue-advanced-chat.

## Device (please complete the following information)

- OS: Arch Linux
- Browser: Chrome Version 99.0.4844.51 (Official Build) (64-bit)
- Package version: next

## Additional context

We have engaged extensively with LogRocket support attempting to resolve this issue. As the session recording also records all console logs, some errors can cause it to fail. We've narrowed the issue down to a specific function in `MessageReply.vue`, per LogRocket's engineering team:

> ﻿For whatever reason, the `this` being referenced here doesn't have any attributes.
```
﻿firstFile: function() {
    var e;
    return null !== (e = this.messageReply.files) && void 0 !== e && e.length ? this.messageReply.files[0] : {}
},

**Comment by antoine92190** [comment]
Ok, I will have a look shortly and fix the issue

**Comment by bapaynter** [comment]
Thank you!

**Comment by antoine92190** [comment]
Should be fixed in https://github.com/antoine92190/vue-advanced-chat/commit/4a3ab96f9b726e0699e630d05827f1bf6ca61c31

**Comment by antoine92190** [comment]
Could you let me know if this issue is fixed? I just updated the `next` branch.

**Comment by bapaynter** [comment]
Thanks, the original error seems to be resolved, but now we're seeing a new error:
```
Cannot read properties of undefined (reading '0')
    at Proxy.formattedDuration (index.ef9825d5.js:14:379149)
```
Which is originating from `lib/RoomsList/RoomContent/RoomContent.vue`
```
		formattedDuration() {
			const file = this.room.lastMessage.files[0]

			if (!file.duration) {
				return `${file.name}.${file.extension}`
			}

			let s = Math.floor(file.duration)
			return (s - (s %= 60)) / 60 + (s > 9 ? ':' : ':0') + s
		},
```
There may be more issues like this, and it would be inefficient to resolve one at a time this way. I'll do more testing tomorrow and create a PR with any necessary fixes.

**Comment by antoine92190** [comment]
Ok, sounds good.

**Comment by bapaynter** [comment]
Seems like there were fewer issues than I anticipated, please see https://github.com/antoine92190/vue-advanced-chat/pull/297

**Comment by bapaynter** [comment]
Hm, it seems like something has broken. Now when viewing my app locally I'm receiving this error:
```
Uncaught TypeError: Object(...) is not a function
    at Module.fb15 (Loader.vue:12:5)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:83:1
    at bootstrap:83:1
    at chunk.5OSL2VXB.js?v=37b496b9:4:5
    at dep:vue-advanced-chat:1:24
```
`dep:vue-advanced-chat:1:24` is:
```
export default require("./node_modules/vue-advanced-chat/dist/vue-advanced-chat.common.js");
```

**Comment by antoine92190** [comment]
Mmm I don't have this issue on my side.
Have you tried to delete `node_modules` and `package-lock.json` and re-run `npm install`?

**Comment by bapaynter** [comment]
I had an issue with package-lock - reverted to an earlier version and every looks good. Thanks for your help with this!
