### ISSUE TITLE
The problem of the first expansion of the expression panel

### ISSUE THREAD

**Issue by just0351** [antoine92190/vue-advanced-chat#298]
When the expression panel is first expanded, there will be a Caton animation from left to right. I don't know if this is a problem, but it's really uncomfortable

https://user-images.githubusercontent.com/103582888/163195817-92e3fad1-8206-4808-8940-b7e5e4ff2ce8.mp4

**Comment by antoine92190** [comment]
Yes I noticed that also, it's not intended, I will try to fix it soon. Don't hesitate to send a PR if you can fix the issue.

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/731839c94600ac5761520a98a656f35703a3e300
