### ISSUE TITLE
Messages will not load if I will try to hard code it on the script

### ISSUE THREAD

**Issue by sintexph** [antoine92190/vue-advanced-chat#3]
![image](https://user-images.githubusercontent.com/47470967/78417598-38359980-7666-11ea-87ce-6ecdfec3bef9.png)
I will be pushing a new object which is working but if I will try to instantiate the message variable, the message will not load.

The display is like this
![image](https://user-images.githubusercontent.com/47470967/78417621-7206a000-7666-11ea-85c5-aac2ce1fddd9.png)

**Comment by antoine92190** [comment]
I'm not 100% sure to understand your issue. Do you have any errors on the console?
You can have a look at the demo code I provided within the repo, line 334.

To add a new message or update a specific message, you can do as below:

```
// To add a new message
this.messages = this.messages.concat([newMessage])

// To update a specific message
this.$set(this.messages, newMessageIndex, newMessage)
```

**Comment by sintexph** [comment]
> I'm not 100% sure to understand your issue. Do you have any errors on the console?
> You can have a look at the demo code I provided within the repo, line 334.
> 
> To add a new message or update a specific message, you can do as below:
> 
> ```
> // To add a new message
> this.messages = this.messages.concat([newMessage])
> 
> // To update a specific message
> this.$set(this.messages, newMessageIndex, newMessage)
> ```

Thank you I think I got it already, anyways I have questions below hope you can help me.

1. do you have an idea on how to disable the actions on the specific message only?
2. how to reflect the username on each message?

thank you in advance

**Comment by antoine92190** [comment]
1. This can be a nice feature to add, I can implement it shortly and let you know when it's done

2. I intentionally hide the username when there are only 2 persons in the room.
I feel like showing username on each message would be unnecessary.
However, username will appear on each message if there are 2+ users in the room.
But I am open to the idea, do you think it is actually useful to have the username shown on each message if only 2 persons are in the room?

**Comment by sintexph** [comment]
> 1. This can be a nice feature to add, I can implement it shortly and let you know when it's done
> 2. I intentionally hide the username when there are only 2 persons in the room.
>    I feel like showing username on each message would be unnecessary.
>    However, username will appear on each message if there are 2+ users in the room.
>    But I am open to the idea, do you think it is actually useful to have the username shown on each message if only 2 persons are in the room?

1. Thank you very much I really appreciate it.
2. I see the username will only display if there are more than 2 users, that makes sense, I just didn't know since I did not see it on the documentation but just keep it that way.

**Comment by antoine92190** [comment]
Sounds good. Just added the option to disable actions and/or reactions for a specific message: https://github.com/antoine92190/vue-advanced-chat/commit/14363932aa758c297cd2eccb5736f2202f3703f0

**Comment by antoine92190** [comment]
Also added the username conditional display on the documentation: https://github.com/antoine92190/vue-advanced-chat/commit/98058e36f714c8e80a83eb4a3020326489232223
Thanks!

**Comment by sintexph** [comment]
Thank you very much, I will just wait for your update in NPM
