### ISSUE TITLE
Run error：JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by kingStrong2022** [antoine92190/vue-advanced-chat#301]
environment:
System: macOS 12.3.1. Apple M1 Max
node version: v14.19.1
npm version: 6.14.16

Bug Recovery Process：

1. Clone the repository using git clone https://github.com/YOUR_USERNAME/vue-advanced-chat
2. Go inside your cloned repository and run npm install
3. Go inside the demo folder and run npm install
4. Run npm run serve inside the demo folder to open the demo app

## Screenshots
<img width="1455" alt="图片" src="https://user-images.githubusercontent.com/101569383/164420635-b665ef2c-313a-44b9-aba5-06d23b6977e6.png">

**Comment by antoine92190** [comment]
Can you confirm you are using vue version 2.6.14 or above?

**Comment by kingStrong2022** [comment]
> Can you confirm you are using vue version 2.6.14 or above?

<img width="587" alt="图片" src="https://user-images.githubusercontent.com/101569383/164424790-ef16c4b8-f249-4940-8f05-f2b171cb6a5e.png">
I'm new to vue, is this the correct way to get the vue version number?

**Comment by kingStrong2022** [comment]
> Can you confirm you are using vue version 2.6.14 or above?

<img width="548" alt="图片" src="https://user-images.githubusercontent.com/101569383/164433045-a92076ef-1c89-4b89-b65c-64b1de5423b9.png">

**Comment by antoine92190** [comment]
Have you followed all the installation steps correctly? https://github.com/antoine92190/vue-advanced-chat#using-with-firestore

**Comment by antoine92190** [comment]
Closing this until you confirmed using the installation steps correctly.
