### ISSUE TITLE
Emoji size is too small

### ISSUE THREAD

**Issue by Shivam-apna** [antoine92190/vue-advanced-chat#305]
- Emoji size is very small 
- Can we increase the size of emoji

**Comment by VladimirMoroz95** [comment]
> * Emoji size is very small
> * Can we increase the size of emoji
> 
> Add any other context or screenshots about the feature request here.

Emoji have a text format. You can to increase size of emoji with "font-size"

**Comment by Shivam-apna** [comment]
text size is also increase if we increase the font size

**Comment by antoine92190** [comment]
Which emojis? The ones in the emoji picker panel, or the ones displayed in room messages?

**Comment by Shivam-apna** [comment]
One which is displayed in room messages

**Comment by Shivam-apna** [comment]
any update

**Comment by antoine92190** [comment]
The solution could be to add a specific font size when a message only contains emojis without any text.
If you want this fixed quickly, feel free to open a PR, otherwise I will fix that when I get the time.

**Comment by Shivam-apna** [comment]
can you please fix it bcz i want to know and implement it in my project

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/a4da2524402033d30a00922416307ad2db290ae4

**Comment by Shivam-apna** [comment]
antoine after implementing this numbers font get bigger

**Comment by antoine92190** [comment]
Ok I will check it

**Comment by Shivam-apna** [comment]
any update..

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/e999ae1ba9d6c49b478dbb80a6f7ed8726747163
