### ISSUE TITLE
Config firebase with demo

### ISSUE THREAD

**Issue by joweste** [antoine92190/vue-advanced-chat#31]
Hi, I am trying to use the demo with firebase.
But I get an error as below.

I have used the next config in demo app:
```
const config = {
    apiKey: "mykey",
    authDomain: "gestandev.firebaseapp.com",
    databaseURL: "https://gestandev.firebaseio.com",
    projectId: "gestandev",
    storageBucket: "gestandev.appspot.com",
    messagingSenderId: "702434346623",
    appId: "1:702434346623:web:cb4b57d585e8571175614a",
    measurementId: "G-30135K4QVE"
  };

```
//my firebase rules
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}

error:
```
```
Uncaught (in promise) TypeError: Cannot read property 'username' of undefined
    at eval (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/ChatContainer.vue?vue&type=script&lang=js&:234)
    at async Promise.all (:8080/index 1)
webpack-internal:///./node_modules/@firebase/database/dist/index.cjs.js:12881 Uncaught (in promise) Error: PERMISSION_DENIED: Permission denied
    at eval (webpack-internal:///./node_modules/@firebase/database/dist/index.cjs.js:12881)
    at exceptionGuard (webpack-internal:///./node_modules/@firebase/database/dist/index.cjs.js:702)
    at Repo.callOnCompleteCallback (webpack-internal:///./node_modules/@firebase/database/dist/index.cjs.js:12871)
    at eval (webpack-internal:///./node_modules/@firebase/database/dist/index.cjs.js:12765)
    at eval (webpack-internal:///./node_modules/@firebase/database/dist/index.cjs.js:11846)
```
![image](https://user-images.githubusercontent.com/30800736/95083370-cf9da700-06f2-11eb-8494-0f9cd947b0b5.png)

**Comment by antoine92190** [comment]
There is probably an `undefined` user value in you code at some point.
Can you share the `rooms` and `messages` prop values?

**Comment by joweste** [comment]
Hi, Mr Antonie. 
I didn´t change nothing on demo. 
The rooms and messages are the same of the git repo.

I just cloned the repo and I put my own config in firebase.

**Comment by antoine92190** [comment]
Can you send a screenshot of one user in the `users` collection of your firestore database?

**Comment by joweste** [comment]
Hi, Here is:
![image](https://user-images.githubusercontent.com/30800736/95084852-d5948780-06f4-11eb-95d9-1eb04af28881.png)

**Comment by joweste** [comment]
Here is what happend after load and try create a room with the app.
It´s locked with an error and a spin circle.
![image](https://user-images.githubusercontent.com/30800736/95085682-f1e4f400-06f5-11eb-89dc-8664d2013ac2.png)

**Comment by antoine92190** [comment]
In the first screenshot you have a user id `6R0...CY2` which doesn't exist in your `users` collection

**Comment by joweste** [comment]
Ok, I just deleted all collections from firebase.
When I refresh the app, I get:
```
index.cjs.js?3523:12881 Uncaught (in promise) Error: PERMISSION_DENIED: Permission denied
    at eval (index.cjs.js?3523:12881)
    at exceptionGuard (index.cjs.js?3523:702)
    at Repo.callOnCompleteCallback (index.cjs.js?3523:12871)
    at eval (index.cjs.js?3523:12765)
    at eval (index.cjs.js?3523:11846)

```
But I give all permissions as posted above.
Do you have some idea about it?

**Comment by antoine92190** [comment]
Can you share your repo? I cannot really debug otherwise

**Comment by joweste** [comment]
Sure I can share my repo.
But, please tell me if my config in firebase is enough.
Maybe I have a rights/rules config problem.
Here is:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
```

**Comment by antoine92190** [comment]
Maybe try
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write
    }
  }
}
```

**Comment by joweste** [comment]
No look. Same error.

**Comment by antoine92190** [comment]
Please share you repo, otherwise I cannot do much.

**Comment by joweste** [comment]
How can I share the repo  with you?
A private zip file?
How about my firebase credentials?

**Comment by antoine92190** [comment]
Is the repo private? If so, you can invite me as a collaborator to the project.
I will also need the firebase credentials to be able to debug. If you don't want to share it, you can quickly create  a new firebase project that reproduces the same issue, then delete it when the issue is figured out.

**Comment by joweste** [comment]
One moment please, I will create the repo.
I use bitbucket

**Comment by joweste** [comment]
I sent you a invite to your project at bitbucket account

**Comment by antoine92190** [comment]
I haven't received anything. You should probably send the invite using my bitbucket username: adupont

**Comment by joweste** [comment]
I sent for this email: antoindupontdev@gmail.com
adupont is not found in bitbucket users.

![image](https://user-images.githubusercontent.com/30800736/95101676-cd464780-0708-11eb-8186-3919638fbde8.png)

**Comment by antoine92190** [comment]
You made a typo in the email. And better to use dupontantoine92@gmail.com instead as my bitbucket account is using this email.

**Comment by joweste** [comment]
There ios no account to  dupontantoine92@gmail.com in bitbucket.
I sent you a invite as a new member:
![image](https://user-images.githubusercontent.com/30800736/95102479-d257c680-0709-11eb-9770-5fdd1d3796a3.png)

**Comment by antoine92190** [comment]
As I said above, the `6R0MijpK6M4AIrwaaCY2` user doesn't exist in you database. Please add it and retest. If there is still an  issue let me know.

**Comment by joweste** [comment]
Mr Antoine,
I am not creating new users without use the demo.
All users are created using the demo.
The user 6R0MijpK6M4AIrwaaCY2 is created by demo app.
I have no way to avoid it.

**Comment by joweste** [comment]
I did some fixes on demo and now it´s working.
But I still have the next error, can you help me?
```
index.cjs.js?3523:12881 Uncaught (in promise) Error: PERMISSION_DENIED: Permission denied
    at eval (index.cjs.js?3523:12881)
    at exceptionGuard (index.cjs.js?3523:702)
    at Repo.callOnCompleteCallback (index.cjs.js?3523:12871)
    at eval (index.cjs.js?3523:12765)
    at eval (index.cjs.js?3523:11846) 
```

**Comment by antoine92190** [comment]
Please push your fixes on bitbucket so I will check your latest version

**Comment by joweste** [comment]
> Please push your fixes on bitbucket so I will check your latest version

I just push my fixes

**Comment by antoine92190** [comment]
Also, you need to setup a Realtime Database in your Firebase project to enable the users online status, that's probably the reason why you get the error.

**Comment by joweste** [comment]
> Also, you need to setup a Realtime Database in your Firebase project to enable the users online status, that's probably the reason why you get the error.

Thank  you.
I just enabled a Realtime Database and all is ok.
