### ISSUE TITLE
Scrolling issue in room messages

### ISSUE THREAD

**Issue by Shivam-apna** [antoine92190/vue-advanced-chat#312]
When i enter a tall text with multiple lines and the input box expands, the chat from top starts hiding, it should scroll up effectively so the last message is visible
![Screenshot (389)](https://user-images.githubusercontent.com/102787302/169784396-207a7184-c671-41ec-b376-dfeda69a26f4.png)

**Comment by Shivam-apna** [comment]
Antoinee can you please look into this

**Comment by Shivam-apna** [comment]
Check it once

**Comment by xiejohnny** [comment]
how to set multiple lines? @Shivam-apna

**Comment by Shivam-apna** [comment]
@xiejohnny Shift + Enter

**Comment by xiejohnny** [comment]
> @xiejohnny Shift + Enter

thanks

**Comment by Shivam-apna** [comment]
> > @xiejohnny Shift + Enter
> 
> thanks

always welcome

**Comment by Shivam-apna** [comment]
Antoine can you give your time to fix this bcz i need to fix this in my project..

**Comment by antoine92190** [comment]
Closing this as the following issue is more detailed: https://github.com/antoine92190/vue-advanced-chat/issues/404
