### ISSUE TITLE
Adding named slot for system messages

### ISSUE THREAD

**Issue by lterlueuen** [antoine92190/vue-advanced-chat#316]
It would be great if there would be named slots for system messages. This is needed in our case for example to 
attach a timestamp or a link to the system message.

**Comment by antoine92190** [comment]
I agree, I can add that soon, or you can create a PR if you want this quicker.

**Comment by lterlueuen** [comment]
It would be nice if you could add that.

**Comment by antoine92190** [comment]
Added in https://github.com/antoine92190/vue-advanced-chat/commit/c31a87c2693018009895a5fedcf395bbf81583c8
