### ISSUE TITLE
Change text input placeholder

### ISSUE THREAD

**Issue by OkilSaber** [antoine92190/vue-advanced-chat#319]
My application is in french and I would like to add a custom placeholder for the message input but I currently cannot (or I haven't found how to) and this is pretty frustating.

The way I see this being implemented is with a simple prop ``input-placeholder`` of type ``String`` to the ``ChatWindow`` component.
This:
![image](https://user-images.githubusercontent.com/54351241/173505784-ce3791a9-889f-4b89-a1f1-dd9d4f56f383.png)
Would become like this after modification:
![image](https://user-images.githubusercontent.com/54351241/173505922-6328caba-492e-4a9a-aa49-65f8cc456c22.png)

And an example of it being used:
```js
    <chat-window :input-placeholder:"'Votre message'" :current-user-id="currentUserId" :rooms="rooms" :messages="messages" @fetch-messages="getMessages"
      @add-room="addRoom" :show-files="false" :show-audio="false" :height="'800px'" :load-first-room="false"
      :loading-rooms="loadingRooms" :rooms-loaded="roomsLoaded" :messages-loaded="messagesLoaded"
      :show-new-messages-divider="false" />```

**Comment by antoine92190** [comment]
You can use `text-messages` prop:
```
text-messages="{
  TYPE_MESSAGE: 'Tapez votre message',
}"
```
