### ISSUE TITLE
Where is the sample data?

### ISSUE THREAD

**Issue by vesper8** [antoine92190/vue-advanced-chat#328]
I'm trying to get this installed and I don't have Firebase and I'm having a hell of a time just figuring out what format the rooms and messages should be in. I just want to set up a purely static demo to start and can't even get that working. I also tried to inspect the XHR requests from the firebase demo and I can't figure out how it's working! I don't see json data being returned anywhere.. it's so weird.. it's like the chatrooms and the messages are being populated by magic. Is there a dump of the sample data somewhere?

Any chance you could include a demo that doesn't involve a database but just has a few rooms and a few messages hardcoded? That's what I would really like to see

**Comment by antoine92190** [comment]
You can check this repo: https://github.com/antoine92190/vue-advanced-chat-sandbox

**Comment by vesper8** [comment]
Thank you very much @antoine92190 ! That's just what I needed.

Can you help me understand something else.. I'm struggling to find out how I can start in the 'room' view on mobile?

I want it so that when you visit a certain route, it loads the messages from that chat room only (id is in the route) and to not display the list of rooms at all here, only the mobile chatroom.

I see others have mentioned this before.. it would be super useful to have some insight on how to accomplish this?

Personally, even on desktop, I would like to do away with your 'rooms list' and handle that myself and only use this library for the functionalities and features of the "chat room" itself.

Can you give me some advice please?

Many thanks!

**Comment by antoine92190** [comment]
This is mentioned in the docs:
```
(23) single-room can be used if you never want to show the rooms list on the left. You still need to pass the rooms prop as an array with a single element.
```
