### ISSUE TITLE
Can't use props 'styles' in React

### ISSUE THREAD

**Issue by mr-teddy-bear** [antoine92190/vue-advanced-chat#329]
## Describe the bug

When i try use props "styles" from my chat, i get error 
`"[Vue warn]: Invalid prop: type check failed for prop "styles". Expected Object, got String with value "[object Object]"."`

My component
![image](https://user-images.githubusercontent.com/46103779/178848151-608d54fc-81f7-448f-b612-da3a8914dc93.png)

Error in console
![image](https://user-images.githubusercontent.com/46103779/178848204-eac6c6f0-41cd-4d20-a711-0d81e973ba35.png)

My styles, which i try for use
![image](https://user-images.githubusercontent.com/46103779/178848339-396f5897-183d-415c-9b7e-ea600789ae1c.png)

Please, help me)

**Comment by antoine92190** [comment]
Hi,
First your styles object is not correct, it should look like this:
```
styles="{
  general: {
    color: '#0a0a0a',
    colorSpinner: '#333',
    borderStyle: '1px solid #e1e4e8'
  },

  footer: {
    background: '#f8f9fa',
    backgroundReply: 'rgba(0, 0, 0, 0.08)'
  },

  icons: {
    search: '#9ca6af'
  }
}"
```
Second, you need to check this repo for React compatibility example: https://github.com/antoine92190/vue-advanced-chat-sandbox/tree/react
You will need to use `reactify-wc` package to make it work.
If you manage to make the chat work with React in a more simple way, I would be glad to know how.

**Comment by mr-teddy-bear** [comment]
Reactify-wc not working with React 17+
I can't use reactify
Maybe you know other way for using 'styles', because if I use styles like in your example, it's also not worked, and i get same error about [Object object]

**Comment by antoine92190** [comment]
You need to use an alternative to reactify-wc if it’s not working. I don’t know which one, but you can try to find one. Otherwise you can also change styles by overriding CSS classes

**Comment by antoine92190** [comment]
You can also check this, someone seems to have a working solution for that: https://stackoverflow.com/a/69672662

**Comment by antoine92190** [comment]
This issue will be fixed in the next migration of this plugin, which will become focused on web component only.
