### ISSUE TITLE
Unread messages counter for each room

### ISSUE THREAD

**Issue by hanatharesh2712** [antoine92190/vue-advanced-chat#33]
Thank you for making such a great plugin!!

Is there any plan to provide an unread message counter for each room? It would help to know what rooms have unread messages.
like as below:
![image](https://user-images.githubusercontent.com/17156331/95313708-11bf1800-08ae-11eb-9ae1-8c646c44b7d5.png)

**Comment by antoine92190** [comment]
Feature added in https://github.com/antoine92190/vue-advanced-chat/commit/f50b2c624a1f1a235529c670adac6077ef5bc0c5.

You can display the counter by adding the `unreadCount` property to each room object.
You can change the `backgroundCounterBadge` and `colorCounterBadge` colors using the `theme` prop.

Thanks for your feedback!
