### ISSUE TITLE
why templatesText click not working

### ISSUE THREAD

**Issue by chiukovo** [antoine92190/vue-advanced-chat#334]
## Describe the bug

templatesText
do mouseover ok
but click not working
thanks

## Screenshots

![1659495759770](https://user-images.githubusercontent.com/11659606/182515497-4952e30c-7483-42e0-aad8-e04f85c306da.jpg)
![1659495783388](https://user-images.githubusercontent.com/11659606/182515480-a4693435-2651-4ae8-8bdd-2fea6032caca.jpg)

## Device (please complete the following information)

- OS: Windows 10
- Browser:  Chrome 103.0.5060.134
- Package version: 1.5.7

**Comment by antoine92190** [comment]
It's working on my side... Could you share a minimal example repo to reproduce the issue?

**Comment by antoine92190** [comment]
Is it working on the demo for you ? https://antoine92190.github.io/vue-advanced-chat/

**Comment by chiukovo** [comment]
sandbox example
thanks u :)

https://codesandbox.io/s/hardcore-shamir-nwlh0w

> Is it working on the demo for you ? https://antoine92190.github.io/vue-advanced-chat/

**Comment by chiukovo** [comment]
> It's working on my side... Could you share a minimal example repo to reproduce the issue?

sandbox example
thanks u :)

https://codesandbox.io/s/hardcore-shamir-nwlh0w

**Comment by chiukovo** [comment]
add setTimeout it's working lol
but i don't know why ....

![1659579627024](https://user-images.githubusercontent.com/11659606/182748985-b4231673-1133-42d5-b61a-7e00440e06d3.jpg)

**Comment by antoine92190** [comment]
Thanks, I can reproduce. I will fix this ASAP

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/cc6ad4f6f6211fb0ab8285796e04cc8c746a9970
Actually, the list was destroyed at the same time as the click action was done, so the click was not computed.
Not sure where this regression comes from, but it should work fine now.
Will release a new version later today.

**Comment by chiukovo** [comment]
great! thanks you

> Fixed in [cc6ad4f](https://github.com/antoine92190/vue-advanced-chat/commit/cc6ad4f6f6211fb0ab8285796e04cc8c746a9970) Actually, the list was destroyed at the same time as the click action was done, so the click was not computed. Not sure where this regression comes from, but it should work fine now. Will release a new version later today.
