### ISSUE TITLE
after I select one user tag, the textarea does not show my choosed item.

### ISSUE THREAD

**Issue by 1259549061** [antoine92190/vue-advanced-chat#335]
## Describe the bug
after I select one user tag, it does not work! the reason may be the blur event runs before click event.  so, the textarea does not show my choosed item.

How can I do~

- OS: mac
- Browser: Chrome latest
- Package version: [e.g. 2.2.0]
- vue 2.7.3
- vue-advanced-chat 1.5.3

please help

**Comment by antoine92190** [comment]
It's working on my side... Could you share a minimal example repo to reproduce the issue?
Is it working on the demo for you ? https://antoine92190.github.io/vue-advanced-chat/

**Comment by 1259549061** [comment]
> It's working on my side... Could you share a minimal example repo to reproduce the issue? Is it working on the demo for you ? https://antoine92190.github.io/vue-advanced-chat/

thank you for your reply! this demo is working on my side too. I will try to show a demo ...

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/cc6ad4f6f6211fb0ab8285796e04cc8c746a9970

**Comment by 1259549061** [comment]
> Fixed in [cc6ad4f](https://github.com/antoine92190/vue-advanced-chat/commit/cc6ad4f6f6211fb0ab8285796e04cc8c746a9970)

oh, so nice~ thank you very much, so, can I use branch [master] ? or what's the publish time of the next tag

**Comment by antoine92190** [comment]
New version 1.5.8 is released
