### ISSUE TITLE
Drag & drop files upload

### ISSUE THREAD

**Issue by Alisonispig** [antoine92190/vue-advanced-chat#336]
## Describe the solution you'd like

I want to add a file drag upload function, which is very necessary in some cases.

**Comment by antoine92190** [comment]
Yes I agree, feel free to send a PR for that.

**Comment by Furqan2** [comment]
@Alisonispig are you going to give PR soon ??

**Comment by antoine92190** [comment]
The implementation should be easy, you just need to make sure the drag and drop calls the following function: https://github.com/antoine92190/vue-advanced-chat/blob/master/src/lib/Room/RoomFooter/RoomFooter.vue#L498-L524

**Comment by Furqan2** [comment]
@antoine92190 thanks for the response can you guide me how exactly i can call this function .... i have drag function with witch i have data property of files now how can i just call onFileChange from my function .... I'm new to Vuejs so.

**Comment by Furqan2** [comment]
i don't understand all i understand is i have to make my drag and drop function and the call the ;library function to pass the files.

**Comment by antoine92190** [comment]
Your drag and drop function needs to be inside the library file, it should be part of the library. If you don't know how to do it, you will need to wait until I implement the feature myself.

**Comment by Furqan2** [comment]
It will be great to have this feature as i need it badly and im stuck on this. Thanks

**Comment by antoine92190** [comment]
Feature added in https://github.com/antoine92190/vue-advanced-chat/commit/3fe2feeb4eab37474bcd433b0c419e5f3fc30a1a
You can try it out on the demo until I release it: https://antoine92190.github.io/vue-advanced-chat/

**Comment by Furqan2** [comment]
Thats a very good move, working good on demo lets try out in real application, when will it be available.

**Comment by Furqan2** [comment]
@antoine92190 hey when the update release4 gonna happen ??
