### ISSUE TITLE
How can I track change state of unseen messages?

### ISSUE THREAD

**Issue by MaxCpp** [antoine92190/vue-advanced-chat#339]
I will describe the problem. My server returns 20 latest messages and room information with the number of unread messages. Let's assume that the user has written 30 messages and he has not read them yet. Accordingly, in `room.unreadCount` I set the value to 30 and the user sees the number of unread messages in the list of rooms. But when the user opens the room, he will only see the last N-messages (for example, 10) that will be on the screen. And all these 10 messages should change the value of the `message.seen` from `false` to `true`. The remaining `room.unreadCount - 10` messages that are above (off the screen) should change seen to true only if the user starts scrolling up and as soon as the message is visible on the screen, then change the `value` of `message.seen`.
Hence the questions.
1. How to track what message is on the screen?
2. Or how do I determine the first 10 messages that should be displayed on the screen?

Or tell me how to solve my problem in another way. Thanks in advance.

**Comment by antoine92190** [comment]
This logic should be written outside of the chat component, but you can check if messages are visible on the screen by using javascript, for example. You could probably trigger this function every time a user is scrolling.
```
function checkVisible(elm) {
  var rect = elm.getBoundingClientRect();
  var viewHeight = Math.max(document.documentElement.clientHeight, window.innerHeight);
  return !(rect.bottom < 0 || rect.top - viewHeight >= 0);
}
```

**Comment by MaxCpp** [comment]
I assumed need to implement it outside of the chat component.
Thanks for the tip.
