### ISSUE TITLE
User tag click is not working - reopen #335

### ISSUE THREAD

**Issue by 1259549061** [antoine92190/vue-advanced-chat#344]
the same bug with #335
https://github.com/antoine92190/vue-advanced-chat/issues/335
I have updated to new version 1.15.8, but it does not work some times.
in pc, bug 50%, 
in mobile, bug is not happen.  do not know why ~
please check it  ,thank you ~

Tip: one time,  hover to one item (item A) and do not click, mouseleave the items and then  back to the item A ,,, click it, the bug is happen ( do not  happen 100%)

**Comment by antoine92190** [comment]
Ok I will check it.
Could you migrate the version to 2.0.0 and let me know if the bug still exists there?
Migration guide to update to 2.0.0 version: https://github.com/antoine92190/vue-advanced-chat/releases/tag/2.0.0

**Comment by 1259549061** [comment]
> Ok I will check it. Could you migrate the version to 2.0.0 and let me know if the bug still exists there? Migration guide to update to 2.0.0 version: https://github.com/antoine92190/vue-advanced-chat/releases/tag/2.0.0

sorry, I try it ,but .... our project use vue 2.x., the version 2.0.0 use vue 3.x

**Comment by antoine92190** [comment]
It should work with vue 2 as well.
This example uses vue 2 and works with it: https://github.com/antoine92190/vue-advanced-chat-sandbox/tree/main

**Comment by 1259549061** [comment]
> It should work with vue 2 as well. This example uses vue 2 and works with it: https://github.com/antoine92190/vue-advanced-chat-sandbox/tree/main

haha I try it just now .the example works ok

**Comment by antoine92190** [comment]
Is the your issue solved then? Can I close this issue?

**Comment by 1259549061** [comment]
> Is your issue solved then? Can I close this issue?
it has other problems, ... for example  :rooms="JSON.stringify(rooms)" .........  the type of params is different from before, and the doc  *** Prop: rooms   type: Array  default [] ***
so ,I studied it ，yesterday, because of it (JSON.parse ), my project can not run 
emm... 
<img width="757" alt="WeChatfa2deb9c426fe17914ea270a9b84771c" src="https://user-images.githubusercontent.com/28998743/187010771-fc3ef1cf-0785-4a16-bd8c-5949ac3c3699.png">

**Comment by antoine92190** [comment]
Have you tried to pass the rooms prop as a string using JSON.stringify as mentionned in the docs? All props which are array or object must be passed as strings

**Comment by antoine92190** [comment]
I updated the documentation about props types and usage: https://github.com/antoine92190/vue-advanced-chat/commit/7498a7d3bf63f724fbbe0cb91713c8e7d9d5b950

**Comment by 1259549061** [comment]
> Have you tried to pass the rooms prop as a string using JSON.stringify as mentionned in the docs? All props which are array or object must be passed as strings

yes~ it's ok, you can close this issue. thank you very much
