### ISSUE TITLE
How do you toggle rooms list visibility externally?

### ISSUE THREAD

**Issue by vlahde** [antoine92190/vue-advanced-chat#346]
How do you toggle rooms list visibility externally?
:rooms-list-opened="false"
wont work. showRoomsList is true in the data section.

**Comment by antoine92190** [comment]
Indeed, rooms-list-opened should toggle the rooms list visibility. I’ll have a look and fix it.

**Comment by vlahde** [comment]
Thanks antoine and thank you for a great repo!

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/e87345fb74c01572c533467604eca8f2cbc16d03
