### ISSUE TITLE
Scroll to Quoted message onClick

### ISSUE THREAD

**Issue by Gikabu** [antoine92190/vue-advanced-chat#347]
Can we have an auto-scroll animation when the quoted message is clicked?

**Comment by antoine92190** [comment]
That would be difficult because of pagination. That’s definitely something I want to tackle, but it will take some time.

**Comment by Gikabu** [comment]
Alright. Thanks

**Comment by antoine92190** [comment]
Let’s not close this, it’s a good idea, I just don’t have time right now to implement it.

**Comment by antoine92190** [comment]
Closing this as duplicate https://github.com/antoine92190/vue-advanced-chat/issues/410
