### ISSUE TITLE
Upload video does not work

### ISSUE THREAD

**Issue by backurdi** [antoine92190/vue-advanced-chat#349]
## Describe the bug

When uploading video, noting is displayed in the message and following error is displayed in the console when you click on the message. Behaivior is happening in both the demo project and my own project.

## Steps to reproduce

Upload foto can be a local video uploaded from the computer or a recording directly from the phone.
Nothing is displayed in the message
Click on the message
Check the console

## Expected behavior

The video should be visible in the chat and clicking it should play the video

## Screenshots
<img width="1512" alt="Screenshot 2022-09-03 at 22 22 19" src="https://user-images.githubusercontent.com/25648047/188286632-f494137d-1cc1-45bc-b0ae-f9aa7def44f5.png">

## Device (please complete the following information)

- OS: IOS mac, Andriod Oneplus phone
- Browser: Chrome
- Package version: 2.0.0

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/issues/349
