### ISSUE TITLE
Named slot are not working

### ISSUE THREAD

**Issue by ThomasTogether** [antoine92190/vue-advanced-chat#351]
## Describe the bug

Named slots are not working. It triggers the error : 
`Codegen node is missing for element/if/for node. Apply appropriate transforms first.`

## Steps to reproduce

Code here : https://stackblitz.com/edit/vitejs-vite-sbf6yv?file=src%2FApp.vue,src%2Fcomponents%2FHelloWorld.vue,src%2Fstyle.css&terminal=dev

## Device (please complete the following information)

Tested on :
- OS: MacOS and Win11
- Browser: Chrome, Firefox

## Additional context

Used with Vite and Vue 3

**Comment by antoine92190** [comment]
Please read the documentation: https://github.com/antoine92190/vue-advanced-chat#named-slots
This is a web component, not a vue component, so you need to use it as such.

**Comment by melvin78** [comment]
Hi, i think you could add an extra section on the documentation for those using vue3 on how to use named slots because the syntax is different. The above code you provided does not work in vue 3. Have tested it doesnt seem to work. Have used this instead seems to work fine: 
` <template #room-header>
            This is a new room header
        </template>
`

**Comment by antoine92190** [comment]
It's working on my side. Will check this

**Comment by melvin78** [comment]
could it be we are using different package versions. This is the version in my package.json
```
//package.json
        "vue-advanced-chat": "https://github.com/antoine92190/vue-advanced-chat/tarball/next"

```

Same applies with the named message slots, according to the documentation to add custom message slot you should name your slot this way `message_{{MESSAGE_ID}}` but this doesn't work. Using just `message` and leaving out the `_id` part works. Have ran into other similar situations am open to make a PR to the documentation part for users who would be using the newer versions. Again Great package!

**Comment by antoine92190** [comment]
You need to use the `master` branch, it supports vue 3 by default. The `next` branch is deprecated and not maintained anymore. I will delete it soon.

**Comment by melvin78** [comment]
ok thanks. I will revert

**Comment by antoine92190** [comment]
Issue seems to be fixed. Please reopen otherwise

**Comment by CRC32EX** [comment]
template seems not working.
[Reproducing the problem(StackBlitz)](https://stackblitz.com/edit/vitejs-vite-2tqbhz?file=src%2FApp.vue&terminal=dev)

### Environment
- vue: 3.2.47
- vue-advanced-chat: 2.0.7
- vite: 4.2.0

**Comment by antoine92190** [comment]
Please read the documentation on how to use templates:
```
<div slot="room-header">
  This is a new room header
</div>
```
