### ISSUE TITLE
[Feature request] Allow usage of Vue components for vue users

### ISSUE THREAD

**Issue by JonLev** [antoine92190/vue-advanced-chat#352]
## Is your feature request related to a problem? Please describe

Hi there, usage of the library is ok as it is, but it's too bad that Vue 3 users can't use it directly as a vue component :( 
That would allow them to use props as reactive properties more easily and usage of custom CSS from outside. 

Even if I get the spirit of having a fair package with the same doc and usage for every framework, the documentation is already slightly different for Vue users (with specific links to vue documentation) and I believe that this small change will make the adoption of the package easier.

## Describe the solution you'd like

start by adding in `src/lib/index.js` a named export that would result in `export const ChatWindow = ChatWindow`, and adapting the logic that are linked to the use of it as a web component.
Obviously add the needed doc for it.

## Describe alternatives you've considered

Using it as a web component with its needs of interfaces and complexity

## Additional context

.

**Comment by antoine92190** [comment]
Does your solution work with named slots?

**Comment by JonLev** [comment]
My bad @antoine92190, I didn't dig enough in the code and realized that a lot of logic is _deeply linked_ to the foundation of having this package as a web component. that mean that means that for the named slots and other logic (that start by looking the shadowRoot of the component) would need a refactoring and different logic to attain the same goal.
I'll try to work on this on my spare time, but do you consider it as a valid feature request ? if not, I'll probably prefer use it as it is, even it's a bit more painful...

**Comment by antoine92190** [comment]
I'm open to the idea, but how is it more painful specifically?
- Props are used exactly the same way, you just need to pass those as strings instead.
- You can also customise CSS from outside, the same way I did it here: https://github.com/antoine92190/vue-advanced-chat/blob/master/src/components/EmojiPickerContainer/EmojiPickerContainer.vue#L85-L113
It's not as simple as a classic Vue implementation, but it's not that painful...

**Comment by JonLev** [comment]
Agree, not that painful neither critical for usage. At least for now 😅  But it could be a nice to have for adoption of the lib.
Like I said, I'll try to take some time on my spare time to do so, so it will not be immediate. But at least now that I have your consent, I know it could be integrated 🙏🏽 

Issue can be close for now, I'll re-open it when I'm ready. Thanks for the reactivity 🙏🏽

**Comment by antoine92190** [comment]
Great, if you find a clean solution to be able to use this library as a web component or a Vue component, I'm more than happy to consider it :)
