### ISSUE TITLE
Supabase support would be a nice addition 

### ISSUE THREAD

**Issue by ZiadJ** [antoine92190/vue-advanced-chat#353]
The benefits are that it is fully open-source and allow for [self-hosting](https://supabase.com/docs/guides/hosting/overview) for more control and cost savings. It has a [ friendly api](https://supabase.com/docs/guides/api) for [realtime messaging](https://supabase.com/docs/guides/realtime), and provides a [migration guide from Firestore](https://supabase.com/docs/guides/migrations/firestore-data) so it should not be too difficult I guess.

**Comment by antoine92190** [comment]
This library supports any backend implementation. The demo is using firebase but you can use whatever backend you want.
