### ISSUE TITLE
Question about new slot 

### ISSUE THREAD

**Issue by duhoang00** [antoine92190/vue-advanced-chat#355]
Hi guys, 

In previous 1.x version, you were allow to bind the room but can I ask why you didn't want to do that in the newer version.

Because I need to the "room" prop from room-header to do something like:
`<template v-slot:room-header="{ room }"> </template >`
Now I have to do something like
`<div slot="room-header"></div>` --> can't get "room" to pass 

Is there any other way, I can achive the same thing since I'm quite new to Vue.

![image](https://user-images.githubusercontent.com/43908251/190042902-2e367f96-c823-4f79-bb35-8ed85ddba6b0.png)
Thank you.

Vue version: 2.6
Vue-advanced-chat version: 2.0.1

**Comment by antoine92190** [comment]
This library is now a web component, and web components is not compatible with slot data.
In the `fetch-messages` event, you can get the selected `room`, so you can store this information in you code and use it in your slot. Something like:
```
<div slot="room-header">
  {{selectedRoom.name}}
</div>
```

**Comment by duhoang00** [comment]
Ah, understood, thank you.
