### ISSUE TITLE
Not being emit @fetch-more-rooms event in vue 2.7.10 

### ISSUE THREAD

**Issue by catthecreator** [antoine92190/vue-advanced-chat#363]
## Describe the bug

I use 
vue 2.7.10 
vue-advacned-chat 2.0.3

## Steps to reproduce

I reproduce the bug in my repo: https://github.com/catthecreator/vue-advanced-chat-sandbox

Scroll down the rooms. An event should be triggered and an alert displayed. Nothing happens

## Expected behavior
The event was called

## Device (please complete the following information)

Windows 10, Chrome 105.0.5195.127

**Comment by antoine92190** [comment]
You need to use `loading-rooms` prop. I pushed the fix on your repo and it's working fine now.
