### ISSUE TITLE
Messages prop for Reply Messages content

### ISSUE THREAD

**Issue by LireEruel** [antoine92190/vue-advanced-chat#364]
Why can't I see the content of the reply message?

![image](https://user-images.githubusercontent.com/47496422/192125429-523d0dea-6a55-4394-818f-8b17e0e91854.png)
this is my prop.
I think the content should be seen because the content has the correct string value.
But the result looks like this.

![image](https://user-images.githubusercontent.com/47496422/192125452-db167e7c-3514-4384-8c92-c6fe4a2ad9e9.png)

What did I do wrong?

**Comment by antoine92190** [comment]
Which chat version are you using?

**Comment by antoine92190** [comment]
Closing this as it was fixed in the latest version. Please reopen if you can still reproduce.
