### ISSUE TITLE
is it possible to listen to the search event?

### ISSUE THREAD

**Issue by catthecreator** [antoine92190/vue-advanced-chat#367]
Hi!
How to use the search? 

I need the database to be searched when the user enters a value into the search bar. Is it possible? what event is used for this? Is it possible to use autocomplete?

Thanks!

**Comment by antoine92190** [comment]
It’s currently not possible, but it could be a nice addition. Feel free to open a PR. You can also use the searchbar named slot to use your own search component.

**Comment by antoine92190** [comment]
You can now use `custom-search-room-enabled` prop and `search-room` event to listen to the search event: https://github.com/antoine92190/vue-advanced-chat/commit/8976dc44e5217e5ffae835d5652bf42fd57b6e10
