### ISSUE TITLE
Fetch more messages does not work with multiple chat windows

### ISSUE THREAD

**Issue by NINI1988** [antoine92190/vue-advanced-chat#368]
## Describe the bug

It is not possible to have multiple chat windows on the same page.
When there are multiple chat windows and you scroll up to the fetch more messages, only the first chat window will fetch new messages and will also trigger this event on the second chat window. 
In the second chat window there will be no fetch more messages event when you scroll up.

We are using the chat component in multiple popup windows to communicate with multiple users at the same time.

## Steps to reproduce

 1. Go to https://playcode.io/vac_multi_chats
 2. Scroll up the second chat window with the name `Room 11` and no messages will be fetched
 3. Scroll up the first chat windows `Room 10`
 5. See that  `Room 10` and `Room 11` will fetch new messages

## Expected behavior

Each chat component should behave independent

## Screenshots

Here is an example of our website:
![grafik](https://user-images.githubusercontent.com/2767665/194553691-91bf4379-0625-4c84-b6ac-ece2135d0abb.png)

## Device (please complete the following information)

- OS: Windows 11
- Browser: Firefox 105, Chrome 106
- Package version: 2.03

**Comment by antoine92190** [comment]
I didn’t think of that. I will try to support multiple chat windows, but if you have any ideas to fix this issue I’m all hears

**Comment by daniser** [comment]
@NINI1988 I am sorry, which window manager library did you use (in the screenshot)? I want to make similar setup.

**Comment by NINI1988** [comment]
It's self implemented by adding divs to the body.
Source: https://gitlab.com/foodsharing-dev/foodsharing/-/blob/master/client/src/conv.js
