### ISSUE TITLE
Room Header size and scrollarea margin

### ISSUE THREAD

**Issue by NINI1988** [antoine92190/vue-advanced-chat#369]
## Describe the bug

The sizes of the header and the margin-top of the messages scroll area does not fit.
This causes the scroll up button to disappear half.

https://github.com/antoine92190/vue-advanced-chat/blob/472563d4882ea873c69f5f8ee739eee90b673228/src/lib/Room/RoomHeader/RoomHeader.scss#L5

https://github.com/antoine92190/vue-advanced-chat/blob/839359228416e1d9e51ce3d7e27c5904be5f1918/src/lib/Room/Room.scss#L36

It should be replaced by: `margin-top: 65px;`

## Steps to reproduce

 1. Go to https://antoine92190.github.io/vue-advanced-chat/
 3. Open chat 

## Expected behavior

The scrollbar should be completely visible

## Screenshots

![image](https://user-images.githubusercontent.com/2767665/195077953-1f4ba8a6-2f36-4b44-8109-e7dc4162311e.png)

## Device (please complete the following information)

- OS: Windows 10
- Browser: Chrome 105.0.5195.127
- Package version: 2.0.3

**Comment by antoine92190** [comment]
Nice catch, will fix that shortly
