### ISSUE TITLE
Send voice messages

### ISSUE THREAD

**Issue by KarimQaderi** [antoine92190/vue-advanced-chat#37]
Send voice message

**Comment by antoine92190** [comment]
That can be a nice addition indeed. Will try to implement this in the near future.
If you want this feature added sooner, do not hesitate to send a pull request!

**Comment by antoine92190** [comment]
Feature added in https://github.com/antoine92190/vue-advanced-chat/commit/a5a5a9854b558db2537220ad2f483ceb0a907803
