### ISSUE TITLE
Named Slot for message avatar

### ISSUE THREAD

**Issue by NINI1988** [antoine92190/vue-advanced-chat#372]
## Is your feature request related to a problem? Please describe

At first, thanks for this great component :-)

It would be great if the message avatar could be also exchanged like for the room avatar.
We use a component for the user avatar, so we need to replace the image in the message by our component like for the room avatar.

## Describe the solution you'd like

At a named slot for message avatar like `room-list-avatar_{{ROOM_ID}}` but for a message or per user.

So somethink like 
`message-avatar_{{MESSAGE_ID}}` or `message-avatar_{{USER_ID}}`

**Comment by antoine92190** [comment]
Indeed that makes sense to add this slot. Will do that shortly

**Comment by antoine92190** [comment]
`message-avatar_{{MESSAGE_ID}}` slot added in https://github.com/antoine92190/vue-advanced-chat/commit/48092be45e47c8b14da48e5d78f3227c5a1bffc8
