### ISSUE TITLE
The help of the contribute is outdated

### ISSUE THREAD

**Issue by NINI1988** [antoine92190/vue-advanced-chat#373]
## Describe the bug

The help of the contribute is outdated

https://github.com/antoine92190/vue-advanced-chat/blob/1550ded199104cb03d3fd43fc97460c5d081a0cd/.github/CONTRIBUTING.md?plain=1#L12

This is for the pre 2.0.0 version.

When i add the following:
```
import { register } from './../../vue-advanced-chat/src/lib/index'
register()
```
I get in the webbrowser:
```
Uncaught TypeError: Object(...) is not a function
```

## Steps to reproduce

 1. Clone https://github.com/antoine92190/vue-advanced-chat repo
 2. Follow instructions https://github.com/antoine92190/vue-advanced-chat/blob/1550ded199104cb03d3fd43fc97460c5d081a0cd/.github/CONTRIBUTING.md
 3. Clone https://github.com/antoine92190/vue-advanced-chat-sandbox repo next to it
 4. Change vue-advanced-chat-sandbox/src/App.vue with the register import
 5. Execute `npm run serve` in vue-advanced-chat-sandbox

## Device (please complete the following information)

- Package version: 2.0.3

**Comment by antoine92190** [comment]
This can only work if `vue-advanced-chat-sandbox` uses Vue 3 version.
That's why the Vue version of the `demo` folder uses Vue 3 and not Vue 2.
I will update the Vue version of the sandbox repo when Vue 2 starts becoming obsolete, but now I still find it useful to check that the library is still working fine with Vue 2.

**Comment by antoine92190** [comment]
To be able to test local change using `vue-advanced-chat-sandbox`, you can use `import { register } from './../../dist/vue-advanced-chat.es.js'` after building the component files

**Comment by antoine92190** [comment]
I also update the contributing doc: https://github.com/antoine92190/vue-advanced-chat/commit/504a818eb8adfc82ae137adc8454834ff33ed76c
