### ISSUE TITLE
How to use this in plain html?

### ISSUE THREAD

**Issue by TwT-L** [antoine92190/vue-advanced-chat#377]
## Is your feature request related to a problem? Please describe

We want to import the application directly in plain html in this way
## Describe the solution you'd like

<img width="793" alt="image" src="https://user-images.githubusercontent.com/93702913/197197892-4439c9b7-e426-49fb-aceb-701bb0509cb1.png">

**Comment by antoine92190** [comment]
I just added the CDN import installation in the readme: https://github.com/antoine92190/vue-advanced-chat/commit/6e890aa28616e203e7fc3e1ec487c0610e034377
