### ISSUE TITLE
Click on deleted message -> TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by netandreus** [antoine92190/vue-advanced-chat#378]
## Description

Error occurs when click on deleted message.

## Steps to reproduce

1. Open [Demo](https://antoine92190.github.io/vue-advanced-chat/)
2. Write message
3. Click to ```down arrow``` button on this message.
4. Select ```Delete message``` -> Message will be mark as ```deleted```.
5. Left click on this message. This error occurs:
```
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Proxy.checkType (index.c779ef9d.js:3268:2965)
    at Proxy.openTag (index.c779ef9d.js:3268:3703)
    at onClick (index.c779ef9d.js:3269:1010)
    at Dr (index.c779ef9d.js:3265:17982)
    at ni (index.c779ef9d.js:3265:18061)
    at HTMLSpanElement.n (index.c779ef9d.js:3265:60201)
KP @ index.c779ef9d.js:3265
cm @ index.c779ef9d.js:3265
Dr @ index.c779ef9d.js:3265
ni @ index.c779ef9d.js:3265
n @ index.c779ef9d.js:3265
```

## Screenshots

![click-on-deleted-message](https://user-images.githubusercontent.com/313477/197758622-197bf150-082a-43a8-80e6-9179c895a6d4.png)

## Device

- OS: macOS Monterey 12.2.1
- Browser: Brave (Chrome) v1.44.112 (Oct 12th, 2022) Chromium 106.0.5249.119 (Official Build) (x86_64)
- Package version: 2.0.3 (as it in demo app).

**Comment by antoine92190** [comment]
Thanks for pointing that out. I will fix it shortly

**Comment by netandreus** [comment]
@antoine92190 Thank you for develop this great component and for supporting it!

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/9f184343e5d932bf12864ddd3e057ff12f73f8b3
