### ISSUE TITLE
register function is not properly exported in TS definition

### ISSUE THREAD

**Issue by rdhainaut** [antoine92190/vue-advanced-chat#379]
## Describe the bug

register function is not properly exported in TS definitions
So, it s not possible to use properly register function in typescript project and vue-advanced-chat component without an compilation error...

## Steps to reproduce
I have created a repo https://github.com/rdhainaut/vue-advanced-chat-register-issue
Note: I have generated a basic vue 2 project from vue-cli (with typescript)

## Expected behavior
no error in ts project

## Fix
```ts
//vue-advanced-chat/types.index.d.ts
export function register(): void;
```

**Comment by antoine92190** [comment]
Thanks, could you open a PR with the fix?

**Comment by antoine92190** [comment]
Thx!
