### ISSUE TITLE
Add sent/seen checkmark

### ISSUE THREAD

**Issue by aubrydario** [antoine92190/vue-advanced-chat#38]
I would like to change the checkmark icon as follows:

- If the message is sent and saved to the database there should be one checkmark
- If the message is read by the other user there should be two checkmarks

This change would make it more intuitive for the user because other chat apps handle it the same (whatsapp, telegram).
In addition to that the user would know if the message was actually sent or not. Currently there is no feedback to the user.

Tell me what you think about this idea, i would be happy to make a pull request.

**Comment by antoine92190** [comment]
Sure that's a good idea. Here are my thoughts:
- Keep the logic for `seen` messages untouched
- Add a `saved` property in both `messages` prop and `lastMessage` property (inside `rooms` prop)
- Clone whatsapp UI: single grey checkmark icon when message is sent locally, double grey checkmark when message is saved, and double blue checkmark when message is `saved` and `seen`.
- The checkmark icon should be implement in both `Message.vue` and `RoomsList.Vue` (for `lastMessage`) components
- Add customisable css variables theming if necessary for icon colors, as the grey checkmark color doesn't exist yet

Feel free to make a pull request, and don't hesitate to ask me anything!

**Comment by aubrydario** [comment]
> - Clone whatsapp UI: single grey checkmark icon when message is sent locally, double grey checkmark when message is saved, and double blue checkmark when message is saved and seen.

Shouldn't it be like: singe grey checkmark when the message is saved, double grey when the other user got the message and double blue when the message is seen?

or what do you mean with "sent locally"?

**Comment by antoine92190** [comment]
> Shouldn't it be like: singe grey checkmark when the message is saved, double grey when the other user got the message and double blue when the message is seen?

Yes you're right.
So we could add `saved` and `distributed` properties in both `messages` prop and `lastMessage` properties.

**Comment by antoine92190** [comment]
`saved`: single grey checkmark
`distributed`: double grey checkmarks
`seen`: double blue checkmarks
