### ISSUE TITLE
Edit message -> Cancel -> Edit message does not working

### ISSUE THREAD

**Issue by netandreus** [antoine92190/vue-advanced-chat#380]
## Describe the bug

If we cancel message editing and try to make it again - it does not work.

## Steps to reproduce

 1. Go to [Demo](https://antoine92190.github.io/vue-advanced-chat/)
 2. Type message, click Send
 3. Click on message ```Arrow down``` button, click ```Edit message```
 4. Click on ```X``` button right to text typing input.
 5. Click on message ```Arrow down``` button, click ```Edit message``` -> no reaction on it.
 6. Now we can't edit this message

## Expected behavior

We should can edit messages twice and more times after click to ```X``` button.

## Screenshots

![after_click_to_x_button](https://user-images.githubusercontent.com/313477/198024965-9f3a9124-6920-4ca2-9eef-3890ef69a8d9.png)

## Device (please complete the following information)

- OS: MacOS Monterey
- Browser: Chrome 106.0.5249.119
- Package version: Demo

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/b5737873eaee7bc9f3e81b0d444347b09138a337
