### ISSUE TITLE
Group chat usernames not displaying

### ISSUE THREAD

**Issue by Nehemiah01** [antoine92190/vue-advanced-chat#384]
Awesome project. My problem is that I can't display the username of group participants to show with their messages despite using the username-options prop. The messages prop is the same with the one in the demo as I am using the demo code.

I even hardcoded the username in the formatMessage method in the Container.vue to a particular string but it's still not displaying. It seems like there is an unseen v-if controling the display of the username

On inspection, this is one of the messages in the chat **in the demo**
![default-code](https://user-images.githubusercontent.com/71828782/199113885-f4a2de63-afe8-4052-bdf7-1832ebefaaca.png)

While this is **my own**
![my own](https://user-images.githubusercontent.com/71828782/199114132-95bf8028-88e0-449c-a2b9-1470b169c1c5.png)

The link to repo - https://github.com/Nehemiah01/haverly
Link to probable file of interest in repo - https://github.com/Nehemiah01/haverly/blob/main/src/ChatContainer.vue
Link to website - haverly.vercel.app

**Comment by antoine92190** [comment]
The behaviour is explained in the readme:
```
username will be displayed on each message of corresponding agents if at least 3 users are in the room
```
If you want to use `username-options` it also needs to be passed as a string:
```
[username-options]="JSON.stringify(usernameOptions)"
```
If you want to show username if there are only 2 users in the room, you need to set `usernameOptions` as below:
```
usernameOptions: {minUsers: 2, currentUser: true}
```

Also, it seems that in your database, user id is stored as `id` instead of `_id`, which make your whole code unreliable

**Comment by Nehemiah01** [comment]
Thanks. I have made the correction regarding displaying the username options with the right method you sent.

But regarding the user._id; my id is still saved as _id even though there is another id property in the object database. So basically my database has two id properties.
As prood, if I use the 'user' properties object as the username you'll still get the _id property.

![user id](https://user-images.githubusercontent.com/71828782/202859536-9f9488de-155b-4d14-9c80-c7ac116d4908.png)

**Comment by antoine92190** [comment]
The senderUser is defined a few lines above:
```
// const senderUser = room.users.find(user => user._id === message.sender_id)
```

Closing this issue as the original topic was addressed.
