### ISSUE TITLE
Disable Drag and Drop 

### ISSUE THREAD

**Issue by NINI1988** [antoine92190/vue-advanced-chat#385]
## Describe the bug

Since the new version 2.0.4 it is possible to drop files, but it is also enabled when `show-files` is disabled.
So please disable drag and drop when `show-files` is disabled or add another option?
Otherwise it can happen that files can be dropped but are not handled because uploading is not implemented.

## Device (please complete the following information)

OS: Windows 10
Browser: Chrome 105.0.5195.127
Package version: 2.0.4

**Comment by antoine92190** [comment]
Indeed, I will disable drag & drop when `show-files` is false
