### ISSUE TITLE
User message avatar slot is only displayed when avatar has a value

### ISSUE THREAD

**Issue by NINI1988** [antoine92190/vue-advanced-chat#386]
## Describe the bug

https://github.com/antoine92190/vue-advanced-chat/commit/48092be45e47c8b14da48e5d78f3227c5a1bffc8#diff-f3d6d7397d0e697abbf31431377ad9b953fe312e3cf9267331d2e2984ed9b529R37-R45

We want to overwrite the message avatar slot.
But the message avatar slot is only displayed when `message.avatar` has a value, so we set it for example to `true`,
and before it is possible to overwrite the `message-avatar_` slot a request is already made to request the avatar for the background image `true`.

Our avatar is generated from multiple images, so it is not possible to just use one url in avatar.

## Proposal

Split `v-if="message.avatar && message.senderId !== currentUserId"`
into `v-if="message.senderId !== currentUserId"`
and move the first part of `v-if="message.avatar"` to the inner div.

## Device (please complete the following information)

- OS: Windows 10
- Browser: Chrome 105.0.5195.127
- Package version: 2.0.4

**Comment by antoine92190** [comment]
Yes makes sense, feel free to send a PR for that change
