### ISSUE TITLE
Add system messages

### ISSUE THREAD

**Issue by Minato-TW** [antoine92190/vue-advanced-chat#39]
Hello,

Is it possible to have "system" message types which can be used for notification purposes. For example, when a new user joins a room, we could use it to send "UserX has joined chat" or something similar. I don't see any such ability in the current Docs.

Let me know if there's some alternative to do this quickly.

Thank you!

**Comment by antoine92190** [comment]
Where would you want to display this "UserX has joined chat" message? Inside the chat feed?
Something like whatsapp when someone join or leave a group right?

**Comment by Minato-TW** [comment]
Hello,

Thanks for the quick response. Yes exactly, that's how I imagined it.

**Comment by antoine92190** [comment]
It doesn't exist yet, but I like the idea.
You can create a pull request, otherwise I will try to add this feature in the near future.

**Comment by antoine92190** [comment]
Feature added in https://github.com/antoine92190/vue-advanced-chat/commit/d131fba979419e5a02ce06545f60dc8b694af9f0
