### ISSUE TITLE
Local Emoji data

### ISSUE THREAD

**Issue by NINI1988** [antoine92190/vue-advanced-chat#391]
## Is your feature request related to a problem? Please describe

Is there a way to use a local copy of the emoji data.json instead of fetching it from https://cdn.jsdelivr.net/npm/emoji-picker-element-data@%5E1/en/emojibase/data.json?

## Describe the solution you'd like

Add a prop or any possiblility to serve a local copy of that database file.

**Comment by antoine92190** [comment]
Currently no there isn't. It's a good idea, will consider it for future updates

**Comment by antoine92190** [comment]
Oh actually you already opened a [PR](https://github.com/antoine92190/vue-advanced-chat/pull/393) for that. Will take a look
