### ISSUE TITLE
Message screen in constant loading state if you navigate between views for single room

### ISSUE THREAD

**Issue by backurdi** [antoine92190/vue-advanced-chat#398]
## Describe the bug

I have a single room chat window, on the first load the chat looks fine, but when I navigate between views the chat will go in a constant loading, even though the messages are there as you can see in the video. (I just removed the loader manually and the hidden class).

## Steps to reproduce
Have a single room chat window on a page with multiple routes.
Enter the chat page it should look fine.
Now navigate to one of the other pages and back to the chat page.
You should see the chat but you see the constant loading.

## Expected behavior

You should see the chat in a not loading state as long as the data is present.

## Screenshots

https://user-images.githubusercontent.com/25648047/203708157-b39c86bf-9cb3-401b-af25-529294d95005.mov

## Device

The issue is on all devices

**Comment by antoine92190** [comment]
Are you reseting all loading and data variables correctly when changing rooms?
It would be helpful if I could have access to your repo, or a minimal reproducible example

**Comment by backurdi** [comment]
I have just set all the loading properties of the vue-chat component to false and the loaded to true as I don't want to focus on that at the moment. And it's not switching rooms it's switching routes in the vue project, so the data that goes into the vue-chat should not have been changed?

**Comment by antoine92190** [comment]
I'm not sure, I will try to reproduce on my side first

**Comment by antoine92190** [comment]
I cannot reproduce the issue.
Can I have access to your repo, or a minimal reproducible example so I can fix the issue on my side?

**Comment by backurdi** [comment]
Sure Antoine, I will give you access.
Just change the .env.local with the .env.production data so you target my production server

**Comment by backurdi** [comment]
And you can use this test user
client1@test.com
testPass1234

**Comment by antoine92190** [comment]
I tested your repo, and you just need to follow the rules explained in the readme file: https://github.com/antoine92190/vue-advanced-chat#important-notes
```
// Follow the UI loading pattern by updating messagesLoaded prop every time a new room is fetched

fetchMessages({ room, options }) {
  this.messagesLoaded = false

  // use timeout to imitate async server fetched data
  setTimeout(() => {
    this.messages = []
    this.messagesLoaded = true
  })
}
```

**Comment by backurdi** [comment]
Amazing thank you it worked
