### ISSUE TITLE
Room name will not display

### ISSUE THREAD

**Issue by sintexph** [antoine92190/vue-advanced-chat#4]
![image](https://user-images.githubusercontent.com/47470967/78513830-dea5aa00-77e0-11ea-9c49-a17f6c27b0bb.png)
As shown in the picture above, the room name will not display
I use your sample room data as shown below.
![image](https://user-images.githubusercontent.com/47470967/78513846-f715c480-77e0-11ea-911c-6f4cfd6b8065.png)
I guess the problem lies in the CSS style
![image](https://user-images.githubusercontent.com/47470967/78514132-60e29e00-77e2-11ea-947b-fb61ae591a3f.png)

**Comment by antoine92190** [comment]
I don't have this issue when replacing the rooms prop value as in the documentation:

rooms="[
  {
    roomId: 1,
    roomName: 'Room 1',
    lastMessage: {
      content: 'Last message received',
      sender_id: 1234,
      username: 'John Doe',
      timestamp: '10:20',
      seen: false,
      new: true
    },
    users: [
      {
        _id: 1234,
        username: 'John Doe',
        status: {
          state: 'online',
          last_changed: 'today, 14:30'
        }
      },
      {
        _id: 4321,
        username: 'John Snow',
        status: {
          state: 'offline',
          last_changed: '14 July, 20:00'
        }
      }
    ],
    typingUsers: [ 4321 ]
  }
]"
```

<img width="484" alt="Screenshot 2020-04-06 at 17 32 55" src="https://user-images.githubusercontent.com/16256207/78529208-da9f7980-782c-11ea-8feb-9c5eaf8b1d33.png">

Not sure what's happening. Maybe a conflict from you css files?
I can have a look but I would need a reproducible example if you can provide one

**Comment by antoine92190** [comment]
Also, I don't see the room name in the right column header from your screenshot. So it's not just the data inside `name-container` class that is impacted, hence probably not a css issue

**Comment by antoine92190** [comment]
@sintexph Have you managed to fix sort out this issue?

**Comment by antoine92190** [comment]
@sintexph Actually you were right, there was indeed a css issue. It should be fixed now https://github.com/antoine92190/vue-advanced-chat/commit/15599887684e1c540da3c1c4be509774523ff7dc

**Comment by antoine92190** [comment]
I’m closing this issue as it should be solved now.
