### ISSUE TITLE
Issue with "vue-advanced-chat/dist/vue-advanced-chat.css"

### ISSUE THREAD

**Issue by bojarovski** [antoine92190/vue-advanced-chat#406]

**Comment by antoine92190** [comment]
You don't need to import this file. Please read the installation steps: https://github.com/antoine92190/vue-advanced-chat#usage

**Comment by bojarovski** [comment]
can u give me a hint. This is my `vue.confug.js`

![image](https://user-images.githubusercontent.com/93287601/204282326-75af1aa2-3fc7-47f9-926b-4dac9f7ec0b2.png)
