### ISSUE TITLE
replaceAll is not a function

### ISSUE THREAD

**Issue by jcardus** [antoine92190/vue-advanced-chat#407]
I'm having no text when I run this on a huwaei device in a capacitor app. I also get this error on sentry.
I suspect it's the webview in this case doesn't have replaceAll. I'm still investigating.
 
I'll fork the project to remove the replaceAll and see if it has any impact.

![imagen](https://user-images.githubusercontent.com/31902485/205049099-3fb26d80-1c4e-4633-a846-bb6442f9d0d2.png)
<img width="1439" alt="Screenshot 2022-12-01 at 12 04 47" src="https://user-images.githubusercontent.com/31902485/205049118-df756a01-e52f-4c24-9f59-7c3b3e848641.png">

**Comment by jcardus** [comment]
In the screen the chrome mobile view version is not showing, but its Chrome Mobile WebView 83.0.4103. According to [this](https://chromestatus.com/feature/6040389083463680), replaceAll is only available since 85.

**Comment by jcardus** [comment]
I can confirm that was the issue. I added this[ ](https://vanillajstoolkit.com/polyfills/stringreplaceall/) polyfill in my app and it worked.

**Comment by zslzz** [comment]
@jcardus  I have met this issue too, could you share your polyfill link? Thanks very much!

**Comment by jcardus** [comment]
hello @zslzz, here it goes:

https://github.com/fleetmap-io/driver-app/blob/a729d7f05f0de57e155100c603fa81118a74dc6f/plugins/vant.js#L21
