### ISSUE TITLE
Url in last message

### ISSUE THREAD

**Issue by NINI1988** [antoine92190/vue-advanced-chat#408]
## Describe the bug

When the last message in the room list contains an url, the text is splitted into multiple spans.

We use the following css to display at maximum 2 lines of last message text. But when the message contains a link, multiple spans are inserted and the limit to 2 lines happens for every span and not for the complete text.
```
    .vac-room-list .vac-text-last .vac-text-ellipsis,
    .vac-room-list .vac-room-name {
      -webkit-line-clamp: 2;
      display: -webkit-box;
      -webkit-box-orient: vertical;
      overflow: hidden;
      white-space: initial;
    }
```

Is there a reason why the url is packed into an own span?
It could just be displayed as normal text right?

## Steps to reproduce

 1. Go to https://antoine92190.github.io/vue-advanced-chat/
 2. Write message `Long TextLong TextLong TextLong https://www.google.com/ TextLong TextLong TextL`
 5. Apply css from above
 6. Text is not limited to 2 lines.

## Expected behavior

Should be limited to 2 lines

## Screenshots

![LastMessageLinkTooManyRows](https://user-images.githubusercontent.com/2767665/205715683-330e0de4-9333-42b3-aee2-074f2769f10d.png)

- The first room (without link) is limited to 2 rows
- The second room (with link) is not limited

## Device (please complete the following information)

- OS: Windows 11
- Browser: Firefox 105, Chrome 106
- Package version: 2.06

**Comment by antoine92190** [comment]
All strings are divided in span so the markdown and links can work. For example if you write `*bold*` the text will be shown as bold. If you have any idea to make it work feel free to share your solution here or open a PR (as long as it doesn't break other features). I'm closing this for now as your use case is too specific.
