### ISSUE TITLE
`slot` attributes are deprecated

### ISSUE THREAD

**Issue by palmtown** [antoine92190/vue-advanced-chat#412]
## Steps to reproduce

Following instructions on https://github.com/antoine92190/vue-advanced-chat to implement a the named slot message-avatar_{{MESSAGE_ID}}.  Specifically, use code below.  

Can you provide an update-to-date example of how to implement a named v-slot for message-avatar_{{MESSAGE_ID}} or any other slot that is dynamic?  

**From example at https://github.com/antoine92190/vue-advanced-chat**
`<div v-for="message in messages" :slot="'message_' + message._id">
    <div v-if="message.system">
      System message: {{ message.content }}
    </div>
    <div v-else>
      Normal message: {{ message.content }}
    </div>
  </div>`

## Expected behavior

Avatar should render component inside of v-slot.

## Device (please complete the following information)

- OS: Windows
- Browser: Chrome
- Package version: n/a

**Comment by antoine92190** [comment]
Which version of the library are you using?

**Comment by palmtown** [comment]
Hello @antoine92190 

Thanks for responding.  I am using 2.0.6.

**Comment by antoine92190** [comment]
Sorry for the late response. Here is a working example:
```
<div v-for="message in messages" :slot="'message-avatar_' + message._id" :key="message._id">
    New avatar
</div>
```
