### ISSUE TITLE
@fetch-messages This event Will be triggered twice

### ISSUE THREAD

**Issue by szwss** [antoine92190/vue-advanced-chat#419]
```
@fetch-messages="fetchMessages($event.detail[0])"
```
This event Will be triggered twice

Is there a way to solve this?

**Comment by szwss** [comment]
https://github.com/antoine92190/vue-advanced-chat/issues/313#issuecomment-1152495598

**Comment by szwss** [comment]
![图片](https://user-images.githubusercontent.com/584808/215495603-cba7b8a1-e21a-4bf6-b664-4403e218c341.png)

```
rest : true
```

Is this normal?

**Comment by julienchabanon** [comment]
I am having this issue too

**Comment by sunprawn** [comment]
Could you let me know if you updated the room-id prop? It will trigger a fetch-message

**Comment by szwss** [comment]
> Could you let me know if you updated the room-id prop? It will trigger a fetch-message

Yes, I specified currentRoom in the fetchMessage method,Below is my code:

my template
```
<vue-advanced-chat
              :room-id="currentRoom ? currentRoom.roomId : null"
              @fetch-messages="fetchMessages($event.detail[0])"
...
>
```

my data
```
data() {
        return {
            currentRoom: null,
...
        }
```

my  fetchMessages method
```
            console.log('fetchMessages room', room)
            console.log('fetchMessages options', options)

            if (this.currentRoom.roomId !== room.roomId) {
                this.currentRoom = room
            }
...
```
Because I sometimes need to know the current room and room ID somewhere else, I can't find any way to get the current room ID, so I can only change it in the fetchMessages method

**Comment by sunprawn** [comment]
That's why it triggers twice. Whenever you update the `room-id` prop, it fires the `fetch-message` event. 

As far as I know, you don't have the change `room-id` when you switch chat room

**Comment by szwss** [comment]
If I don't set currentRoomId, when there are multiple chat rooms, I am in chat room A, but at this time chat B has new messages, obviously I can't change the current this.messages because it belongs to chat room A. It's okay to need the current room information at this point, but I can't find it

**Comment by puzzle9** [comment]
> If I don't set currentRoomId, when there are multiple chat rooms, I am in chat room A, but at this time chat B has new messages, obviously I can't change the current this.messages because it belongs to chat room A.
> 
> At this point, it's okay if I get the current room information, but I haven't found a way to do it

Save `room-id` separately
Determine the reset parameter under `@fetch-messages`
Then if it is the same as the current `room-id`, return

**Comment by antoine92190** [comment]
Closing this as it seems to be solved, please reopen otherwise and explain clearly what is not working
