### ISSUE TITLE
Join and leave chat rooms && alert for unread messages

### ISSUE THREAD

**Issue by szwss** [antoine92190/vue-advanced-chat#420]
I'm using Laravel WebSocket as a backend service 
Laravel-echo serves as a front-end service 
They have several characteristics 
1. Online channel, this is only whether the user is online, and entering the chat room has nothing to do with it, 
document: https://laravel.com/docs/6.x/broadcasting#broadcasting-to-presence-channels 
2. joining the chat room, this is the event of entering the chat room, at this time you can know who is in the current chat room, this is different from the first point, the first point only shows that this user is online, but not he is in this chat room 
3. leaving the chat room, this is the opposite of the second point 
But currently there is only one online function, and it is not possible to determine whether the user is in the current chat room. 

```
Echo.join(`chat.${roomId}`)
    .here((users) => {
        //
    })
    .joining((user) => {
        console.log(user.name);
    })
    .leaving((user) => {
        console.log(user.name);
    });
```

Do you consider adding the function of entering and leaving the chat room? 

Another question: 
When there are multiple chat rooms, if I am viewing chat room B and chat room A receives a message, 
I cannot directly display a special mark on the room list to remind users that there are new unread messages in chat room A

Can you add this functionality?

**Comment by antoine92190** [comment]
- You can update the `joining` and `leaving` status of the current user when changing a room for example, using `fetch-messages` event. You can update the `here` status when a user arrives on you website.
- Actually the username should be displayed as bold if there are new messages. You can also use `unreadCount` inside the `rooms prop` to show unread message counter

**Comment by szwss** [comment]
thank you
