### ISSUE TITLE
Cannot display date time stamp in american format 

### ISSUE THREAD

**Issue by avenuesrini** [antoine92190/vue-advanced-chat#426]
## Describe the bug

Right now, the date and time stamp is displayed in international format .. DD/MM/YY - but unfortunately Americans are in reverse. And I don;'t think there is a way to change it. 

## Steps to reproduce

go to any chat room and see the date/time stamp 

Example:
![image](https://user-images.githubusercontent.com/53194512/217910393-1ba2a17f-5710-4bb5-b377-ef327f811655.png)

## Expected behavior

The ability to display **Feb 6, 23 2:20 PM**  so its globally compatible 

## Screenshots

![image](https://user-images.githubusercontent.com/53194512/217910564-de727041-a996-4a93-b059-640c28b7d98a.png)

## Device (please complete the following information)

Mobile App - across all platforms

**Comment by antoine92190** [comment]
You can set timestamp in rooms > lastMessage and messages props however you want, it doesn't need to be a date object, it can be a string.
So you can format the date on your side and pass timestamp: 'Feb 6, 2:20 PM'

**Comment by antoine92190** [comment]
Closing this, please reopen if you still have an issue
