### ISSUE TITLE
Does this tool support hiding the left rooms sidebar using a params called `show-rooms`(Boolean)

### ISSUE THREAD

**Issue by dongrixinyu** [antoine92190/vue-advanced-chat#428]
I wanna  vue-advanded-chat provide only one room for the user to use such as ChatGPT. So there is no need to load the left room sidebar.

I am curious that if this tool can provide a param that controls to show or hide the left room sidebar. And I recommend to call id `show-rooms`

![image](https://user-images.githubusercontent.com/27001062/218627101-70c8c1f0-eb24-4cf3-8884-a830adb66ae3.png)

The red rectangle should be deleted when set `show-rooms="false"`

Thanks!

**Comment by dongrixinyu** [comment]
Sorry, I have found `rooms-list-opened` params. But I am still confused that the left-top button could been disabled?

![image](https://user-images.githubusercontent.com/27001062/218629656-1076adb9-6824-4ff6-bafa-b4fb64b8c683.png)

**Comment by antoine92190** [comment]
You can use `single-room` param instead:
> `single-room` can be used if you never want to show the rooms list on the left. You still need to pass the rooms prop as an array with a single element.

**Comment by seyfer** [comment]
> You can use single-room param instead:

When using single room, we miss `typing` indicator, as it is shown only in the rooms list.
When using `single-room` mode, typing should be shown in the chat or in the chat header.
