### ISSUE TITLE
Two questions about displaying loading icons. One is to load the room and the other is to load the message 

### ISSUE THREAD

**Issue by szwss** [antoine92190/vue-advanced-chat#429]
# First case: 
```
this.room: [], 
roomsLoaded: false, 
loadingRooms: true, 
```
when I add a room to Rooms 
```
const _rooms = [... this.rooms] 
_rooms.push(room) 
this.rooms = _rooms
```
The rooms list is triggered to appear with a loading icon And it keeps showing and doesn't go away 

# Second case: 
There is a room in the normal display, including this.messages 
I add a room like above 
```
const _rooms = [... this.rooms] 
_rooms.push(room) 
this.rooms = _rooms 
```
The messages of the current room will appear with a loading icon,
Through the console can see that fetcehMessages is triggered, 
but I didn't change the current room at this time, just added a room to the room list. 

Both of the above cases are problems caused by the add room to this.rooms

**Comment by antoine92190** [comment]
You can set `loading-rooms` prop to `false` when your rooms are loaded.

**Comment by szwss** [comment]
thank you
