### ISSUE TITLE
Any idea how we can change new message color. It show as bold and i need change also color for clarify.  

### ISSUE THREAD

**Issue by ataryandev** [antoine92190/vue-advanced-chat#432]

**Comment by antoine92190** [comment]
You can override css using shadow DOM:
```
Shadow DOM
CSS classes cannot be simply overridden anymore. You can still use CSS variables, and if needed you can override CSS classes like this:

const style = document.createElement('style')
style.innerHTML = styles
this.$refs.chatWindow.shadowRoot.appendChild(style)
```

**Comment by antoine92190** [comment]
Closing this, please reopen if you still have an issue

**Comment by khanhzizu** [comment]
> Closing this, please reopen if you still have an issue

Hi Antoine, can you show me where to write the code to edit the css? I write it in Created(), then console log "can not read properties of undefined (reading 'shadowRoot')"

**Comment by antoine92190** [comment]
Have you added `chatWindow` ref to the chat window component?
Please refer to the demo code, everything is there: https://github.com/antoine92190/vue-advanced-chat/blob/master/demo/src/ChatContainer.vue#L33

**Comment by khanhzizu** [comment]
> Have you added `chatWindow` ref to the chat window component? Please refer to the demo code, everything is there: https://github.com/antoine92190/vue-advanced-chat/blob/master/demo/src/ChatContainer.vue#L33

It worked. Thank you very much

**Comment by ataryandev** [comment]
Here is my solution
    ```
:deep(.vac-message-new) {
      animation: new-message 1s infinite;
      font-size: 14px;
      font-weight: 700;

      @keyframes new-message {
        50% {
          color: #f00;
        }
      }
    }
```

**Comment by seyfer** [comment]
It worked for me as well, but since I use webpack and typescript, I was getting Module object on scss import instead of CSS text.

Solved by altering webpack import behavior.

```
// eslint-disable-next-line import/no-webpack-loader-syntax,import/no-named-default
import { default as ChatCss } from '!css-loader!sass-loader!./chat-shadow-dom.scss';

// have to alter webpack behavior to make it load text, not Module object
// @see https://stackoverflow.com/a/66539355/1074834

const ChatCssString = ChatCss.toString();

export default ChatCssString;
```

then use ChatCssString to add 

```
 const addChatShadowDomCss = async () => {
    const style = document.createElement('style');
    style.innerHTML = ChatCssString;
    chatWindow.value.shadowRoot.appendChild(style);
  };
```

**Comment by reslear** [comment]
better solution https://github.com/antoine92190/vue-advanced-chat/issues/453#issuecomment-1638289893

**Comment by seyfer** [comment]
@reslear as to me it is not better, as I want my styles to be SCSS and loaded from a file

**Comment by elfaz2** [comment]
`
<script setup type="module">
const vacRef = ref(null)
const addCustomStyle = () => {
    if (!vacRef.value) return
    const style = document.createElement('style')
    style.textContent = '.vac-message-wrapper .vac-message-current{background: linear-gradient(90deg, #BD42BB 0%, #663E97 100%) !important; color: white} .vac-message-actions-wrapper .vac-options-me {background: transparent;}'
    vacRef.value.shadowRoot.appendChild(style)
}
onMounted(() => { addCustomStyle() });
</script>
<template>
<vue-advanced-chat
            ref="vacRef"/>
</template>
`
