### ISSUE TITLE
Further customization

### ISSUE THREAD

**Issue by aubrydario** [antoine92190/vue-advanced-chat#44]
The customization of the component is currently very limited, mainly colors can be changed. I want to go one step further and make the component more adaptable to meet the users needs.

- Customizable icons
- More opportunities to change the presentation and styling

Here is an example screenshot of how I imagine the component could look like when customized:

![Screenshot from 2020-11-16 11-16-00](https://user-images.githubusercontent.com/26509954/99240744-3687a300-27fd-11eb-95bb-9017916bd314.png)

What do you think about this idea? I would be very happy to make a pull request.

**Comment by antoine92190** [comment]
Yes I've been meaning to add more customisation but didn't have time for it.
I fully agree for icons, we could add more named slots as I did for `rooms-header`.

What did you have in mind for further customisation ? Add more css variables ?

**Comment by aubrydario** [comment]
I thought about adding named slots to the room list item and to the room header. Therefor the user has full control over the styling and presentation.

**Comment by antoine92190** [comment]
Yes sounds good.
The more named slots the better :)
We could also add one for messages box.
