### ISSUE TITLE
user-tags-enabled not working

### ISSUE THREAD

**Issue by CRC32EX** [antoine92190/vue-advanced-chat#440]
## Describe the bug
`user-tags-enabled` not working

## Steps to reproduce
https://stackblitz.com/edit/vitejs-vite-itzwau?file=src%2FApp.vue&terminal=dev

## Current behavior
![image](https://user-images.githubusercontent.com/25629617/227502109-f80025d1-048a-4c01-bf34-8cf3d4d7ead1.png)
- User tag (h1) enabled
- User style(color: red) enabled

## Expected behavior
![image](https://user-images.githubusercontent.com/25629617/227502067-2a6811bf-886c-4d95-ba31-0156df1699e9.png)

- User tag (h1) disabled
- User style(color: red) disabled

## Screenshots
![image](https://user-images.githubusercontent.com/25629617/227501595-023aeff2-fe97-4269-9076-ba5ef192f89d.png)

## Device (please complete the following information)
- OS: Windows 11
- Browser: Chrome 111
- Package version: 2.0.7

**Comment by antoine92190** [comment]
`user-tags-enabled` is not used for that. It's used to be able to tag users when typing `@antoine` for example.
But it can be an interesting new prop to add, to be able to disable HTML formatting in message

**Comment by CRC32EX** [comment]
> But it can be an interesting new prop to add, to be able to disable HTML formatting in message

Yes, i agree too.
Because using slot `message_{{MESSAGE_ID}}` is breaks UI styles.
Add disable HTML prop is very convenient, i think.

I close this issue.
I needed to hurry, I solve this issue escape string server side.
