### ISSUE TITLE
Pin messages

### ISSUE THREAD

**Issue by arufonsekun** [antoine92190/vue-advanced-chat#446]
Hello, first of all congratulations for this awesome lib.

It would be great to be able to pin **messages** .
If there's a way to improvise this behaviour (something similar to pin/fav a room) please let me know.

Best regards.

**Comment by antoine92190** [comment]
You can probably use `message-actions` to add a `Favorite` option, then use pinned messages DOM id or slots to have a specific display for those messages

**Comment by antoine92190** [comment]
@arufonsekun Please let me know if this meets your need, or if it makes sense to create a specific feature for that.

**Comment by antoine92190** [comment]
Closing this, if someone wants to have this feature built-in, please vote on the first comment with a 👍

**Comment by arufonsekun** [comment]
> @arufonsekun Please let me know if this meets your need, or if it makes sense to create a specific feature for that.

Hallo @antoine92190, as you suggested I added a `Pin` option on `message-actions`. However I'm having some trouble to change `message-actions` array in order to replace `Pin` with `Unpin` option, any ideia how I could manage that?

**Comment by arufonsekun** [comment]
> Is there any event that I could listen when message option dropdown is open?

I was checking the implementation on `MessageActions` and found an event that could help me:
https://github.com/antoine92190/vue-advanced-chat/blob/7a30bd54d6175c21695de6fd5298ba53773c37dd/src/lib/Room/RoomMessage/MessageActions/MessageActions.vue#L164
Listen to this event on chat root component would be amazing. Is that possible @antoine92190?

**Comment by jeanchilger** [comment]
> You can probably use `message-actions` to add a `Favorite` option, then use pinned messages DOM id or slots to have a specific display for those messages

I am implementing the same feature and this tip worked well.

But I'm facing the same problem reported by @arufonsekun in replacing `Pin` with `Unpin` on `message-actions`.

**Comment by arufonsekun** [comment]
> https://github.com/antoine92190/vue-advanced-chat/blob/7a30bd54d6175c21695de6fd5298ba53773c37dd/src/lib/Room/RoomMessage/MessageActions/MessageActions.vue#L164
> 
> 
> Listen to this event on chat root component would be amazing. Is it possible to make this event available @antoine92190?

I can make the changes and pull request the repo if it's all right to you @antoine92190?
