### ISSUE TITLE
Multiple rooms not working

### ISSUE THREAD

**Issue by fabriguespe** [antoine92190/vue-advanced-chat#447]
Doesnt work. Try with 2 rooms and different messages in both. Will load for ever. doesnt work

rooms: [
				{
					roomId: '1',
					roomName: 'Room 1',
					avatar: 'https://66.media.tumblr.com/avatar_c6a8eae4303e_512.pnj'
				},
{
					roomId: '2',
					roomName: 'Room 2',
					avatar: 'https://66.media.tumblr.com/avatar_c6a8eae4303e_512.pnj'
				}
		],

**Comment by antoine92190** [comment]
Have you set `messagesLoaded` to `false` after your rooms are loaded?

**Comment by khanhzizu** [comment]
> Have you set `messagesLoaded` to `false` after your rooms are loaded?

Hi Antoine, can you show me where to write the code to edit the css? I write it in Created() like this: 
const style = document.createElement('style')
style.innerHTML = '.vac-room-header { display: none !important; }'
this.$refs.chatWindow.shadowRoot.appendChild(style).

Console log show "can not read properties of undefined (reading 'shadowRoot')"

**Comment by antoine92190** [comment]
Closing this as using `messagesLoaded ` correctly should work. Please reopen otherwise.
