### ISSUE TITLE
How to refresh room list

### ISSUE THREAD

**Issue by deepweller** [antoine92190/vue-advanced-chat#45]
Hi, I have a question.

How do I refresh room list? I added refresh room buttion in slot area.
And when I button click, reset data like below.
```
        this.me = {}
        this.currentUserId = ''
        this.rooms = []
        this.currentRoom = {}
        this.currentRoomId = ''
        this.messages = []
        this.messagesLoaded = false
```
But seleted room was not changed to empty. (It still remains previous seleted room.)
![스크린샷 2020-11-17 오후 1 50 09](https://user-images.githubusercontent.com/31335415/99348106-15e24a80-28dc-11eb-8884-0bd55f953c17.png)

Can I reset room data or refresh room list?

Thank you.

**Comment by antoine92190** [comment]
I believe you need to set `this.loadingRooms = true`, fetch your lists, then `this.loadingRooms = false`

**Comment by deepweller** [comment]
RoomList area loading is works well.
But room area is still loading...
I sent screen record file to email. (yellow button is refresh room buttion.)

**Comment by antoine92190** [comment]
Maybe this can help: https://github.com/antoine92190/vue-advanced-chat/issues/40#issuecomment-723100859

**Comment by deepweller** [comment]
Actually I already changed messageLoaded props.
I think room data is not initialized when rooms props was setted empty array [].(like above image)

**Comment by antoine92190** [comment]
Would you be able to share here your full component code snippet so I can reproduce the issue?

**Comment by deepweller** [comment]
I found issue. The cause of the issue is that I put them in rooms prop sequentially when I get room list to server.
I changed it to put it at once.
before
```javascript
    getRooms() {
        this.rooms = []
        getChannels().then(async res => {
          for (let i = 0; i < res.channels.length; i++) {
            if (!res.channels[i].name.startsWith('chat_')) {
              continue
            }

            let members = await this.getChannelMembers(res.channels[i]._id);

            const room = {
              roomId: res.channels[i]._id,
              roomName: res.channels[i].name,
              users: members.members,
              type: 'channel',
              offset: 0,
              unreadCount: 0,
            }

            await this.subRoom(room)
            this.rooms.push(room)
          }
        })
      }
```
after
```javascript
    getRooms() {
        let rooms = []
        getChannels().then(async res => {
          for (let i = 0; i < res.channels.length; i++) {
            if (!res.channels[i].name.startsWith('chat_')) {
              continue
            }

            let members = await this.getChannelMembers(res.channels[i]._id);

            const room = {
              roomId: res.channels[i]._id,
              roomName: res.channels[i].name,
              users: members.members,
              type: 'channel',
              offset: 0,
              unreadCount: 0,
            }

            await this.subRoom(room)
            rooms.push(room)
          }
          this.rooms = rooms
        })
      }
```

**Comment by antoine92190** [comment]
Ok cool. I will have a look and check if I can allow the first method to work as well.

**Comment by antoine92190** [comment]
Actually, I will not change the current behaviour as it may lead to performance issues. Instead, I add guidelines in the readme: DON'T DO THIS
