### ISSUE TITLE
Infinite loader displayed when `messagesLoaded` is `true`

### ISSUE THREAD

**Issue by despatates** [antoine92190/vue-advanced-chat#455]
First, thank you for your amazing plugin!

## Describe the bug

When the server returns an empty list of messages, the message window shows a message _No messages_ for the first room, but shows an infinite loader for the others.

## Steps to reproduce

Here is a repo to reproduce the issue: https://github.com/despatates/vue-advanced-chat-sandbox

Starting with `messages = []` and `messagesLoaded = false`.
I simulate an empty response from the server by setting `messagesLoaded = true`.
When I select another chat room, the infinite loader remains visible.

## Expected behavior

The message window should display _No messages_ if the server returns an empty list of messages.

## Screenshots
![vue-advanced-chat-sandbox](https://github.com/antoine92190/vue-advanced-chat/assets/3403829/546eff5f-ca8b-4a6d-9304-6cdfff04630a)

## Device (please complete the following information)

- OS: Fedora 38
- Browser: Chrome 113.0.5672.126, Firefox 113.0.1
- Package version: 2.0.7

**Comment by despatates** [comment]
Hmm, I think I found the solution by writing this issue.

`messagesLoaded` must be reset to `false` before requesting the messages for the newly selected room. Thus it will reset the "loading state" of the message window. And eventually set it back to `true` when the messages are loaded.

Am I right?

**Comment by antoine92190** [comment]
Yep that's exactly right
