### ISSUE TITLE
Please provide the corrent data format

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#46]
In the document, the room props
  timestamp: '10:20',
   date: 123242424,

the timestamp looks like a time instead of unix timestamp, while the date looks like a timestamp. is the date is valid php date like "2020-10-12 10:30", please provide the correct data format even for dummy data. or specify the props types like string or unix timestamp. thanks.

**Comment by antoine92190** [comment]
`date` and `timestamp` values are plain strings so you have full flexibility over it.
But you are right, I will precise it in the README.

**Comment by tingan** [comment]
Hi,
it's not about string, yes, they all can be string, but string like '123344' can be timestamp, while string like '2020-11-20 10:30' is a date string. that's different.

**Comment by antoine92190** [comment]
I don't understand the question/requirement then...

**Comment by tingan** [comment]
Hi,
in document, it say If you set a date to lastMessage property, your rooms will be ordered using this date value. If vue-advanced-chat will order the rooms by date, then i guess the date should be one of supported format. like order by timestamp or order by datetime. but the date: 123242424, it looks like the date should be timestamp? or does the order (sorting) support both timestamp and datetime?

**Comment by antoine92190** [comment]
Indeed.
- `timestamp` is a normal string and will be only used for UI display: `Today, 10:45` for example
- `date` can actually be anything sortable. Using a timestamp here will work fine as older timestamps are smaller than most recent ones. Here is the code for sorting the date: https://github.com/antoine92190/vue-advanced-chat/blob/master/src/ChatWindow/ChatWindow.vue#L190

**Comment by antoine92190** [comment]
I updated the readme: https://github.com/antoine92190/vue-advanced-chat/commit/3d1553474da43cdb0f53c7acf49930c75b4621b8
