### ISSUE TITLE
Cannot send file in sendMessage by axios post

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#49]
Hi,
in the sendMessage method, 
sendMessage({roomId, content, file, replyMessage}) {
let data = new FormData()
                data.append('file', file)
                axios({
                    method: 'post',
                    url: '/add-message',
                    data: data,
                    headers: {
                        'Content-Type' : 'multipart/form-data'
                    }
                })

but in the server side, i cannot get the file from the request. Is anything wrong in the above code? thanks.

**Comment by aubrydario** [comment]
Try this out:  `data.append('file', file.blob)`

**Comment by tingan** [comment]
it works! Thank you.
