### ISSUE TITLE
Where to provide user photo

### ISSUE THREAD

**Issue by saumyasinghal747** [antoine92190/vue-advanced-chat#50]
Hello,

I'm trying to make something exactly the same as your real-world example using firebase google authentication. What I can't figure out is where to provide the component the photo URL of the user, or how to change the default?

Thank you!

**Comment by saumyasinghal747** [comment]
I figured it out by reading the source code that a user can have a property `avatar`. Maybe add this to the docs?

**Comment by saumyasinghal747** [comment]
Okay, I won't close actually so that you can add to docs.

**Comment by antoine92190** [comment]
Yes indeed. Thanks!
https://github.com/antoine92190/vue-advanced-chat/commit/adea041cbff1505e2e3855439e1fec07b2170dc1
