### ISSUE TITLE
typingUsers not refresh UI with dynamic data

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#52]
## Describe the bug
typingUsers works with static data. but When I am using websocket's whisper to get the dynamic typingUsers id and update room's typingUsers array, the UI not reflect the change, or UI doesn't show typing at all.

**Comment by antoine92190** [comment]
Have you tried to update `typingUsers` array as in the demo?
```
query.onSnapshot(rooms => {
	rooms.forEach(room => {
		const foundRoom = this.rooms.find(r => r.roomId === room.id)
		if (foundRoom) foundRoom.typingUsers = room.data().typingUsers
	})
})
```

**Comment by tingan** [comment]
hi,
`
 .listenForWhisper('typing', ({id, roomId}) => {
             
                        for (let i = 0; i < this.rooms.length; i++) {
                            if (this.rooms[i]['roomId'] == roomId) {
                                // push typing user id to room's typingUsers, but it not reflect in UI.
                                if (!this.rooms[i]['typingUsers'].includes(id)) {
                                    this.rooms[i]['typingUsers'].push(id)
                                }
`
the rooms (data property) are axios fetched from backend and i update the rooms typingUsers array , but it not works. but i didn't use firestore.

**Comment by tingan** [comment]
Hi, i find the typing for demo site https://antoine92190.github.io/vue-advanced-chat/ also not working.

**Comment by antoine92190** [comment]
The typing is working on my side.
Your code above is wrong, please use the logic I sent you.
```
for (let i = 0; i < this.rooms.length; i++) {
    const foundRoom = this.rooms.find(r => r.roomId === this.rooms[i]['roomId'])
    if (foundRoom) foundRoom.typingUsers = [...this.rooms[i]['typingUsers'], id]
}
```

**Comment by antoine92190** [comment]
I added some notes in the readme that should be helpful for that case: https://github.com/antoine92190/vue-advanced-chat#important-notes

**Comment by tingan** [comment]
Hi,
I tried 
this.rooms[i]['typingUsers'] = [...this.rooms[i].typingUsers, id]
OR
this.$set(this.rooms[i],'typingUsers', [id])`
`
None of it work.

**Comment by antoine92190** [comment]
Have you tried:
```
for (let i = 0; i < this.rooms.length; i++) {
    this.rooms[i].typingUsers = [...this.rooms[i].typingUsers, id]
    this.$set(this.rooms, i, room)
}
```

**Comment by tingan** [comment]
hi,
` for (let j = 0; j < this.rooms[i]['users'].length; j++) {
                                    if (this.rooms[i]['users'][j]['_id'] == id) {
                                        if (!this.typingUsers.includes(this.rooms[i]['users'][j]['username'])) {
                                            this.typingUsers.push(this.rooms[i]['users'][j]['username'])
                                        }
                                    }
                                }`
Currently i uses another way, by adding a div typing indicator bar on top of chat window, it works. but it's not elegant way. as a div typing indicator bar is not part of chat window itself.  I created a typingUsers array in data.(which is not part of rooms).

**Comment by antoine92190** [comment]
Can I have access to your repo or a minimal reproducible example?

**Comment by tingan** [comment]
Hi, it works with !
`
 this.rooms[i]['typingUsers'] = [...this.rooms[i].typingUsers, id]
`
and by setTimeout i can clear the is typing.

for online/offline
`
 this.rooms[0]['users'][0]['status']['state'] = 'online'
`
it works for online/offline, i just hard update the room user state, UI reflect the change. 
I will close the issue. thanks for help!

**Comment by tingan** [comment]
But i have another question,

How can i translate the words" is typing" for other languages. the i18n issue, thx

**Comment by antoine92190** [comment]
You can use `textMessages` prop:
```
textMessages="{
	IS_TYPING: 'is writing...'
}"
```

**Comment by tingan** [comment]
Hi,
thx, i found the src/locales/index.js has the list of strings. otherwise it's difficult to guess, IS_TYPING why not IS_WRITING. hehe.
