### ISSUE TITLE
add more detail information about the room in the right chat window Room name bar

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#53]
Hi,

Vue-advanced-chat has left side chat room list and right side chat main panel. Current the left side chat room name and right side chat main panel's chat room name show exact the same information. But as right side chat main panel has more space, i want to add more detailed information of the chat room . E.g. left side chat room is Leia (person name), but in right side chat room name, can I add extra information such as the short introduction of Leia. (Leia's profile ). as sometimes, many people has same names, a profile introduction might be useful to differentiate who is who. thanks.

**Comment by tingan** [comment]
Hi,
it seems room-header slot can do this. but i don't know how to do it. can you give some code snippet example for it. the slot part document is missing for details. thx.

**Comment by antoine92190** [comment]
https://github.com/antoine92190/vue-advanced-chat#named-slots
On the first line you have the example:
```
<template v-slot:rooms-header>
	This is the new rooms header
</template>
```

**Comment by tingan** [comment]
hi, thx
I roughly figure it out, 
<div slot="room-header" slot-scope="{ room, typingUsers, userStatus }">
</div>

**Comment by tingan** [comment]
Hi,
`
 <div slot="room-header" slot-scope="{ room, typingUsers, userStatus }">
               {{room.roomName}}
            </div>
`
with above code, i can add custom room name information, but the original room-options, menu-icon, toggle-icon are missing, I don't want to change those room-options, men-icons, how can i get them back? thanks.!

**Comment by antoine92190** [comment]
If you decide to use `room-header`, you cannot retrieve room default options.
I haven't implemented the slots feature myself, so I am not very familiar with it.
I understand the limitations of the current implementation, I will work on it very soon.

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/2cfe6bbf731182a963bc9bb2acd041dda69a1447
You can now use `room-header-info` slot.

**Comment by tingan** [comment]
thx, really wonderful fix.
