### ISSUE TITLE
roomInfo event 's room undefined

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#54]
`
<chat-window
...
 @roomInfo="roomInfo"
>
methods: {
   roomInfo({room}) {
                console.log(room)
            },
room undefined

`
although there is a workaround to get the room by this.selectedRoom.

**Comment by antoine92190** [comment]
Right, there is an error in readme. It should be:
```
roomInfo(room) {
  console.log(room)
}
```
