### ISSUE TITLE
LAST_SEEN is translated but not reflect on UI

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#55]
HI,
I translated all the textMessages into another languages, UI show the other translation correctly. However, in the right chat panel top bar, the 'last seen 2020-11-28 22:45:01' still show the english. Is it a bug? thx.

**Comment by antoine92190** [comment]
I don't have this issue with `:textMessages="{ LAST_SEEN: 'test' }"`

**Comment by tingan** [comment]
hi,
it's my bad, the reason is 'last seen ' has a space after the word 'seen' , i miss the space, which cause the string cannot be found.
