### ISSUE TITLE
Room list is not sorted correctly with empty room 

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#56]
Hi,
i have three chat rooms. two are empty room(without messages and last message). all rooms in DB, the last_message is null. However last_message is calculated in client js side. one room has last message date '2020-11-28 10:38', while two other empty rooms's last message is undefined. but the empty room is show first in the room list. is it possible to improve if last message is null or undefined (empty rooms), then the empty rooms show after the room which has last message date. thx.

**Comment by antoine92190** [comment]
This should already be the case, and it's working on my side.
Please share some code when opening an issue, otherwise I cannot help.

**Comment by tingan** [comment]
Hi,
the code wont help, as it's too much code. but anyway i have figured it out, as room will sort by last_message's date field. if last_message is undefined or null, then it doesn't have the date field, which cause the ChatWindow.vue's sorting code fails. So the solution is just to check if the message (last message) is null or undefined. if it's , then return:
`
 return {
                        content: '',
                        date: '',
                    }
`
So it works now. thx.
