### ISSUE TITLE
Closing chat window after leaving a room

### ISSUE THREAD

**Issue by zeineb89** [antoine92190/vue-advanced-chat#59]
## Describe the bug
the chat window is kept visible even when the user leaves the room.
I choose to use only the compact display mode (either the rooms list or the messages).
In the demo example, I found that to go back to the list of rooms you empty and refill the list again (by calling fetchRooms() after deleteRoom()), but in the case of the last room, the list remains empty, as a consequence the display stays in messages.
## Expected behavior
return to the rooms list after leaving the room in any case
## Screenshots

![before leaving a room](https://user-images.githubusercontent.com/29895031/100617904-65cd0280-331b-11eb-9d4f-c927fcb4cc08.PNG)
![after leaving a room](https://user-images.githubusercontent.com/29895031/100617914-68c7f300-331b-11eb-904e-53d4e4c0398c.PNG)

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/ac9226317eb1d906fafc4bd302cba7294bf5c9f0

**Comment by antoine92190** [comment]
Actually to go back to rooms in any case, I need to do:
```
if (
	!newVal[0] ||
	!newVal.find(room => room.roomId === this.room.roomId)
) {
	this.showRoomsList = true
}
```
But it throws an error with the demo code, so I will implement a better fix soon

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/ea10cbd6d99c75f700dace9042bb3ad8c2f25e12
