### ISSUE TITLE
If new Created room is also the current selected room, send message will not show up

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#62]
Hi,
if I create a new room and the new room is also the only one room or the current selected room. then send new message will show on other's chat window except show on the writer's own chat window. So the writer has to either refresh the page or click another room and then click the new created room again (to force fetchMessage twice).

**Comment by tingan** [comment]
solved, 
`
if (!message.timestamp) return`
`
instead of return, return message.

**Comment by antoine92190** [comment]
@tingan Please open an issue only if the bug is from the chat component itself, not with your own code, and after testing it thoroughly. Otherwise the issue history is full of non relevant posts.
