### ISSUE TITLE
Seems a typo in editMessage function demo

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#64]
in the ChatWindow.vue, the editMessage function as fllow
`
async editMessage({ messageId, newContent, roomId, file }) {
			const newMessage = { edited: new Date() }
			newMessage.content = newContent

			if (file) {
				newMessage.file = {
					name: file.name,
					size: file.size,
					type: file.type,
					url: file.url || file.localUrl
				}
				if (file.audio) {
					message.file.audio = true
					message.file.duration = file.duration
				}
			} else {
				newMessage.file = deleteDbField
			}

			await messagesRef(roomId)
				.doc(messageId)
				.update(newMessage)
		},
`
the message.file.audio = true seems like a typo, should be newMessage.file.audio, as it make no sense. 
also for `  const newMessage = { edited: new Date() }`
does the edited field is used for sorting or any UI change?

**Comment by antoine92190** [comment]
Yes you are right, I will fix it.
`const newMessage = { edited: new Date() }` is not used for any UI change.
I just thought it was more useful to have the date in edited property instead of `true`, so in the future I can leverage that if needed.

**Comment by antoine92190** [comment]
Fixed https://github.com/antoine92190/vue-advanced-chat/commit/3e5bd844c63c20539497701ae620cada9903bdaf
