### ISSUE TITLE
How to control which room is selected for first time

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#67]
Hi,
I found my room list always the second room is selected for first time or refresh page. How to control fetchMessage({room, options})'s room parameter? or how to control which room is fetching messages for first time. Thanks.

**Comment by antoine92190** [comment]
You can use `roomId` prop.

**Comment by rancou** [comment]
> You can use `roomId` prop.

When on mobile, setting `roomId` does not seem to open the selected room. Any solution?

**Comment by antoine92190** [comment]
Indeed, I don't think that's possible to enter a room on mobile with `roomId`.
I will fix that soon.

**Comment by antoine92190** [comment]
@rancou Actually, setting `roomId` does automatically change the selected room on both web and mobile on my side.
Please share your component code snippet so I can reproduce your issue.

**Comment by rancou** [comment]
> @rancou Actually, setting `roomId` does automatically change the selected room on both web and mobile on my side.
> Please share your component code snippet so I can reproduce your issue.

Basically, I tried to set `roomId` when its first loaded. It kinda works now if I wrap it a `setTimeout`.
