### ISSUE TITLE
How to display the name of the person sending the message.

### ISSUE THREAD

**Issue by AlandEr2612** [antoine92190/vue-advanced-chat#68]
![image](https://user-images.githubusercontent.com/9408682/101173756-f43dce80-3610-11eb-9cab-19a71140ab32.png)

My setting is "singleRoom" = true

The room is a dynamic chat group, thats is, x users can send a message in any moment and i need identify who person send the message.

**Comment by antoine92190** [comment]
This should answer your question: https://github.com/antoine92190/vue-advanced-chat/issues/9#issuecomment-626056298
