### ISSUE TITLE
Keep device keyboard opened after sending message

### ISSUE THREAD

**Issue by antoine92190** [antoine92190/vue-advanced-chat#7]
On mobile browsers, keyboard closes when a message is sent.
A better solution is to keep keyboard opened and prevent footer bouncing.

**Comment by nirawit-git** [comment]
INFO  Starting development server...
98% after emitting

 ERROR  Failed to compile with 2 errors                                                                                                                                                            23:40:34
This relative module was not found:

* ./src/main.js in multi

**Comment by saumyasinghal747** [comment]
This is a result of using `submit` in a form, rather than having an event to determine when the message is sent, such as when the user hits enter/clicks a button. Using `submit` is a signal to the OS that the task is completed.
