### ISSUE TITLE
Infinite number of chat rooms.

### ISSUE THREAD

**Issue by pisethx** [antoine92190/vue-advanced-chat#72]
It seems like the number of rooms is fixed. It would be great to implement infinite scroll where we can fetch more rooms. Or at least expose another rooms-footer slot. Thank you.

**Comment by hasanbasri1993** [comment]
very nice feature.

**Comment by antoine92190** [comment]
Indeed, I agree. Will implement infinite scroll for rooms list.
What would be the use of a room-footer slot?

**Comment by rancou** [comment]
> Indeed, I agree. Will implement infinite scroll for rooms list.
> What would be the use of a room-footer slot?

With the room footer slot, I can put a Loader component there where it can detect intersection so I can fetch more rooms when it is triggered.

**Comment by hasanbasri1993** [comment]
how about this feature ?

**Comment by antoine92190** [comment]
It’s in progress in infinite-rooms branch. Will probably release it next week.

**Comment by hasanbasri1993** [comment]
Thanks you very much for your reply very happy to hear that

**Comment by antoine92190** [comment]
Released in https://github.com/antoine92190/vue-advanced-chat/releases/tag/0.6.3
