### ISSUE TITLE
Add video UI

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#73]
It would be nice to have the webRTC or other video technology for video chat in future, more like slack. thanks.

**Comment by antoine92190** [comment]
Yes I was thinking about that. Will not implement it very soon but will definitely work on it at some point.

**Comment by radudiaconu0** [comment]
@antoine92190 it will be very good. i suggest a discord like interface for video ;) i work on a WebRTC chat app and i need some frontend ;)

**Comment by antoine92190** [comment]
Actually I don't think I’ll implement this feature. It’s a very heavy implementation and going out of the scope of a lightweight chat component. However the component should give you enough flexibility to implement it yourself.
