### ISSUE TITLE
Realtime in RoomList

### ISSUE THREAD

**Issue by hasanbasri1993** [antoine92190/vue-advanced-chat#74]
how to make realtime roomlist when new user and chatsroom added?

**Comment by antoine92190** [comment]
You can just update the `rooms` prop

**Comment by hasanbasri1993** [comment]
how to implement ?

**Comment by antoine92190** [comment]
You need to manage realtime outside of the component scope.
When an update is available, you need to update `rooms` prop (https://github.com/antoine92190/vue-advanced-chat#important-notes):

```
getRealtimeUpdates() {
  this.$set(this.rooms, roomIndex, room)
}
```

**Comment by hasanbasri1993** [comment]
hello @antoine92190 
how to detected an update is available ?
i still confuse how make Realtime in RoomList.

thanks u
