### ISSUE TITLE
Interfaces for Google Translate message

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#75]
Hi,

The people who chat may to speak the same language. It would be nice to have such interfaces such as functions and slots to  add google translate or other translate service to show the translated message below or somewhere. thanks.

**Comment by antoine92190** [comment]
I don't think I will implement this as it is too specific.
But you can manage it on your own using the `messageActions` prop:

```
messageActions="[
  {
    name: 'translateMessage',
    title: 'Translate Message'
  }
]"
```
Then when getting the callback, you can open a popup with the translated text.
