### ISSUE TITLE
[Improvement] Use kebab-case syntax instead of camelCase for emitted events

### ISSUE THREAD

**Issue by LouisMazel** [antoine92190/vue-advanced-chat#78]
## Is your feature request related to a problem? Please describe

Vue JS conventions: It is recommended that you always use kebab-case to name custom events. It is not recommended to use camelCase to name events. 

```html
<ChatWindow
   @fetchMessages="doSomething"
/>
```

[CF second point](https://learnvue.co/2020/01/12-vuejs-best-practices-for-pro-developers/)

## Describe the solution you'd like

Use

```js
this.$emit('fetch-messages', data)
```

So: 

```html
<ChatWindow
   @fetch-messages="doSomething"
/>
```

**Comment by antoine92190** [comment]
Yep, that's already on my todo list

**Comment by antoine92190** [comment]
Fixed https://github.com/antoine92190/vue-advanced-chat/commit/26861535298aa8cca444dc301924f7fc35c2b17a
