### ISSUE TITLE
[Prop API Options] room-message not works

### ISSUE THREAD

**Issue by LouisMazel** [antoine92190/vue-advanced-chat#79]
## Describe the bug

- When I set the prop API property `room-message`, it seems that it does not work

```html
<ChatWindow
   room-message="TEST"
/>
```

The textearea stay empty

### Others

- Second thing: In the `README.md` the type of `room-message` is `Object`, or it's a `String`, right ? 

- By the way: Always in the `README.md` in `text-messages` props API description: "Tapez votre message" or "Taper le message" instead of "Taper votre message"

## Expected behavior

The textarea must show the default string

**Comment by antoine92190** [comment]
Have you tried with `roomMessage`?

**Comment by LouisMazel** [comment]
Yes, it doesn't work

(But HTML/Vue attributes is always in `kebab-case`, to test the `camelCase` I should to disable eslint)

**Comment by LouisMazel** [comment]
**Update**: 

It's work when I change the value of `room-message`, so after the hot-reload update.
But not on init (reload page).

See this short video: [VIDEO](https://jumpshare.com/v/K8kMOv1XnoKLywaeo1xw)

Steps: 
1 - Init state
2 - I change the value of `room-message` --> hot reload --> Message is shown
3 - Reload page, no message shown

**FYI**: I use Nuxt.JS (but I think it's not a problem)

**Comment by antoine92190** [comment]
> Second thing: In the README.md the type of room-message is Object, or it's a String, right ?

> By the way: Always in the README.md in text-messages props API description: "Tapez votre message" or "Taper le message" instead of "Taper votre message"

Fixed https://github.com/antoine92190/vue-advanced-chat/commit/301a2d29c032630128b69e4877bc5d19e1c6d5cd

**Comment by antoine92190** [comment]
>When I set the prop API property room-message, it seems that it does not work

Fixed https://github.com/antoine92190/vue-advanced-chat/commit/93fb99fdacb53d8940b74decf949d2a4743741a1
