### ISSUE TITLE
Scroll icon always shown

### ISSUE THREAD

**Issue by cecilkootz** [antoine92190/vue-advanced-chat#81]
## Describe the bug

The scroll to bottom icon is always show when the window height is large.

## Steps to reproduce

Increasing the height causes the scroll to bottom to be shown over the most recent message sent by the user. 

## Expected behavior

Behave the same no matter the window height

### Good
![Screen Shot 2020-12-13 at 9 52 03 AM](https://user-images.githubusercontent.com/14874/102019560-2219c600-3d29-11eb-8c57-7a3e705df283.png)

### Bad
![Screen Shot 2020-12-13 at 9 51 41 AM](https://user-images.githubusercontent.com/14874/102019558-1cbc7b80-3d29-11eb-89b2-93f480919aed.png)

## Device (please complete the following information)

- OS: Mac
- Browser: Chrome v87
- Package version: 0.5.6

## Additional context

Tested locally with `height="calc(100vh - 50px)"` set on the `chat-window` component and got the same results.

**Comment by antoine92190** [comment]
Fixed https://github.com/antoine92190/vue-advanced-chat/commit/eda0e8ac10bcde54579c47f256c33d407f6dd6c6
