### ISSUE TITLE
[Improvements] Add option to choose file types allowed

### ISSUE THREAD

**Issue by LouisMazel** [antoine92190/vue-advanced-chat#82]
## Is your feature request related to a problem? Please describe

**In my case**: users can only send PNG, JPEG JPG, but he can select PDF or others types from the device

## Describe the solution you'd like

Add option to choose file types allowed like dropzone JS: [DropzoneJS Doc - AcceptedFiles](https://www.dropzonejs.com/#config-acceptedFiles)

**Comment by LouisMazel** [comment]
PR Ready - #83

**Comment by antoine92190** [comment]
Release in v.0.5.7
