### ISSUE TITLE
how to pass method props into slots

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#85]
hi,
`
<template #room-header-info="{ room, typingUsers, userStatus }">
                <div class="text-ellipsis">
                    <a href="#" @click="this.openUserProfile(room)">
                      <div class="room-name text-ellipsis">{{ room.roomName }}</div>
                   </a>
                  
`
I want open a model when click the roomName instead of click whole roomInfo bar. How can i inject the method like openUserProfile, as above this variable is null.

**Comment by antoine92190** [comment]
Why have you put `this` in a template?
This works fine for me:
```
<template v-slot:room-header-info="{ room }">
  <a href="#" @click="openUserProfile(room)">
    {{ room.roomName }}
  </a>
</template>
```

**Comment by tingan** [comment]
Hi,
your suggestion works. but there is an issue. that the original   roomInfo(room)  {} method will also called when click. how can i that when i click room name it execute openUserProfile method, while click other places it execute roomInfo method? thanks.
