### ISSUE TITLE
[Improvement](RoomHeaderInfo Slot) Update userStatus with user typing info

### ISSUE THREAD

**Issue by LouisMazel** [antoine92190/vue-advanced-chat#86]
## Is your feature request related to a problem? Please describe

On mobile device, the user can't know if the member is typing or not (because the sidebar is not displayed)

## Describe the solution you'd like

Update the userStatus when the user is typing to show the info on

<img width="498" alt="vue-advanced" src="https://user-images.githubusercontent.com/12446546/102066485-2cf05b80-3dfa-11eb-9f83-2755fa843012.png">

**Comment by antoine92190** [comment]
Can't you use `typingUsers` data from `room-header-info` slot?

**Comment by LouisMazel** [comment]
@antoine92190 

Ok my bad, I missed this data slot
