### ISSUE TITLE
Add room options dropdown

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#87]
Hi,
Checkbox to select multiple rooms for some actions such as empty the messages or delete the selected rooms. select all and unselect all. select by tags etc.

**Comment by antoine92190** [comment]
That's a nice idea, but I don't think I'll implement that anytime soon.

**Comment by antoine92190** [comment]
I don't think I'll implement multiple rooms selection, however as a middle ground I'll implement this feature:

<img width="358" alt="Screenshot 2021-01-17 at 09 57 24" src="https://user-images.githubusercontent.com/16256207/104835989-9c021980-58aa-11eb-86aa-36003e3212da.png">

**Comment by antoine92190** [comment]
Feature added https://github.com/antoine92190/vue-advanced-chat/commit/68b505e4b05c94fd936f61a3acde8a12683a9b17
