### ISSUE TITLE
room-avatar named slot

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#88]
Hi,
although currently the room-header-info make me possible to open a user profile model when click room name, but it makes more sense to open the model when click the room avatar (plus room name). But it seems that there is no room avatar slot, i just want to add the <a href > </a> wrap the room avatar picture. thanks.

**Comment by antoine92190** [comment]
You can use `roomInfo` event

**Comment by tingan** [comment]
roomInfo event triggered when whole head bar is clicked, not just the room avatar.

**Comment by antoine92190** [comment]
Ok, I can add a `room-avatar` slot

**Comment by tingan** [comment]
thx, as it's quite annoying when i accidentally click the head bar, a modal popup, even i meant to click the menu action dots

**Comment by antoine92190** [comment]
Fixed https://github.com/antoine92190/vue-advanced-chat/commit/e5a548f7b0e9431d3f33e56e53d4ed7eb04be713
