### ISSUE TITLE
Event API for a room item in room list is clicked

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#89]
Hi,
is the event API available for when a room item in the room list is clicked. I want to clear or rest unreadCount to zero when a room item is clicked. Thanks.

**Comment by antoine92190** [comment]
Please read the docs.
> fetchMessages is triggered every time a room is opened. If the room is opened for the first time, the options param will hold reset: true

**Comment by tingan** [comment]
Hi,
the problem is when a new message is sent, the new message is pushed by websockets, so the fetchMessages is not executed. only the new message is inserted. so the unreads will increase, but the fetchMessage is not called, so unreads will not cleared.

**Comment by antoine92190** [comment]
Then manage this in your websockets function.
If the websockets tries to increment the number of unreads but the room is already selected, don't increment.

**Comment by tingan** [comment]
Hi,
seems a good idea. thx.
