### ISSUE TITLE
Information about messages sent.(FEATURE REQUEST)

### ISSUE THREAD

**Issue by x-N0** [antoine92190/vue-advanced-chat#9]
## Is your feature request related to a problem? Please describe
No.
Users need to know who sen't a content (video, photo, etc..) and the basic information (who saw it, who recieved it).

## Describe the solution you'd like
Add optional prop with this purpose.

## Additional context
 Like in What'sApp and Facebook.

![imagen](https://user-images.githubusercontent.com/51316342/81454478-d1bf0200-9162-11ea-8d3a-8a8c8a638cf2.png)

In that btn menu you would add an "info" option, or "information", the name doesn't matter.

**Comment by antoine92190** [comment]
If there are only 2 users in the rooms, who sent the message and who received it is obvious.
If there are 3+ users in the room, the username is displayed on each message to know who sent it.

If you want to add more options in the menu showcased in your screenshot, you can use the `messageActions` prop coupled with the `messageActionHandler` event to create and manage your own options.

I just fixed an issue so you can get the message data when calling `messageActionHandler`: https://github.com/antoine92190/vue-advanced-chat/commit/60b872ad7a55d1edb2db36509869305ad9cc2ff6

Would that help with your issue?
