### ISSUE TITLE
vue-cli-service serve #error

### ISSUE THREAD

**Issue by kasungaya** [antoine92190/vue-advanced-chat#93]
Hi,

Issue  : "This relative module was not found:

* ./src/main.js in multi (webpack)-dev-server/client?http://"my IP address with port"&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js"

I clone the project then "npm install" and finally "npm run serve" but i'm getting this error please can you explain why i'm getting this error 

And i tried even "npm install -g webpack" and "npm install -g webpack-dev-server"

**Comment by antoine92190** [comment]
This component cannot be served as a vue project. You need to go in `demo` folder and serve it from there

**Comment by antoine92190** [comment]
You will also need to add your own firestore config in `demo/src/firestore/index.js`

**Comment by kasungaya** [comment]
yeah thanks got it
