### ISSUE TITLE
Multiple files upload

### ISSUE THREAD

**Issue by pisethx** [antoine92190/vue-advanced-chat#94]
Right now it seems like we can only upload one at a time. for both images and files.

I dig into the source code. It seems like its gonna need a lot of refactoring for this feature...

**Comment by antoine92190** [comment]
It sounds like a good idea, but I will not be able to work on it soon.
You can make a pull request for it, otherwise you'll need to wait.

**Comment by antoine92190** [comment]
For archiving purposes, here is the diff for the implementation: https://github.com/antoine92190/vue-advanced-chat/compare/f88196214cc56e1911f5574e6f549e0b01f74a51..7c735a41f0fb23a64824c4dae3eebbf79e248dad

**Comment by antoine92190** [comment]
Now available in v1.1.0
