### ISSUE TITLE
upload image by camera screenshot 

### ISSUE THREAD

**Issue by tingan** [antoine92190/vue-advanced-chat#95]
Hi,
for mobile, it's common to take a screenshot by camera and upload it. this feature will be very useful. thx.

**Comment by antoine92190** [comment]
That's already the case. On which browser and device are you testing?

**Comment by tingan** [comment]
Hi,
Maybe it's my MAMP Viewer issue (I test mobile in iphone with MAMP viewer), when i click camera, it crash. others like select photo from library all works fine.
